const {randomUUID}=require('node:crypto');const {assertTransition}=require('../state/dispatch-state-machine');
function createDispatchAuthority({db,audit=()=>{},notify=()=>{}}){
 function tx(fn){db.exec('BEGIN IMMEDIATE');try{const r=fn();db.exec('COMMIT');return r;}catch(e){db.exec('ROLLBACK');throw e;}}
 function getBooking(id){return db.prepare('SELECT b.*,p.status payment_status FROM bookings b JOIN payments p ON p.booking_id=b.id WHERE b.id=?').get(id);}
 function expire(){const now=new Date().toISOString();db.prepare("UPDATE dispatch_assignments SET status='EXPIRED' WHERE status='OFFERED' AND lease_expires_at<=?").run(now);}
 function offer({bookingId,driverId,idempotencyKey,leaseMs=30000,actor}){if(!idempotencyKey)throw Object.assign(new Error('IDEMPOTENCY_KEY_REQUIRED'),{code:'IDEMPOTENCY_KEY_REQUIRED'});return tx(()=>{expire();const prior=db.prepare('SELECT * FROM dispatch_assignments WHERE idempotency_key=?').get(idempotencyKey);if(prior)return {...prior,duplicate:true};const b=getBooking(bookingId);if(!b)throw Object.assign(new Error('BOOKING_NOT_FOUND'),{code:'BOOKING_NOT_FOUND'});if(b.status!=='confirmed'||b.payment_status!=='paid')throw Object.assign(new Error('PAYMENT_OR_BOOKING_NOT_CONFIRMED'),{code:'PAYMENT_OR_BOOKING_NOT_CONFIRMED'});const d=db.prepare("SELECT id,verified FROM users WHERE id=? AND role='driver'").get(driverId);if(!d||d.verified!==1)throw Object.assign(new Error('DRIVER_INELIGIBLE'),{code:'DRIVER_INELIGIBLE'});const conflict=db.prepare("SELECT id FROM dispatch_assignments WHERE driver_id=? AND status IN ('OFFERED','ACCEPTED','ASSIGNED','DRIVER_EN_ROUTE','ARRIVED','TRIP_STARTED')").get(driverId);if(conflict)throw Object.assign(new Error('ASSIGNMENT_CONFLICT'),{code:'ASSIGNMENT_CONFLICT'});const id=randomUUID(),now=new Date().toISOString(),exp=new Date(Date.now()+leaseMs).toISOString();db.prepare('INSERT INTO dispatch_assignments(id,booking_id,driver_id,status,lease_expires_at,idempotency_key,version,created_at,updated_at) VALUES(?,?,?,?,?,?,1,?,?)').run(id,bookingId,driverId,'OFFERED',exp,idempotencyKey,now,now);audit(actor,'dispatch.offered',bookingId,{assignmentId:id,driverId});return db.prepare('SELECT * FROM dispatch_assignments WHERE id=?').get(id);});}
 function accept({assignmentId,driverId,actor}){return tx(()=>{expire();let a=db.prepare('SELECT * FROM dispatch_assignments WHERE id=?').get(assignmentId);if(!a)throw Object.assign(new Error('ASSIGNMENT_NOT_FOUND'),{code:'ASSIGNMENT_NOT_FOUND'});if(a.driver_id!==driverId)throw Object.assign(new Error('NOT_ASSIGNMENT_DRIVER'),{code:'NOT_ASSIGNMENT_DRIVER'});if(a.status==='ASSIGNED')return {...a,duplicate:true};assertTransition(a.status,'ACCEPTED');db.prepare("UPDATE dispatch_assignments SET status='ACCEPTED',version=version+1,updated_at=? WHERE id=?").run(new Date().toISOString(),a.id);assertTransition('ACCEPTED','ASSIGNED');db.prepare("UPDATE dispatch_assignments SET status='ASSIGNED',lease_expires_at=NULL,version=version+1,updated_at=? WHERE id=?").run(new Date().toISOString(),a.id);db.prepare("UPDATE bookings SET driver_id=?,status='assigned' WHERE id=? AND status='confirmed'").run(driverId,a.booking_id);audit(actor,'driver.assigned',a.booking_id,{assignmentId:a.id,driverId});notify(driverId,'A viewing trip has been assigned to you.');const b=db.prepare('SELECT customer_id FROM bookings WHERE id=?').get(a.booking_id);if(b)notify(b.customer_id,'Driver assigned to your viewing.');return db.prepare('SELECT * FROM dispatch_assignments WHERE id=?').get(a.id);});}
 function reject({assignmentId,driverId,actor}){return tx(()=>{const a=db.prepare('SELECT * FROM dispatch_assignments WHERE id=?').get(assignmentId);if(!a)throw Object.assign(new Error('ASSIGNMENT_NOT_FOUND'),{code:'ASSIGNMENT_NOT_FOUND'});if(a.driver_id!==driverId)throw Object.assign(new Error('NOT_ASSIGNMENT_DRIVER'),{code:'NOT_ASSIGNMENT_DRIVER'});if(a.status==='REJECTED')return {...a,duplicate:true};assertTransition(a.status,'REJECTED');db.prepare("UPDATE dispatch_assignments SET status='REJECTED',lease_expires_at=NULL,version=version+1,updated_at=? WHERE id=?").run(new Date().toISOString(),a.id);audit(actor,'dispatch.rejected',a.booking_id,{assignmentId:a.id,driverId});return db.prepare('SELECT * FROM dispatch_assignments WHERE id=?').get(a.id);});}
 function transition({assignmentId,to,actor}){return tx(()=>{const a=db.prepare('SELECT * FROM dispatch_assignments WHERE id=?').get(assignmentId);if(!a)throw Object.assign(new Error('ASSIGNMENT_NOT_FOUND'),{code:'ASSIGNMENT_NOT_FOUND'});if(a.status===to)return {...a,duplicate:true};assertTransition(a.status,to);db.prepare('UPDATE dispatch_assignments SET status=?,version=version+1,updated_at=? WHERE id=?').run(to,new Date().toISOString(),a.id);if(to==='TRIP_COMPLETED')db.prepare("UPDATE bookings SET status='completed' WHERE id=? AND status='assigned'").run(a.booking_id);audit(actor,'dispatch.'+to.toLowerCase(),a.booking_id,{assignmentId:a.id});return db.prepare('SELECT * FROM dispatch_assignments WHERE id=?').get(a.id);});}
 return {offer,accept,reject,transition,expire};}
module.exports={createDispatchAuthority};