(() => {
 'use strict';
 const {api,node,button,perform,refresh,getUser,status}=window.R2V;
 const $=id=>document.getElementById(id);let selected=[],accountId=null;
 function field(f,label,name,type='text',value=''){const l=node('label',label),i=node('input');i.name=name;i.type=type;i.value=value;l.append(i);f.append(l);return i;}
 function select(f,label,name,rows,value){const l=node('label',label),i=node('select');i.name=name;for(const [v,t]of rows){const o=node('option',t);o.value=v;i.append(o);}if(value)i.value=value;l.append(i);f.append(l);return i;}
 function form(label,action){const f=node('form'),b=node('button',label);b.type='submit';f.addEventListener('submit',e=>{e.preventDefault();perform(async()=>{await action(Object.fromEntries(new FormData(f)));await refresh();},b);});f.append(b);return f;}
 async function addProperty(p){if(getUser()?.role!=='customer')throw new Error('Sign in as a customer to plan a viewing package');if(selected.some(s=>s.property.id===p.id))throw new Error('Property is already in this itinerary');if(selected.length>=3)throw new Error('Choose up to three properties');const slots=(await api('/properties/'+p.id+'/slots')).slots;if(!slots.length)throw new Error('No available slots for this property');selected.push({property:p,slots});renderPlanner();$('journey-planner').scrollIntoView({behavior:'smooth'});}
 function renderPlanner(){const target=$('journey-planner');target.replaceChildren(node('h3','Plan up to three property viewings'));if(!selected.length){target.append(node('p','Search properties and choose “Add to viewing package”. Add them in visit order.'));return;}
 const f=form('Request reviewed package quote',async d=>{const participants=d.participants.split('\n').map(s=>s.trim()).filter(Boolean).map(name=>({name,relationship:'viewing participant'}));await api('/journeys','POST',{stops:selected.map((s,i)=>({listingId:s.property.id,slotId:d['slot'+i]})),tier:d.tier,returnJourney:d.returnJourney==='yes',participants,idempotencyKey:crypto.randomUUID()});selected=[];status('Package plan saved. Operations will review transfer distances and times before quoting.');});
 selected.forEach((s,i)=>{const row=node('div',null,'app-card');row.append(node('p',`${i+1}. ${s.property.title}`),button('Remove '+s.property.title,async()=>{selected.splice(i,1);renderPlanner();}));f.append(row);select(f,'Viewing time for '+s.property.title,'slot'+i,s.slots.map(v=>[v.id,new Date(v.start_at).toLocaleString()+' – '+new Date(v.end_at).toLocaleTimeString()]));});
 select(f,'Ride tier','tier',[['general','General'],['vip','VIP']]);select(f,'Return journey','returnJourney',[['no','One way'],['yes','Include return']]);const l=node('label','Participants (one name per line, maximum four)'),input=node('textarea');input.name='participants';input.value=getUser().name;input.required=true;l.append(input);f.append(l,node('p','Operations reviews the route estimate. You will see and accept the price before agents confirm and payment is requested.'));target.append(f);}
 function renderProfile(p,wallet){const target=$('journey-profile');target.replaceChildren(node('h3','Contact and pickup profile'));const f=form('Save contact and pickup',d=>api('/customer/details','PUT',{...d,version:p.version}));field(f,'Phone','phone','tel',p.details.phone||'').required=true;field(f,'Pickup address','pickup','text',p.details.pickup||'').required=true;select(f,'Preferred contact','preferredContact',[['phone','Phone'],['email','Email'],['sms','SMS'],['whatsapp','WhatsApp']],p.details.preferredContact);field(f,'Accessibility or pickup instructions','accessibilityNotes','text',p.details.accessibilityNotes||'');target.append(f,node('p',`Viewing credits: KES ${wallet.balanceKES}. Contact preferences are recorded; external messages require a connected provider.`));const history=node('details');history.append(node('summary','Profile and qualification history'));for(const h of p.history)history.append(node('p',`${new Date(h.created_at).toLocaleString()} · ${h.snapshot.details?'Contact and pickup updated':`${h.snapshot.city||'City unset'} · budget KES ${h.snapshot.budget||0} · ${h.snapshot.goal||'Goal unset'}`}`));for(const q of p.qualifications)history.append(node('p',`${new Date(q.created_at).toLocaleString()} · ${q.snapshot.status} · property price KES ${q.snapshot.listingPrice}`));target.append(history);}
 function quoteForm(j,card){const f=form('Publish reviewed quote',d=>api('/journeys/'+j.id+'/quote','POST',{version:j.version,route:{legs:j.plan.stops.slice(1).map((s,i)=>({distanceMetres:Math.round(Number(d['km'+i])*1000),minutes:Number(d['minutes'+i])})),waitingMinutes:Number(d.waitingMinutes),evidenceRef:d.evidenceRef}}));j.plan.stops.slice(1).forEach((s,i)=>{field(f,`Transfer ${i+1} distance (km)`,'km'+i,'number').step='0.001';field(f,`Transfer ${i+1} minutes`,'minutes'+i,'number').min='1';});field(f,'Estimated additional waiting minutes','waitingMinutes','number',0).min='0';field(f,'Route review evidence reference','evidenceRef').required=true;card.append(f);}
 async function rescheduleForm(j,card){const f=form('Reschedule whole package',d=>api('/journeys/'+j.id+'/reschedule','POST',{version:j.version,slotIds:j.plan.stops.map((s,i)=>d['slot'+i])}));for(let i=0;i<j.plan.stops.length;i++){const s=j.plan.stops[i],slots=(await api('/properties/'+s.listingId+'/slots')).slots;select(f,'New slot for property '+(i+1),'slot'+i,slots.map(v=>[v.id,new Date(v.start_at).toLocaleString()]));}card.append(f);}
 async function renderJourneys(rows,user){const target=$('journey-list');target.replaceChildren();if(!rows.length)target.append(node('p','No viewing packages yet.'));for(const j of rows){const card=node('article',null,'app-card');card.dataset.journeyId=j.id;card.append(node('h3','Viewing package · '+j.status),node('p','Package reference: '+j.id));if(j.plan.contact&&['customer','admin','driver'].includes(user.role))card.append(node('p','Pickup: '+j.plan.contact.pickup),node('p','Participants: '+j.plan.participants.map(p=>p.name).join(', ')));
 for(const s of j.stops){const row=node('div',null,'app-card');row.append(node('h4',`${s.position+1}. ${s.listing.title}`),node('p',`${new Date(s.startAt).toLocaleString()} · Agent ${s.request_status} · Stop ${s.status}`));if(['agent','admin'].includes(user.role)&&j.status==='PENDING_AGENTS'&&s.request_status==='REQUESTED'){row.append(button('Confirm package stop',async()=>{await api('/journeys/'+j.id+'/stops/'+s.position+'/confirm','POST',{version:j.version,decision:'ACCEPTED'});await refresh();}));const df=form('Decline whole package',d=>api('/journeys/'+j.id+'/stops/'+s.position+'/confirm','POST',{version:j.version,decision:'DECLINED',reason:d.reason}));field(df,'Decline reason','reason').required=true;row.append(df);}if(['driver','admin'].includes(user.role)&&j.status==='IN_PROGRESS'&&s.status!=='COMPLETED')row.append(button('Complete package stop '+(s.position+1),async()=>{await api('/journeys/'+j.id+'/stops/'+s.position+'/complete','POST',{version:j.version});await refresh();}));if(s.outcome)row.append(node('p','Outcome: '+s.outcome.outcome));else if(s.status==='COMPLETED'&&['customer','admin'].includes(user.role)){const of=form('Record property outcome',d=>api('/viewing-requests/'+s.request_id+'/outcome','POST',d));select(of,'Outcome','outcome',[['INTERESTED','Interested'],['NOT_INTERESTED','Not interested'],['FOLLOW_UP','Follow up']]);field(of,'Outcome notes','notes');row.append(of);}card.append(row);}
 if(!j.stops.length)j.plan.stops.forEach((s,i)=>card.append(node('p',`Planned stop ${i+1}: ${s.listingId}`)));
 if(j.quote){const q=j.quote;card.append(node('p',`Quoted total KES ${q.totalKES} · policy ${q.policyVersion}: ${q.policy.label}`),node('p',`Base KES ${q.baseKES} · inter-property distance KES ${(q.distanceMinor/100).toFixed(2)} · return KES ${(q.returnMinor/100).toFixed(2)} · waiting KES ${(q.waitingMinor/100).toFixed(2)} · rounding KES ${(q.roundingMinor/100).toFixed(2)}`),node('p',q.policy.cancellation),node('p',q.policy.routeMode),node('p',q.policy.taxMode));if(j.status==='QUOTED')card.append(node('p','Quote expires '+new Date(j.quote_expires_at).toLocaleString()));}
 if(user.role==='admin'&&['DRAFT','QUOTED'].includes(j.status))quoteForm(j,card);
 if(user.role==='customer'&&j.status==='QUOTED'){const f=form('Accept price and request all agents',async d=>{if(d.acceptPolicy!=='on')throw new Error('Accept the displayed pricing and cancellation policy');await api('/journeys/'+j.id+'/accept','POST',{version:j.version,acceptPolicy:true,useCredits:d.useCredits==='on'});});field(f,'I accept the displayed price and cancellation policy','acceptPolicy','checkbox').value='on';field(f,'Use available viewing credits','useCredits','checkbox').value='on';card.append(f);}
 if(j.status==='PENDING_AGENTS'&&j.plan.confirmationExpiresAt)card.append(node('p','Agent confirmation deadline: '+new Date(j.plan.confirmationExpiresAt).toLocaleString()));
 if(j.payment)card.append(node('p',`Package payment: ${j.payment.status} · amount due KES ${j.payment.amount} · credits used KES ${j.credit_amount}`));
 if(j.status==='PAYABLE'&&user.role==='customer')card.append(node('p','Pay only the package amount through operations. Payment confirms every viewing hold together.'));
 if(['driver','admin'].includes(user.role)&&j.status==='ASSIGNED')card.append(button('Start package transport',async()=>{await api('/journeys/'+j.id+'/start','POST',{});await refresh();}));
 if(['driver','admin'].includes(user.role)&&j.status==='IN_PROGRESS'&&j.stops.every(s=>s.status==='COMPLETED'))card.append(button('Finish package transport and return',async()=>{await api('/journeys/'+j.id+'/finish','POST',{});await refresh();}));
 if(['customer','admin'].includes(user.role)&&!['IN_PROGRESS','COMPLETED','CANCELLED','DECLINED','EXPIRED'].includes(j.status)){const cf=form('Cancel whole package',d=>api('/journeys/'+j.id+'/cancel','POST',{...d,version:j.version}));field(cf,'Cancellation reason','reason').required=true;select(cf,'Paid amount disposition','disposition',[['REFUND','Refund to original payment (operations settlement)'],['CREDIT','Viewing credits']]);card.append(cf);if(['PENDING_AGENTS','PAYABLE','CONFIRMED','ASSIGNED'].includes(j.status)){const details=node('details');details.append(node('summary','Reschedule all properties'));details.append(button('Load replacement availability',async()=>{details.replaceChildren(node('summary','Reschedule all properties'));await rescheduleForm(j,details);}));card.append(details);}}
 if(j.refund){card.append(node('p',`Cash refund: ${j.refund.status} · KES ${j.refund.amount}`));if(user.role==='admin'&&j.refund.status==='PENDING'){const f=form('Record completed refund transfer',d=>api('/journeys/'+j.id+'/refund','POST',{reference:d.reference,amount:j.refund.amount}));field(f,'Actual refund transaction reference','reference').required=true;card.append(f);}}
 if(j.events){const events=node('details');events.append(node('summary','Journey timeline'));for(const e of j.events)events.append(node('p',`${new Date(e.created_at).toLocaleString()} · ${e.event}`));card.append(events);}target.append(card);}}
 async function update(user){$('journey-workspace').hidden=!user;if(!user){selected=[];accountId=null;return;}if(accountId!==user.id){selected=[];accountId=user.id;}$('journey-customer').hidden=user.role!=='customer';if(user.role==='customer'){const [p,w]=await Promise.all([api('/customer/details'),api('/customer/credits')]);renderProfile(p,w);renderPlanner();}await renderJourneys((await api('/journeys')).journeys,user);}
 window.R2VJourney={refresh:update,addProperty};
})();
