(() => {
 'use strict';
 const {api,node,button,perform,refresh,getUser,status}=window.R2V;
 const $=id=>document.getElementById(id);
 let dashboard=null,users=[];
 function field(f,label,name,type='text',value=''){const l=node('label',label),i=node('input');i.name=name;i.type=type;i.value=value;l.append(i);f.append(l);return i;}
 function select(f,label,name,values,value){const l=node('label',label),i=node('select');i.name=name;for(const [v,t] of values){const o=node('option',t);o.value=v;i.append(o);}if(value)i.value=value;l.append(i);f.append(l);return i;}
 function form(label,action){const f=node('form'),b=node('button',label);b.type='submit';f.append(b);f.addEventListener('submit',e=>{e.preventDefault();perform(async()=>{await action(Object.fromEntries(new FormData(f)),f);await refresh();},b);});return f;}
 async function upload(d,f){const file=f.querySelector('[name=file]').files[0];if(!file||file.size>2097152)throw new Error('Choose a PDF, PNG or JPEG up to 2 MiB');const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(const b of bytes)binary+=String.fromCharCode(b);await api('/mobility/documents','POST',{kind:d.kind,name:file.name,mime:file.type,data:btoa(binary),expiresAt:new Date(d.expiresAt).toISOString()});status('Private mobility evidence uploaded.');}
 function renderEvidence(user,target){target.append(node('h3','Private mobility evidence'));const f=form('Upload mobility evidence',upload);select(f,'Evidence kind','kind',(user.role==='driver'?dashboard.requirements:['identity','selfie','women_eligibility','enrolment']).map(k=>[k,k]));const file=field(f,'PDF, PNG or JPEG','file','file');file.accept='.pdf,.png,.jpg,.jpeg';file.required=true;field(f,'Evidence expiry (device local time)','expiresAt','datetime-local').required=true;target.append(f);
 for(const d of dashboard.documents){const row=node('p'),link=node('a',d.name+' · '+d.kind);link.href='/api/mobility/documents/'+d.id;link.target='_blank';link.rel='noopener';row.append(link,node('span',' · expires '+new Date(d.expires_at).toLocaleDateString()));target.append(row);}
 const kinds=user.role==='driver'?['driver','women_driver']:['women_rider','student'];for(const kind of kinds){const needed=kind==='driver'?dashboard.requirements:kind==='women_driver'?['identity','selfie']:kind==='women_rider'?['identity','selfie','women_eligibility']:['identity','enrolment'];const docs=dashboard.documents.filter(d=>needed.includes(d.kind));const sf=form('Submit '+kind+' review',async(d,f)=>{if(d.adultConfirmed!=='on')throw new Error('Adult pilot confirmation required');const ids=Array.from(f.querySelectorAll('[name=evidence]:checked')).map(i=>i.value);await api('/mobility/checks/'+kind+'/submit','POST',{documentIds:ids,adultConfirmed:true,...(kind==='student'?{institution:d.institution}:{})});status('Mobility evidence submitted for operations review.');});sf.append(node('p',kind+' evidence required: '+needed.join(', ')));for(const doc of docs){const input=field(sf,doc.name,'evidence','checkbox');input.value=doc.id;}if(kind==='student')field(sf,'Institution name','institution').required=true;field(sf,'I confirm adult pilot participation','adultConfirmed','checkbox').value='on';target.append(sf);}
 for(const c of dashboard.checks)target.append(node('p',`${c.kind}: ${c.status} · ${c.currentlyEligible?'Current eligibility':'Not currently eligible'}${c.reason?' · '+c.reason:''}`));
 }
 function renderDriver(target){const p=dashboard.profile;target.replaceChildren(node('h3','Driver and vehicle onboarding'));const f=form('Save driver profile',d=>api('/driver/profile','PUT',{...d,capacity:Number(d.capacity),revision:p.revision}));for(const [name,label]of [['legalName','Legal name'],['phone','Phone'],['plate','Vehicle plate'],['make','Vehicle make'],['model','Vehicle model'],['licenceNumber','Licence number']])field(f,label,name,'text',p.payload[name]||'').required=true;field(f,'Passenger capacity','capacity','number',p.payload.capacity||4).min='1';select(f,'Gender declaration (separate review required for Women-Only)','gender',[['undisclosed','Undisclosed'],['female','Female'],['male','Male']],p.payload.gender);target.append(f,node('p','Profile changes invalidate driver and Women-Only approval. Evidence review is an operational check; no government or biometric provider is connected.'),button(p.online?'Go offline':'Go online',async()=>{await api('/driver/availability','PUT',{online:!p.online});await refresh();}));renderEvidence(getUser(),target);}
 function renderReviewer(target){target.replaceChildren(node('h3','Mobility evidence review'));for(const c of dashboard.reviews){const card=node('article',null,'app-card');card.dataset.mobilitySubject=c.subject_id;card.dataset.mobilityKind=c.kind;card.append(node('h4',`${c.kind} · ${c.status}`),node('p','Account: '+c.subject_id));if(c.profile)card.append(node('p',`${c.profile.legalName} · ${c.profile.plate} · ${c.profile.make} ${c.profile.model} · capacity ${c.profile.capacity} · declared gender ${c.profile.gender}`));for(const d of c.documents){const link=node('a',d.kind+' · '+d.name);link.href='/api/mobility/documents/'+d.id;link.target='_blank';link.rel='noopener';card.append(link,node('p','Evidence expires '+new Date(d.expires_at).toLocaleString()));}if(['PENDING','APPROVED'].includes(c.status)){const f=form('Record mobility review',d=>api('/admin/mobility-reviews/'+c.subject_id+'/'+c.kind,'POST',{revision:c.revision,decision:d.decision,reason:d.reason,adultVerified:d.adultVerified==='on',womenEligibilityVerified:d.womenEligibilityVerified==='on',enrolmentVerified:d.enrolmentVerified==='on',...(d.decision==='APPROVED'?{expiresAt:new Date(d.expiresAt).toISOString()}:{})}));select(f,'Decision','decision',c.status==='PENDING'?[['APPROVED','Approve'],['REJECTED','Reject'],['REVOKED','Revoke']]:[['REVOKED','Revoke']]);field(f,'Evidence assessment and adult eligibility reason','reason').required=true;field(f,'I reviewed adult pilot eligibility','adultVerified','checkbox').value='on';if(['women_driver','women_rider'].includes(c.kind))field(f,'I verified Women-Only eligibility from reviewed evidence','womenEligibilityVerified','checkbox').value='on';if(c.kind==='student')field(f,'I verified current institution enrolment','enrolmentVerified','checkbox').value='on';field(f,'Review expiry no later than evidence expiry','expiresAt','datetime-local');card.append(f);}target.append(card);}}
 function renderPolicy(target,p){target.replaceChildren(node('h3','Ride2Go commercial policy'));target.append(node('p',p.policy?`Current version ${p.version}: ${p.policy.label}`:p.reason));if(getUser().role!=='admin')return;const f=form('Publish Ride2Go pricing policy',d=>api('/ride2go/pricing','POST',{label:d.label,baseKES:Object.fromEntries(['general','women','students','vip'].map(k=>[k,Number(d[k])])),perKmKES:Number(d.perKmKES),returnPercent:Number(d.returnPercent),waitingKESPerTwoMinutes:Number(d.waitingKESPerTwoMinutes),waitingGraceMinutes:Number(d.waitingGraceMinutes)}));field(f,'Policy label','label','text',p.policy?.label||'Operations-reviewed pilot').required=true;for(const tier of ['general','women','students','vip'])field(f,tier+' base fare KES',tier,'number',p.policy?.baseKES[tier]||'').required=true;for(const [k,l,v]of [['perKmKES','KES per kilometre',''],['returnPercent','Return percentage of base',50],['waitingKESPerTwoMinutes','KES per two-minute waiting block',0],['waitingGraceMinutes','Waiting grace minutes',0]])field(f,l,k,'number',p.policy?.[k]??v).required=true;target.append(f);}
 function requestForm(target){target.replaceChildren(node('h3','Request a standalone ride'));const f=form('Request Ride2Go quote',d=>api('/ride2go/trips','POST',{pickup:d.pickup,destination:d.destination,phone:d.phone,tier:d.tier,passengers:Number(d.passengers),returnJourney:d.returnJourney==='yes',scheduledAt:new Date(d.scheduledAt).toISOString(),idempotencyKey:crypto.randomUUID()}));field(f,'Pickup address','pickup').required=true;field(f,'Destination','destination').required=true;field(f,'Contact phone','phone','tel').required=true;field(f,'Departure (device local time)','scheduledAt','datetime-local').required=true;field(f,'Passengers','passengers','number',1).min='1';select(f,'Ride tier','tier',[['general','General'],['women','Women-Only (verified rider and driver)'],['students','Student (verified enrolment)'],['vip','VIP']]);select(f,'Return journey','returnJourney',[['no','One way'],['yes','Include return']]);target.append(f,node('p','Women-Only and Student pilots accept one verified adult account holder. Pooling and live tracking are not connected. Operations reviews the route and fare before payment.'));}
 function driverOptions(tier){return users.filter(u=>u.role==='driver'&&u.mobilityEligible&&u.online&&(tier!=='women'||dashboard.reviews.some(c=>c.subject_id===u.id&&c.kind==='women_driver'&&c.status==='APPROVED'&&c.expires_at>new Date().toISOString()))).map(u=>[u.id,u.name]);}
 function renderTrips(rows,target,user){target.replaceChildren();if(!rows.length)target.append(node('p','No standalone rides yet.'));for(const r of rows){const card=node('article',null,'app-card');card.dataset.rideId=r.id;card.append(node('h3',`${r.plan.pickup} → ${r.plan.destination}`),node('p',`${r.status} · ${r.plan.tier} · ${r.plan.passengers} passenger(s) · ${new Date(r.plan.scheduledAt).toLocaleString()}`),node('p','Ride reference: '+r.id));if(r.assignment)card.append(node('p','Driver assignment: '+r.assignment.status+(r.assignment.lease_expires_at?' · response deadline '+new Date(r.assignment.lease_expires_at).toLocaleTimeString():'')));if(r.driver)card.append(node('p',`Driver: ${r.driver.name} · ${r.driver.plate} · ${r.driver.make} ${r.driver.model}`));if(r.pickupCode)card.append(node('p','Private pickup code: '+r.pickupCode));
 if(r.quote){const q=r.quote;card.append(node('p',`Quoted fare KES ${q.totalKES} · policy ${q.policyVersion}: ${q.policy.label}`),node('p',`Base ${(q.baseMinor/100).toFixed(2)} · distance ${(q.distanceMinor/100).toFixed(2)} · return ${(q.returnMinor/100).toFixed(2)} · waiting ${(q.waitingMinor/100).toFixed(2)} · rounding ${(q.roundingMinor/100).toFixed(2)}`),node('p',q.policy.cancellation),node('p',q.policy.routeMode),node('p',q.policy.taxMode));}
 if(user.role==='admin'&&['REQUESTED','QUOTED'].includes(r.status)){const f=form('Publish Ride2Go quote',d=>api('/ride2go/trips/'+r.id+'/quote','POST',{version:r.version,distanceMetres:Math.round(Number(d.distanceKm)*1000),minutes:Number(d.minutes),waitingMinutes:Number(d.waitingMinutes),evidenceRef:d.evidenceRef}));field(f,'Reviewed route distance km','distanceKm','number').step='0.001';field(f,'Reviewed duration minutes','minutes','number').min='1';field(f,'Estimated extra waiting minutes','waitingMinutes','number',0);field(f,'Reviewed route evidence reference','evidenceRef').required=true;card.append(f);}
 if(user.role==='customer'&&r.status==='QUOTED'){const f=form('Accept Ride2Go fare',d=>{if(d.acceptPolicy!=='on')throw new Error('Accept the displayed price and cancellation policy');return api('/ride2go/trips/'+r.id+'/accept','POST',{version:r.version,acceptPolicy:true});});field(f,'I accept the displayed fare and cancellation policy','acceptPolicy','checkbox').value='on';card.append(f);}
 if(r.payment)card.append(node('p',`Payment: ${r.payment.status} · KES ${r.payment.amount}. Operations verifies actual received payment; no Ride2Go collection provider is connected.`));
 if(user.role==='admin'&&r.status==='PAYABLE'){const f=form('Verify Ride2Go payment',d=>api('/ride2go/trips/'+r.id+'/verify','POST',{reference:d.reference,amount:r.payment.amount}));field(f,'Received transaction reference','reference').required=true;card.append(f);}
 if(user.role==='admin'&&r.status==='CONFIRMED'){const f=form('Offer Ride2Go to driver',d=>api('/ride2go/trips/'+r.id+'/offer','POST',{driverId:d.driverId,idempotencyKey:crypto.randomUUID()}));select(f,'Eligible online driver','driverId',driverOptions(r.plan.tier));card.append(f);}
 if(user.role==='driver'&&r.assignment?.status==='OFFERED'){for(const [label,decision]of [['Accept Ride2Go','ACCEPTED'],['Reject Ride2Go','REJECTED']])card.append(button(label,async()=>{await api('/ride2go/assignments/'+r.assignment.id+'/respond','POST',{decision});await refresh();}));}
 if(user.role==='admin'&&['ASSIGNED','ARRIVED'].includes(r.status)){const rf=form('Reissue private pickup code',d=>api('/ride2go/trips/'+r.id+'/resetCode','POST',{version:r.version,reason:d.reason}));field(rf,'Customer recovery verification evidence','reason').required=true;card.append(rf);}
 if(user.role==='driver'&&['ASSIGNED','ARRIVED','IN_PROGRESS'].includes(r.status)){const action={ASSIGNED:'arrive',ARRIVED:'start',IN_PROGRESS:'complete'}[r.status];const f=form({arrive:'Confirm Ride2Go arrival',start:'Start Ride2Go trip',complete:'Complete Ride2Go trip'}[action],d=>api('/ride2go/trips/'+r.id+'/'+action,'POST',{version:r.version,...(action==='start'?{pickupCode:d.pickupCode}:{})}));if(action==='start')field(f,'Rider-provided pickup code','pickupCode').required=true;card.append(f);}
 if(['customer','admin'].includes(user.role)&&!['IN_PROGRESS','COMPLETED','CANCELLED','EXPIRED'].includes(r.status)){const f=form('Cancel Ride2Go',d=>api('/ride2go/trips/'+r.id+'/cancel','POST',{version:r.version,reason:d.reason}));field(f,'Cancellation reason','reason').required=true;card.append(f);}
 if(r.refund){card.append(node('p',`Refund: ${r.refund.status} · KES ${r.refund.amount}`));if(user.role==='admin'&&r.refund.status==='PENDING'){const f=form('Record Ride2Go refund transfer',d=>api('/ride2go/trips/'+r.id+'/refund','POST',{reference:d.reference,amount:r.refund.amount}));field(f,'Actual refund transaction reference','reference').required=true;card.append(f);}}
 target.append(card);
 }}
 async function update(user){$('mobility-workspace').hidden=!user||user.role==='agent';if(!user||user.role==='agent')return;dashboard=await api('/mobility/dashboard');$('mobility-driver').hidden=user.role!=='driver';$('mobility-customer').hidden=user.role!=='customer';$('mobility-reviewer').hidden=user.role!=='admin';if(user.role==='driver')renderDriver($('mobility-driver'));if(user.role==='customer'){$('mobility-customer').replaceChildren();renderEvidence(user,$('mobility-customer'));requestForm($('ride2go-request'));}if(user.role==='admin'){users=(await api('/admin/users')).users;renderReviewer($('mobility-reviewer'));}renderPolicy($('ride2go-policy'),await api('/ride2go/pricing'));$('ride2go-request').hidden=user.role!=='customer';renderTrips((await api('/ride2go/trips')).trips,$('ride2go-trips'),user);}
 window.R2VMobility={refresh:update};
})();
