(() => {
 'use strict';
 const {api,node,button,perform,refresh,getUser,status}=window.R2V;
 const root=node('section');root.id='operations-workspace';root.hidden=true;document.getElementById('app-workspace').append(root);
 let openSections=new Set();
 let generation=0,sharing=null,sequence=Date.now(),gpsBusy=false,pollBusy=false;
 function field(f,label,name,type='text',value=''){const l=node('label',label),i=node('input');i.name=name;i.type=type;i.value=value;i.required=type!=='checkbox';if(type==='number')i.step='any';l.append(i);f.append(l);return i;}
 function check(f,label,name){field(f,label,name,'checkbox').value='on';}
 function select(f,label,name,choices,value){const l=node('label',label),i=node('select');i.name=name;for(const [v,t]of choices){const o=node('option',t);o.value=v;i.append(o);}if(value)i.value=value;l.append(i);f.append(l);return i;}
 function form(label,action){const f=node('form'),b=node('button',label);b.type='submit';f.append(b);f.addEventListener('submit',e=>{e.preventDefault();perform(async()=>{await action(Object.fromEntries(new FormData(f)),f);await refresh();},b);});return f;}
 function link(target,label,url){const a=node('a',label);a.href=url;a.target='_blank';a.rel='noopener noreferrer';target.append(a);}
 function section(title){const e=node('details');e.append(node('summary',title));root.append(e);return e;}
 const tripPath=t=>'/operations/trips/'+t.kind+'/'+t.id;
 function currentPosition(){return new Promise((resolve,reject)=>{if(!navigator.geolocation)return reject(new Error('Geolocation is unavailable'));navigator.geolocation.getCurrentPosition(resolve,reject,{enableHighAccuracy:true,maximumAge:5000,timeout:10000});});}
 async function share(){if(!sharing||gpsBusy)return;gpsBusy=true;const target={...sharing};try{const p=await currentPosition();if(!sharing||sharing.key!==target.key)return;await api(tripPath(target)+'/location','PUT',{latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy:p.coords.accuracy,capturedAt:new Date(p.timestamp).toISOString(),sequence:++sequence});status('Driver location shared for the active trip.');}catch(e){sharing=null;status('Location sharing stopped: '+e.message);}finally{gpsBusy=false;}}
 function overview(target,t){target.replaceChildren(node('p',t.status+(t.active?' · active trip':'')));if(!t.location)target.append(node('p','Driver location has not been shared.'));else target.append(node('p',(t.location.stale?'Last known location — stale':'Recent driver location')+' · accuracy '+Math.round(t.location.accuracy)+' m · '+new Date(t.location.capturedAt).toLocaleTimeString()));if(t.eta)target.append(node('p','Road ETA '+Math.ceil(t.eta.durationSeconds/60)+' minutes · '+(t.eta.distanceMetres/1000).toFixed(1)+' km · '+new Date(t.eta.calculatedAt).toLocaleTimeString()));else target.append(node('p',t.mapsConnected?'ETA requires navigation points and fresh GPS.':'Road ETA provider is not configured.'));
 const points=[t.route?.pickup,t.route?.destination,t.location].filter(Boolean);if(points.length>=2){const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 360 180');svg.setAttribute('role','img');svg.setAttribute('aria-label','Pickup, destination and driver coordinate overview');svg.style.width='100%';svg.style.maxWidth='500px';const xs=points.map(p=>p.longitude),ys=points.map(p=>p.latitude),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys);const x=p=>25+(p.longitude-minX)/Math.max(maxX-minX,0.001)*300,y=p=>150-(p.latitude-minY)/Math.max(maxY-minY,0.001)*120;for(const [p,label,color]of [[t.route?.pickup,'Pickup','#245c37'],[t.route?.destination,'Destination','#8c4e1f'],[t.location,'Driver','#225ec4']])if(p){const dot=document.createElementNS(ns,'circle');dot.setAttribute('cx',x(p));dot.setAttribute('cy',y(p));dot.setAttribute('r','6');dot.setAttribute('fill',color);const text=document.createElementNS(ns,'text');text.setAttribute('x',Math.min(290,x(p)+8));text.setAttribute('y',y(p)-9);text.setAttribute('font-size','12');text.textContent=label;svg.append(dot,text);}target.append(svg,node('p','Coordinate overview. Open the map below for street navigation.'));}
 if(t.route){const dest=t.inProgress?t.route.destination:t.route.pickup;let url='https://www.google.com/maps/dir/?api=1&destination='+encodeURIComponent(dest.latitude+','+dest.longitude)+'&travelmode=driving';if(t.location)url+='&origin='+encodeURIComponent(t.location.latitude+','+t.location.longitude);link(target,'Open map navigation',url);}}
 function tripCard(t,user){const card=node('article',null,'app-card');card.dataset.liveTrip=t.kind+':'+t.id;card.append(node('h3',t.label),node('p',t.id));const live=node('div');live.dataset.liveStatus='true';overview(live,t);card.append(live);if(['customer','admin'].includes(user.role)){const f=form('Save navigation points',d=>api(tripPath(t)+'/route','PUT',{version:t.route?.version||0,pickup:{latitude:Number(d.pickupLat),longitude:Number(d.pickupLng)},destination:{latitude:Number(d.destLat),longitude:Number(d.destLng)},destinationLabel:d.destinationLabel,reason:d.reason,shareWithDriver:d.shareWithDriver==='on'}));const coordinates=node('details');coordinates.append(node('summary','Enter or review map coordinates'));f.append(coordinates);for(const [name,label,value]of [['pickupLat','Pickup latitude',t.route?.pickup.latitude],['pickupLng','Pickup longitude',t.route?.pickup.longitude],['destLat','Destination latitude',t.route?.destination.latitude],['destLng','Destination longitude',t.route?.destination.longitude]])field(coordinates,label,name,'number',value??'');field(f,'Pickup street address','pickupAddress').required=false;field(f,'Destination street address','destinationLabel','text',t.route?.destinationLabel||'');field(f,'Navigation instructions / change reason','reason','text',t.route?.reason||'Customer confirmed navigation points');const results=node('div');for(const [which,label,name]of [['pickup','Find pickup address','pickupAddress'],['dest','Find destination address','destinationLabel']])f.append(button(label,async()=>{const r=await api('/operations/geocode','POST',{address:f.elements[name].value});results.replaceChildren(node('p','Choose the correct address:'));for(const p of r.results)results.append(button(p.address,()=>{f.elements[which+'Lat'].value=p.latitude;f.elements[which+'Lng'].value=p.longitude;f.elements[name].value=p.address;results.replaceChildren(node('p','Selected: '+p.address));}));}));f.append(results);check(f,'Share these navigation points with my assigned driver','shareWithDriver');const locate=button('Use my location as pickup',async()=>{const p=await currentPosition();f.elements.pickupLat.value=p.coords.latitude;f.elements.pickupLng.value=p.coords.longitude;f.elements.pickupAddress.value='Current device location';});f.append(locate);card.append(f);}
 if(t.active){card.append(button('Refresh road ETA',async()=>{const next=await api(tripPath(t)+'/eta','POST',{});overview(live,next);}));if(user.role==='driver'&&user.id===t.driverId){card.append(button('Start sharing my GPS',async()=>{sharing={...t,key:t.kind+':'+t.id};await share();}),button('Stop sharing my GPS',async()=>{sharing=null;await api(tripPath(t)+'/location','DELETE',{});overview(live,await api(tripPath(t)));}));if(t.kind==='booking'){const to={ASSIGNED:'DRIVER_EN_ROUTE',DRIVER_EN_ROUTE:'ARRIVED',ARRIVED:'TRIP_STARTED'}[t.status];if(to)card.append(button({DRIVER_EN_ROUTE:'Report viewing driver en route',ARRIVED:'Report viewing driver arrival',TRIP_STARTED:'Start viewing transport'}[to],async()=>{await api(tripPath(t)+'/progress','POST',{to});await refresh();}));}}}return card;}
 function printReceipt(r){const w=window.open('','_blank');if(!w)throw new Error('Allow a print window to download your receipt');w.opener=null;w.document.title=r.receiptNumber;const h=w.document.createElement('h1');h.textContent=r.receiptNumber;w.document.body.append(h);for(const line of [r.snapshot.label,'KES '+r.amount,'Payment reference: '+r.reference,'Payment status: '+r.paymentStatus,'Created: '+r.created_at]){const p=w.document.createElement('p');p.textContent=line;w.document.body.append(p);}for(const f of r.fiscal.filter(x=>x.status==='ACCEPTED')){const p=w.document.createElement('p');p.textContent=f.kind+': '+f.provider_result.invoiceNumber+' · control '+f.provider_result.controlCode+' · gross '+(f.snapshot.grossMinor/100).toFixed(2)+' · tax '+(f.snapshot.taxMinor/100).toFixed(2);w.document.body.append(p);}w.print();}
 async function update(user){const run=++generation;root.hidden=!user;if(!user){sharing=null;root.replaceChildren();openSections.clear();return;}if(root.querySelector(':scope > details'))openSections=new Set(Array.from(root.querySelectorAll(':scope > details[open]')).map(e=>e.querySelector('summary').textContent));root.replaceChildren(node('p','Loading operations…'));const customerOrAdmin=['customer','admin'].includes(user.role),canTrack=['customer','driver','admin'].includes(user.role);const [cap,prefs,collections,receipts,trips,queue,policy,refunds,events,reconciliations]=await Promise.all([api('/operations/capabilities'),api('/operations/communications'),customerOrAdmin?api('/operations/collections'):Promise.resolve({collections:[],payable:[]}),customerOrAdmin?api('/operations/receipts'):Promise.resolve({receipts:[]}),canTrack?api('/operations/trips'):Promise.resolve({trips:[]}),user.role==='admin'?api('/operations/jobs'):Promise.resolve({jobs:[]}),user.role==='admin'?api('/operations/fiscal-policy'):Promise.resolve(null),user.role==='admin'?api('/operations/refunds'):Promise.resolve({requests:[],pending:[]}),user.role==='admin'?api('/operations/payment-events'):Promise.resolve({events:[]}),user.role==='admin'?api('/operations/reconciliations'):Promise.resolve({records:[]})]);if(run!==generation)return;root.replaceChildren(node('h2','Payments, trip tracking & receipts'));root.append(node('p',`Provider connections: payments ${cap.payments?'configured':'not configured'} · messaging ${cap.messaging?'configured':'not configured'} · road ETA ${cap.maps?'configured':'not configured'} · fiscal ${cap.fiscal?'configured':'not configured'}.`));
 const messages=section('Notification preferences');messages.append(node('p',prefs.verified_at?'Contact verified for '+prefs.channel:'Contact verification required before booking alerts'));const pf=form('Save notification preference',d=>api('/operations/communications','PUT',{channel:d.channel,destination:d.destination,consent:d.consent==='on'}));select(pf,'Channel','channel',[['sms','SMS'],['whatsapp','WhatsApp']],prefs.channel);field(pf,'International phone number','destination','tel',prefs.destination).required=false;check(pf,'I consent to booking updates and a verification message','consent');if(prefs.consent)pf.elements.consent.checked=true;messages.append(pf);const vf=form('Verify notification contact',d=>api('/operations/communications/verify','POST',d));field(vf,'Received verification code','code');messages.append(vf);
 if(user.role==='customer'){const payments=section('Pay for confirmed services');for(const p of collections.payable){const f=form('Request M-Pesa payment',d=>api('/operations/collections','POST',{kind:p.kind,targetId:p.targetId,phone:d.phone,idempotencyKey:crypto.randomUUID()}));f.append(node('p',p.kind+' · '+p.targetId+' · KES '+p.amount));field(f,'M-Pesa phone (+254...)','phone','tel');payments.append(f);}}
 if(customerOrAdmin){const statusPanel=section('Collection status and recovery');for(const c of collections.collections){const row=node('article',null,'app-card');row.append(node('p',c.kind+' · '+c.target_id+' · '+c.status+' · KES '+c.amount));if(user.role==='admin'&&c.status==='REVIEW'&&c.reference){const f=form('Record refund of unapplied funds',d=>api('/operations/collections/'+c.id+'/refund','POST',{amount:c.amount,reference:d.reference}));field(f,'Actual external refund reference','reference');row.append(f);}statusPanel.append(row);}for(const e of events.events.filter(x=>x.status==='REVIEW'))statusPanel.append(node('p',e.collection_id+' · '+e.error),button('Reapply verified collection '+e.id,async()=>{await api('/operations/payment-events/'+e.id+'/retry','POST',{});await refresh();}));}
 if(canTrack){const panel=section('Live transport');panel.open=trips.trips.some(t=>t.active);panel.append(node('p','GPS sharing runs only while this page is open and you enable it. Last-known points are marked stale; off-trip tracking is blocked. Navigation points guide the driver and do not change the agreed fare or itinerary.'));for(const t of trips.trips)panel.append(tripCard(t,user));}
 if(customerOrAdmin){const panel=section('Payment receipts');for(const r of receipts.receipts){const card=node('article',null,'app-card');card.dataset.receiptId=r.id;card.append(node('h3',r.receiptNumber),node('p','KES '+r.amount+' · '+r.paymentStatus),node('p',r.snapshot.label),button('Print / save receipt',()=>printReceipt(r)));for(const f of r.fiscal){card.append(node('p','Fiscal '+f.kind+' · '+f.status));if(f.provider_result){card.append(node('p','Invoice '+f.provider_result.invoiceNumber+' · control '+f.provider_result.controlCode));if(f.provider_result.verificationUrl)link(card,'Verify fiscal record',f.provider_result.verificationUrl);}}if(user.role==='admin'){if(!r.fiscal.some(x=>x.kind==='invoice'))card.append(button('Submit fiscal invoice',async()=>{await api('/operations/receipts/'+r.id+'/fiscal','POST',{kind:'invoice'});await refresh();}));if(r.paymentStatus==='refunded'&&!r.fiscal.some(x=>x.kind==='credit'))card.append(button('Submit fiscal credit note',async()=>{await api('/operations/receipts/'+r.id+'/fiscal','POST',{kind:'credit'});await refresh();}));}panel.append(card);}}
 if(user.role==='admin'){const ledgerPanel=section('Reconcile received and refunded funds');for(const record of reconciliations.records){const row=node('article',null,'app-card');row.append(node('p',record.reference+' · '+record.direction+' · KES '+record.expected_amount+' · '+record.status));if(record.status==='PENDING'){const f=form('Reconcile financial record',d=>api('/operations/reconciliations/'+record.ledger_event_id,'POST',{observedAmount:Number(d.observedAmount),evidenceRef:d.evidenceRef}));field(f,'Observed statement amount KES','observedAmount','number');field(f,'Statement / provider evidence reference','evidenceRef');row.append(f);}ledgerPanel.append(row);}const panel=section('Finance and provider operations');const f=form('Publish reviewed fiscal policy',d=>api('/operations/fiscal-policy','POST',{...d,taxBasisPoints:Number(d.taxBasisPoints),taxInclusive:d.taxInclusive==='on'}));for(const [name,label]of [['supplierName','Registered supplier name'],['supplierPin','Supplier tax PIN'],['supplierAddress','Supplier address'],['taxCategory','Provider tax category'],['evidence','Tax treatment review evidence']])field(f,label,name,'text',policy?.[name]||'');field(f,'Inclusive tax rate in basis points (100 = 1%)','taxBasisPoints','number',policy?.taxBasisPoints??'');check(f,'Quoted prices include the reviewed tax; no extra customer charge','taxInclusive');panel.append(f);for(const r of refunds.pending){const f=form('Submit external refund',d=>api('/operations/refunds/'+r.kind+'/'+r.targetId,'POST',d));f.append(node('p',r.kind+' · '+r.targetId+' · KES '+r.amount));field(f,'Refund reason','reason');panel.append(f);}for(const r of refunds.requests){panel.append(node('p','Refund '+r.target_id+' · '+r.status));if(r.status==='REVIEW'){const retry=form('Reapply settled refund',d=>api('/operations/refunds/'+r.id+'/retry','POST',d));field(retry,'Recovery review reason','reason');panel.append(retry);}}for(const j of queue.jobs){panel.append(node('p',j.kind+' · '+j.status+' · '+j.id));if(['REVIEW','PROCESSING'].includes(j.status)){const f=form('Reconcile provider delivery',d=>api('/operations/jobs/'+j.id+'/reconcile','POST',d));field(f,'Review reason','reason');panel.append(f);}}}
 for(const panel of root.querySelectorAll(':scope > details'))if(openSections.has(panel.querySelector('summary').textContent))panel.open=true;root.dataset.renderVersion=String(run);
 }
 setInterval(()=>{void share();},10000);
 setInterval(async()=>{if(pollBusy||!getUser()||root.hidden||document.hidden)return;pollBusy=true;try{for(const card of root.querySelectorAll('[data-live-trip]')){const [kind,id]=card.dataset.liveTrip.split(':');try{const t=await api('/operations/trips/'+kind+'/'+id);overview(card.querySelector('[data-live-status]'),t);if(sharing?.key===card.dataset.liveTrip&&!t.active)sharing=null;}catch{}}}finally{pollBusy=false;}},15000);
 window.addEventListener('pagehide',()=>{sharing=null;});
 window.R2VOperations={refresh:update};
})();
