(() => {
  'use strict';
  const {api,node,button,perform,status,refresh,getUser}=window.R2V;
  const $=id=>document.getElementById(id);
  let dashboard=null;
  function field(form,label,name,type='text',value=''){
    const wrap=node('label',label),input=node('input');input.name=name;input.type=type;input.value=value;wrap.append(input);form.append(wrap);return input;
  }
  function select(form,label,name,values,value){const wrap=node('label',label),input=node('select');input.name=name;for(const [v,t] of values){const o=node('option',t);o.value=v;input.append(o);}if(value)input.value=value;wrap.append(input);form.append(wrap);return input;}
  function form(action,label){const f=node('form'),submit=node('button',label);submit.type='submit';f.addEventListener('submit',e=>{e.preventDefault();perform(async()=>{await action(Object.fromEntries(new FormData(f)));await refresh();},submit);});f.append(submit);return f;}
  function checkLabel(c){return `${c.kind}: ${c.status}${c.expires_at?' · valid until '+new Date(c.expires_at).toLocaleDateString():''}${c.reason?' · '+c.reason:''}`;}
  function submission(kind,targetId){const docs=(dashboard?.documents||[]).filter(d=>d.kind===kind);const f=form(async d=>{if(kind!=='publication'&&!d.documentId)throw new Error('Upload matching private evidence first');await api('/supply/checks/'+kind+'/'+targetId+'/submit','POST',{documentIds:d.documentId?[d.documentId]:[]});status('Review requested.');},'Submit '+kind+' review');if(kind!=='publication')select(f,'Private evidence','documentId',docs.map(d=>[d.id,d.name]));return f;}
  async function renderSlots(id,target){const slots=(await api('/properties/'+id+'/slots')).slots;target.replaceChildren(...slots.map(s=>{const row=node('div',null,'app-card');row.append(node('p',`${new Date(s.start_at).toLocaleString()} – ${new Date(s.end_at).toLocaleTimeString()} · ${s.occupied?'Requested / accepted':'Open'}`));if(!s.occupied)row.append(button('Remove slot',async()=>{await api('/properties/'+id+'/slots/'+s.id,'DELETE',{});await renderSlots(id,target);}));return row;}));}
  function renderProperties(properties){const target=$('app-listings');target.replaceChildren();for(const p of properties){const card=node('article',null,'app-card');card.dataset.propertyId=p.id;
    card.append(node('h3',p.title),node('p',`KES ${p.price.toLocaleString()} · ${p.transactionType||'rent'} · ${p.approved?'Published':'Draft / requires review'} · ${p.available?'Available':'Unavailable'}`));
    for(const c of p.checks||[])card.append(node('p',checkLabel(c)));
    card.append(button(p.available?'Mark unavailable':'Mark available',async()=>{await api('/listings/'+p.id,'PATCH',{available:!p.available});await refresh();}));
    const edit=node('details'),editTitle=node('summary','Edit property');edit.append(editTitle);const ef=form(async d=>{await api('/listings/'+p.id,'PATCH',{title:d.title,description:d.description,price:Number(d.price),transactionType:d.transactionType,location:{city:d.city},property:{bedrooms:Number(d.bedrooms)}});status('Property updated; documentary and publication reviews must be renewed.');},'Save property edits');field(ef,'Title','title','text',p.title).required=true;field(ef,'Description','description','text',p.description);field(ef,'Price (KES)','price','number',p.price).min='1';field(ef,'City','city','text',p.location.city);field(ef,'Bedrooms','bedrooms','number',p.property.bedrooms).min='0';select(ef,'Transaction','transactionType',[['rent','Rent'],['sale','Sale']],p.transactionType);edit.append(ef);card.append(edit);
    const evidence=node('details');evidence.append(node('summary','Property documents and publication'));for(const kind of ['marketing','ownership','publication'])evidence.append(submission(kind,p.id));card.append(evidence);
    const media=node('details');media.append(node('summary','Photos, video and 360 tour'));for(const m of p.media||[]){const row=node('p'),link=node('a',m.caption||m.kind);link.href=m.url;link.target='_blank';link.rel='noopener noreferrer';row.append(link,button('Remove media',async()=>{await api('/properties/'+p.id+'/media/'+m.id,'DELETE',{});await refresh();}));media.append(row);}const mf=form(async d=>{await api('/properties/'+p.id+'/media','POST',d);status('Media added. Request publication review again.');},'Add media');select(mf,'Media type','kind',[['photo','Photo'],['video','Video'],['tour360','360 tour']]);field(mf,'HTTPS media URL','url','url').required=true;field(mf,'Caption','caption');media.append(mf);card.append(media);
    const availability=node('details');availability.append(node('summary','Availability slots'));const sf=form(async d=>{await api('/properties/'+p.id+'/slots','POST',{startAt:new Date(d.startAt).toISOString(),endAt:new Date(d.endAt).toISOString()});status('Availability published.');},'Add viewing slot');field(sf,'Start (device local time)','startAt','datetime-local').required=true;field(sf,'End (device local time)','endAt','datetime-local').required=true;const slots=node('div');availability.append(sf,button('Load availability',()=>renderSlots(p.id,slots)),slots);card.append(availability);target.append(card);
  }}
  function renderViewings(viewings,target,agent){target.replaceChildren();if(!viewings.length)target.append(node('p','No viewing requests yet.'));for(const v of viewings){const card=node('article',null,'app-card');card.dataset.requestId=v.id;card.append(node('h3',v.listing.title),node('p',`${new Date(v.start_at).toLocaleString()} – ${new Date(v.end_at).toLocaleTimeString()}`),node('p',`Request: ${v.status} · Booking: ${v.booking_status||'Awaiting acceptance'} · Payment: ${v.payment_status||'Not requested'}`),node('p',`Viewing reference: ${v.id}`));
    if(agent&&v.status==='REQUESTED'){
      card.append(button('Accept viewing request',async()=>{await api('/viewing-requests/'+v.id+'/accept','POST',{});status('Viewing accepted. Payment reservation created.');await refresh();}));
      const f=form(d=>api('/viewing-requests/'+v.id+'/decline','POST',d),'Decline viewing request');field(f,'Decline reason','reason').required=true;card.append(f);
    }
    if(agent&&['REQUESTED','ACCEPTED'].includes(v.status)&&!['assigned','completed','cancelled'].includes(v.booking_status)){
      const f=form(d=>api('/viewing-requests/'+v.id+'/reschedule','POST',d),'Reschedule viewing');const slotSelect=select(f,'New availability slot','slotId',[]);card.append(button('Load alternative slots',async()=>{const rows=(await api('/properties/'+v.listing_id+'/slots')).slots.filter(s=>!s.occupied);slotSelect.replaceChildren(...rows.map(s=>{const o=node('option',new Date(s.start_at).toLocaleString());o.value=s.id;return o;}));}),f);
    }
    if(['REQUESTED','ACCEPTED'].includes(v.status)&&!['completed','cancelled'].includes(v.booking_status)){const f=form(d=>api('/viewing-requests/'+v.id+'/cancel','POST',d),'Cancel viewing request');field(f,'Cancellation reason','reason').required=true;card.append(f);}
    if(v.booking_status==='completed'){
      if(v.outcome)card.append(node('p',`Outcome: ${v.outcome.outcome} · ${v.outcome.notes}`));else {const f=form(d=>api('/viewing-requests/'+v.id+'/outcome','POST',d),'Record viewing outcome');select(f,'Outcome','outcome',[['INTERESTED','Interested'],['NOT_INTERESTED','Not interested'],['FOLLOW_UP','Follow up']]);field(f,'Outcome notes','notes');card.append(f);}
      if(!agent){const f=form(d=>api('/viewing-requests/'+v.id+'/review','POST',{rating:Number(d.rating),comment:d.comment}),'Submit agent review');select(f,'Rating','rating',[['5','5'],['4','4'],['3','3'],['2','2'],['1','1']]);field(f,'Review','comment');card.append(f);}
    }
    target.append(card);
  }}
  function renderLeads(leads){$('supply-lead-list').replaceChildren();for(const lead of leads){const card=node('article',null,'app-card');card.append(node('h3',lead.title),node('p',`Stage: ${lead.stage} · ${lead.notes}`));const f=form(d=>api('/agent/leads/'+lead.requestId,'PATCH',d),'Update lead');select(f,'Lead stage','stage',['QUALIFIED','VIEWED','FOLLOW_UP','NEGOTIATING','WON','LOST'].map(v=>[v,v]),lead.stage);field(f,'Follow-up notes / agreement evidence for a won deal','notes','text',lead.notes);card.append(f);
    if(getUser().role==='admin'&&lead.stage==='WON'){const cf=form(d=>api('/admin/commissions/requests/'+lead.requestId,'POST',{amount:Number(d.amount),evidenceRef:d.evidenceRef}),'Record agreed commission');field(cf,'Commission (KES)','amount','number').required=true;field(cf,'Agreed commission evidence reference','evidenceRef').required=true;card.append(cf);}
    $('supply-lead-list').append(card);
  }}
  function renderCommissions(rows){$('supply-commissions').replaceChildren(...rows.map(c=>{const card=node('article',null,'app-card');card.append(node('p',`KES ${c.amount.toLocaleString()} · ${c.status} · ${c.evidence_ref}${c.payment_reference?' · '+c.payment_reference:''}`));if(getUser().role==='admin'&&c.status!=='PAID'){const f=form(d=>api('/admin/commissions/'+c.id,'PATCH',d),'Update commission record');select(f,'Status','status',[['PENDING','Pending payout'],['DISPUTED','Disputed'],['PAID','Paid (verify actual payout first)']]);field(f,'Evidence reference','evidenceRef').required=true;field(f,'Payout transaction reference (paid only)','paymentReference');card.append(f);}return card;}));if(!rows.length)$('supply-commissions').append(node('p','No agreed commission records yet.'));}
  function renderQueue(reviews){$('supply-review-list').replaceChildren();for(const c of reviews){const card=node('article',null,'app-card');card.dataset.checkKind=c.kind;card.dataset.targetId=c.target_id;card.append(node('h3',`${c.kind} · ${c.profile?.legal_name||c.property?.title||c.target_id}`),node('p',checkLabel(c)),node('p',`Revision ${c.revision}`));if(c.profile)card.append(node('p',`${c.profile.agency_name} · Registration ${c.profile.registration_number} · ${c.profile.phone}`));for(const d of c.documents){const a=node('a','Download private evidence: '+d.name);a.href='/api/supply/documents/'+d.id;card.append(a);}
    if(['PENDING','APPROVED'].includes(c.status)){const f=form(async d=>{await api('/admin/supply-reviews/'+c.kind+'/'+c.target_id,'POST',{decision:d.decision,reason:d.reason,revision:c.revision,expiresAt:d.expiresAt?new Date(d.expiresAt).toISOString():undefined});status('Review recorded.');},'Record review decision');const decision=select(f,'Decision','decision',c.status==='PENDING'?[['APPROVED','Approve'],['REJECTED','Reject']]:[['REVOKED','Revoke']]);field(f,'Review rationale','reason').required=true;const expiry=field(f,'Approval expiry (device local time)','expiresAt','datetime-local');const toggleExpiry=()=>{expiry.required=decision.value==='APPROVED';expiry.parentElement.hidden=!expiry.required;};decision.addEventListener('change',toggleExpiry);toggleExpiry();card.append(f);} $('supply-review-list').append(card);
  }}
  async function refreshSupply(user){
    $('supply-agent').hidden=!user||!['agent','admin'].includes(user.role);$('supply-review-panel').hidden=user?.role!=='admin';$('supply-customer').hidden=user?.role!=='customer';if(!user){dashboard=null;return;}
    if(['agent','admin'].includes(user.role)){
      dashboard=await api('/agent/dashboard');renderProperties(dashboard.properties);const profile=dashboard.profile;if(profile){const f=$('supply-agent-profile');for(const [name,key] of Object.entries({legalName:'legal_name',phone:'phone',agencyName:'agency_name',registrationNumber:'registration_number'}))f.elements[name].value=profile[key];}
      $('supply-agent-profile').hidden=user.role==='admin';$('supply-agent-checks').replaceChildren(...dashboard.checks.map(c=>node('p',checkLabel(c))));if(user.role==='agent')for(const kind of ['identity','agency'])$('supply-agent-checks').append(submission(kind,user.id));
      $('supply-documents').replaceChildren(...dashboard.documents.map(d=>{const a=node('a',d.kind+' · '+d.name);a.href='/api/supply/documents/'+d.id;const p=node('p');p.append(a);return p;}));renderViewings(dashboard.viewings,$('supply-agent-viewings'),true);renderLeads(dashboard.leads);renderCommissions(dashboard.commissions);
      $('supply-payment-records').replaceChildren(...dashboard.payments.map(p=>node('p',`Viewing ${p.requestId} · ${p.status}`)));
      $('supply-metrics').textContent=`Properties: ${dashboard.performance.properties} · Published: ${dashboard.performance.published} · Requests: ${dashboard.performance.requests} · Completed: ${dashboard.performance.completed} · Won: ${dashboard.performance.won}`;
      $('supply-reviews').replaceChildren(...dashboard.reviews.map(r=>node('p',`${r.rating}/5 · ${r.comment}`)));
    }
    if(user.role==='admin')renderQueue((await api('/admin/supply-reviews')).reviews);
    if(user.role==='customer'){
      const profile=(await api('/customer/profile')).preferences;for(const [key,val]of Object.entries(profile))if($('supply-preferences').elements[key])$('supply-preferences').elements[key].value=val;
      renderViewings((await api('/viewing-requests')).viewings,$('supply-customer-viewings'),false);
      $('supply-saved').replaceChildren(...(await api('/customer/saved-properties')).properties.map(p=>{const row=node('div',null,'app-card');row.append(node('p',`${p.title} · ${p.currentlyPublished?'Published':'Currently unavailable'}`),button('Remove saved property',async()=>{await api('/customer/saved-properties/'+p.id,'DELETE',{});await refresh();}));return row;}));
    }
  }
  $('supply-agent-profile').addEventListener('submit',e=>{e.preventDefault();perform(async()=>{await api('/agent/profile','PUT',Object.fromEntries(new FormData(e.target)));status('Profile saved. Upload evidence and submit identity and agency reviews.');await refresh();});});
  $('supply-preferences').addEventListener('submit',e=>{e.preventDefault();perform(async()=>{const d=Object.fromEntries(new FormData(e.target));await api('/customer/profile','PUT',{city:d.city,budget:Number(d.budget),bedrooms:Number(d.bedrooms),goal:d.goal});status('Preferences saved.');await refresh();});});
  $('supply-document-form').addEventListener('submit',e=>{e.preventDefault();perform(async()=>{const file=e.target.elements.file.files[0];if(!file||file.size>2097152)throw new Error('Choose a PDF, PNG or JPEG of at most 2 MiB');const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));await api('/supply/documents','POST',{kind:e.target.elements.kind.value,name:file.name,mime:file.type,data:btoa(binary)});status('Private document uploaded. Select it when requesting the matching review.');e.target.reset();await refresh();});});
  window.R2VSupply={refresh:refreshSupply,renderProperties};
})();
