const {randomUUID,createHash}=require('node:crypto');
const {active,assertDriver}=require('./eligibility');
const REQUIRED=['identity','selfie','licence','permit','registration','insurance','inspection'];
const KINDS=['driver','women_driver','women_rider','student'];
const now=()=>new Date().toISOString();
function fail(status,message){throw Object.assign(new Error(message),{status});}
function text(v,label,max=200){if(typeof v!=='string'||!v.trim()||v.length>max)fail(400,label+' is required');return v.trim();}
function expiry(v){if(typeof v!=='string'||!/(Z|[+-]\d\d:\d\d)$/.test(v)||!Number.isFinite(Date.parse(v))||Date.parse(v)<=Date.now())fail(400,'Future expiry with explicit UTC offset required');return new Date(v).toISOString();}
function createOnboardingAuthority({db,audit=()=>{},notify=()=>{}}){
 function tx(fn){db.exec('BEGIN IMMEDIATE');try{const r=fn();db.exec('COMMIT');return r;}catch(e){db.exec('ROLLBACK');throw e;}}
 function role(a,...roles){if(!a)fail(401,'Sign in to continue');if(!roles.includes(a.role))fail(403,'This action is not permitted for this account');}
 function event(a,id,kind,type,data={}){db.prepare('INSERT INTO mobility_review_events VALUES(?,?,?,?,?,?,?)').run(randomUUID(),id,kind,type,a.id,JSON.stringify(data),now());audit(a,'mobility.'+type.toLowerCase(),id,{kind,...data});}
 function profile(a,data){role(a,'driver');const prior=db.prepare('SELECT * FROM driver_profiles WHERE user_id=?').get(a.id);if(data===undefined)return prior?{...prior,payload:JSON.parse(prior.payload)}:{user_id:a.id,payload:{},revision:0,online:0};
 if(data.revision!==(prior?.revision||0))fail(409,'Driver profile changed; refresh');
 const p={legalName:text(data.legalName,'Legal name',100),phone:text(data.phone,'Phone',40),plate:text(data.plate,'Vehicle plate',40).toUpperCase(),make:text(data.make,'Vehicle make',60),model:text(data.model,'Vehicle model',60),licenceNumber:text(data.licenceNumber,'Licence number',80),capacity:data.capacity,gender:data.gender||'undisclosed'};
 if(!Number.isSafeInteger(p.capacity)||p.capacity<1||p.capacity>8||!['female','male','undisclosed'].includes(p.gender))fail(400,'Capacity must be 1–8; invalid gender declaration');
 return tx(()=>{if(db.prepare("SELECT 1 FROM dispatch_assignments WHERE driver_id=? AND status IN ('OFFERED','ACCEPTED','ASSIGNED','DRIVER_EN_ROUTE','ARRIVED','TRIP_STARTED')").get(a.id)||db.prepare("SELECT 1 FROM ride2go_assignments WHERE driver_id=? AND status IN ('OFFERED','ASSIGNED','ARRIVED','IN_PROGRESS')").get(a.id))fail(409,'Complete or cancel active assignments before changing driver or vehicle details');db.prepare('INSERT INTO driver_profiles VALUES(?,?,?,0,?) ON CONFLICT(user_id) DO UPDATE SET payload=excluded.payload,revision=excluded.revision,online=0,updated_at=excluded.updated_at').run(a.id,JSON.stringify(p),(prior?.revision||0)+1,now());db.prepare("UPDATE mobility_checks SET status='DRAFT',revision=revision+1,expires_at=NULL,updated_at=? WHERE subject_id=? AND kind IN ('driver','women_driver')").run(now(),a.id);db.prepare('UPDATE users SET verified=0 WHERE id=?').run(a.id);event(a,a.id,'driver','PROFILE_UPDATED');return profile(a);});
 }
 function document(a,data){role(a,'driver','customer');const allowed=a.role==='driver'?REQUIRED:['identity','selfie','women_eligibility','enrolment'];if(!allowed.includes(data.kind))fail(400,'Invalid document kind for this account');const name=text(data.name,'Document name',160),expires=expiry(data.expiresAt),mime=data.mime;
 if(!['application/pdf','image/png','image/jpeg'].includes(mime)||typeof data.data!=='string'||data.data.length>2796204||!/^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/.test(data.data))fail(400,'Use a PDF/PNG/JPEG up to 2 MiB');const bytes=Buffer.from(data.data,'base64');if(bytes.length<8||bytes.length>2097152)fail(400,'Document size must be 8 bytes–2 MiB');const valid=mime==='application/pdf'?bytes.subarray(0,5).toString()==='%PDF-':mime==='image/png'?bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])):bytes[0]===255&&bytes[1]===216&&bytes[2]===255;if(!valid)fail(400,'Document content does not match MIME type');if(db.prepare('SELECT COUNT(*) n FROM mobility_documents WHERE owner_id=?').get(a.id).n>=100)fail(409,'Document limit reached');return tx(()=>{const id=randomUUID();db.prepare('INSERT INTO mobility_documents VALUES(?,?,?,?,?,?,?,?,?)').run(id,a.id,data.kind,name,mime,bytes,createHash('sha256').update(bytes).digest('hex'),expires,now());event(a,a.id,data.kind,'DOCUMENT_ADDED',{documentId:id});return {id,kind:data.kind,name,mime,expires_at:expires};});
 }
 function readDocument(a,id){role(a,'customer','driver','admin');const doc=db.prepare('SELECT * FROM mobility_documents WHERE id=?').get(id);if(!doc)fail(404,'Document not found');if(a.role!=='admin'&&doc.owner_id!==a.id)fail(403,'Document belongs to another account');audit(a,'mobility.document_read',id);return doc;}
 function submit(a,kind,data){role(a,kind==='driver'||kind==='women_driver'?'driver':'customer');const institution=kind==='student'?text(data.institution,'Institution name',200):null;if(!KINDS.includes(kind))fail(400,'Invalid review kind');if(data.adultConfirmed!==true)fail(400,'Adult pilot eligibility confirmation required');return tx(()=>{const p=kind==='driver'||kind==='women_driver'?profile(a):null;if(p&&!p.revision)fail(409,'Complete driver profile');if(kind==='women_driver'&&(p.payload.gender!=='female'||!active(db,a.id,'driver')))fail(409,'Current driver approval and female declaration required');const ids=data.documentIds;if(!Array.isArray(ids)||!ids.length||ids.length>10||new Set(ids).size!==ids.length)fail(400,'Provide 1–10 distinct evidence IDs');const docs=ids.map(id=>db.prepare('SELECT id,kind,owner_id,expires_at FROM mobility_documents WHERE id=?').get(id));if(docs.some(d=>!d||d.owner_id!==a.id||d.expires_at<=now()))fail(403,'Evidence must be current and belong to this account');const needed=kind==='driver'?REQUIRED:kind==='women_driver'?['identity','selfie']:kind==='student'?['identity','enrolment']:['identity','selfie','women_eligibility'];if(needed.some(k=>!docs.some(d=>d.kind===k))||docs.some(d=>!needed.includes(d.kind)))fail(400,'Required evidence: '+needed.join(', '));const prior=db.prepare('SELECT * FROM mobility_checks WHERE subject_id=? AND kind=?').get(a.id,kind);const revision=(prior?.revision||0)+1;db.prepare("INSERT INTO mobility_checks VALUES(?,?,'PENDING',?,?,?,NULL,NULL,NULL,?) ON CONFLICT(subject_id,kind) DO UPDATE SET status='PENDING',revision=excluded.revision,profile_revision=excluded.profile_revision,evidence=excluded.evidence,reason=NULL,reviewer_id=NULL,expires_at=NULL,updated_at=excluded.updated_at").run(a.id,kind,revision,p?.revision||null,JSON.stringify(ids),now());if(kind==='driver'){db.prepare('UPDATE users SET verified=0 WHERE id=?').run(a.id);db.prepare('UPDATE driver_profiles SET online=0 WHERE user_id=?').run(a.id);}event(a,a.id,kind,'SUBMITTED',{revision,adultConfirmed:true,institution});return db.prepare('SELECT * FROM mobility_checks WHERE subject_id=? AND kind=?').get(a.id,kind);});}
 function review(a,id,kind,data){role(a,'admin');if(!KINDS.includes(kind)||!['APPROVED','REJECTED','REVOKED'].includes(data.decision))fail(400,'Invalid review decision');const reason=text(data.reason,'Review reason',1000);return tx(()=>{const c=db.prepare('SELECT * FROM mobility_checks WHERE subject_id=? AND kind=?').get(id,kind);if(!c)fail(404,'Review submission not found');if(c.revision!==data.revision)fail(409,'Review revision changed');if(data.decision!=='REVOKED'&&c.status!=='PENDING')fail(409,'Only pending submissions can be reviewed');let expires=null;if(data.decision==='APPROVED'){expires=expiry(data.expiresAt);if(data.adultVerified!==true)fail(400,'Reviewer must confirm adult pilot eligibility');if(['women_driver','women_rider'].includes(kind)&&data.womenEligibilityVerified!==true)fail(400,'Explicit Women-Only eligibility verification required');if(kind==='student'&&data.enrolmentVerified!==true)fail(400,'Explicit current enrolment verification required');const docs=JSON.parse(c.evidence).map(docId=>db.prepare('SELECT expires_at FROM mobility_documents WHERE id=?').get(docId));if(docs.some(d=>!d||d.expires_at<expires))fail(400,'Review expiry cannot exceed evidence expiry');if(['driver','women_driver'].includes(kind)){const p=db.prepare('SELECT revision,payload FROM driver_profiles WHERE user_id=?').get(id);if(!p||p.revision!==c.profile_revision)fail(409,'Driver profile changed');if(kind==='women_driver'&&(!active(db,id,'driver')||JSON.parse(p.payload).gender!=='female'))fail(409,'Current female driver approval required');}}
 db.prepare('UPDATE mobility_checks SET status=?,reason=?,reviewer_id=?,expires_at=?,revision=revision+1,updated_at=? WHERE subject_id=? AND kind=?').run(data.decision,reason,a.id,expires,now(),id,kind);if(kind==='driver'){db.prepare('UPDATE users SET verified=? WHERE id=?').run(data.decision==='APPROVED'?1:0,id);if(data.decision!=='APPROVED')db.prepare('UPDATE driver_profiles SET online=0 WHERE user_id=?').run(id);}event(a,id,kind,'REVIEWED',{decision:data.decision,reason,expiresAt:expires,adultVerified:data.adultVerified===true,womenEligibilityVerified:data.womenEligibilityVerified===true,enrolmentVerified:data.enrolmentVerified===true});notify(id,'Mobility '+kind+' review: '+data.decision);return db.prepare('SELECT * FROM mobility_checks WHERE subject_id=? AND kind=?').get(id,kind);});}
 function availability(a,data){role(a,'driver');if(typeof data.online!=='boolean')fail(400,'Online must be boolean');return tx(()=>{if(data.online)assertDriver(db,a.id,'general',1,{requireOnline:false});db.prepare('UPDATE driver_profiles SET online=?,updated_at=? WHERE user_id=?').run(data.online?1:0,now(),a.id);event(a,a.id,'driver','AVAILABILITY_CHANGED',{online:data.online});return dashboard(a);});}
 function dashboard(a){role(a,'driver','customer','admin');if(a.role==='admin')return {reviews:db.prepare('SELECT * FROM mobility_checks ORDER BY updated_at DESC').all().map(c=>({...c,account:db.prepare('SELECT id,name,email,role FROM users WHERE id=?').get(c.subject_id),declaration:JSON.parse(db.prepare("SELECT details FROM mobility_review_events WHERE subject_id=? AND kind=? AND event='SUBMITTED' ORDER BY created_at DESC,rowid DESC LIMIT 1").get(c.subject_id,c.kind)?.details||'{}'),profile:['driver','women_driver'].includes(c.kind)?JSON.parse(db.prepare('SELECT payload FROM driver_profiles WHERE user_id=?').get(c.subject_id)?.payload||'{}'):null,documents:JSON.parse(c.evidence).map(id=>db.prepare('SELECT id,kind,name,mime,sha256,expires_at FROM mobility_documents WHERE id=?').get(id))}))};return {profile:a.role==='driver'?profile(a):null,checks:db.prepare('SELECT * FROM mobility_checks WHERE subject_id=?').all(a.id).map(c=>({...c,currentlyEligible:active(db,a.id,c.kind)})),documents:db.prepare('SELECT id,kind,name,mime,expires_at FROM mobility_documents WHERE owner_id=?').all(a.id),requirements:REQUIRED,events:db.prepare('SELECT kind,event,details,created_at FROM mobility_review_events WHERE subject_id=? ORDER BY created_at DESC LIMIT 100').all(a.id)};}
 return {profile,document,readDocument,submit,review,availability,dashboard};
}
module.exports={createOnboardingAuthority,REQUIRED};
