const {approveDriver}=require('./helpers/mobility.cjs');
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const { createApp } = require('../server/app');
const {approveAgent,publishProperty,createSlot}=require('./helpers/supply.cjs');
(async()=>{
 const app=createApp({dbPath:':memory:',adminEmail:'admin@example.test',adminPassword:'Administrator-Test-Only-42'});
 let browser;
 try {
  await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+app.server.address().port;
  async function call(path,body,cookie,method='POST'){const r=await fetch(base+'/api'+path,{method,headers:{'Content-Type':'application/json',...(cookie?{Cookie:cookie}:{})},body:body?JSON.stringify(body):undefined});assert(r.ok,await r.clone().text());return {data:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};}
  const admin=(await call('/auth/login',{email:'admin@example.test',password:'Administrator-Test-Only-42'})).cookie;
  const customer={email:'customer@example.test',name:'Customer Test',password:'Customer-Test-Only-42',role:'customer'};
  const driver={email:'driver@example.test',name:'Driver Test',password:'Driver-Test-Only-42',role:'driver'};
  await call('/auth/register',customer);const registered=await call('/auth/register',driver);const driverLogin=await call('/auth/login',driver);
  const supplyCall=async(path,method='GET',body,cookie,expected=200)=>{const r=await fetch(base+'/api'+path,{method,headers:{'Content-Type':'application/json',...(cookie?{Cookie:cookie}:{})},body:body?JSON.stringify(body):undefined});const data=await r.json();assert.equal(r.status,expected,JSON.stringify(data));return {data,cookie:r.headers.get('set-cookie')?.split(';')[0]};};
  await approveDriver(supplyCall,{id:registered.data.id,cookie:driverLogin.cookie},admin);
  const agentAccount={email:'agent@example.test',name:'Agent Test',password:'Agent-Test-Only-42',role:'agent'};const agentRegistration=await call('/auth/register',agentAccount);const agent={id:agentRegistration.data.id,cookie:(await call('/auth/login',agentAccount)).cookie};await approveAgent(supplyCall,agent,admin);
  const listing=await call('/listings',{title:'Kilimani 2 bedroom',description:'A Nairobi property for viewing',price:45000,location:{city:'Nairobi'},property:{bedrooms:2},timing:{duration:45}},agent.cookie);
  await publishProperty(supplyCall,listing.data.id,agent.cookie,admin);await createSlot(supplyCall,listing.data.id,agent.cookie,7);
  browser=await chromium.launch({headless:true,executablePath:process.env.R2V_CHROMIUM_EXECUTABLE||undefined,args:['--no-sandbox','--disable-dev-shm-usage']});
  const errors=[];
  async function pageFor(email,password){const context=await browser.newContext();await context.route('https://**/*',r=>r.abort());const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(base);await page.waitForFunction(()=>document.getElementById('app-status').textContent.startsWith('Ready.'));await page.locator('#app-auth-form [name=email]').fill(email);await page.locator('#app-auth-form [name=password]').fill(password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.waitForFunction(()=>!document.getElementById('app-account').hidden);return page;}
  const client=await pageFor(customer.email,customer.password);
  await client.locator('#supply-preferences [name=budget]').fill('50000');await client.getByRole('button',{name:'Save preferences',exact:true}).click();await client.waitForFunction(()=>document.getElementById('app-status').textContent==='Preferences saved.');
  const agentPage=await pageFor(agentAccount.email,agentAccount.password);assert(await agentPage.locator('#supply-agent').isVisible());
  await client.locator('#app-search [name=message]').fill('Find a 2 bedroom property in Nairobi');await client.locator('#app-search [name=availableTime]').fill('1 hour');await client.locator('#app-search button').filter({hasText:/^Search$/}).click();await client.getByRole('button',{name:'Choose property',exact:true}).click();
  await client.locator('#app-booking-form [name=slotId]').selectOption({index:0});await client.getByRole('button',{name:'Request viewing',exact:true}).click();await client.waitForFunction(()=>document.getElementById('supply-customer-viewings').textContent.includes('REQUESTED'));
  await agentPage.evaluate(()=>window.R2V.refresh());await agentPage.getByRole('button',{name:'Accept viewing request',exact:true}).click();await agentPage.waitForFunction(()=>document.getElementById('supply-agent-viewings').textContent.includes('ACCEPTED'));
  await client.getByRole('button',{name:'Refresh status',exact:true}).click();await client.waitForFunction(()=>document.getElementById('app-bookings').textContent.includes('Payment: pending'));
  const operations=await pageFor('admin@example.test','Administrator-Test-Only-42');await operations.getByLabel('Transaction reference').fill('BROWSER_RECEIPT_001');await operations.getByRole('button',{name:'Verify received payment',exact:true}).click();await operations.getByRole('button',{name:'Offer viewing to driver',exact:true}).click();await operations.waitForFunction(()=>document.getElementById('app-status').textContent.includes('Viewing offered to driver.'));const offered=app.db.prepare("SELECT * FROM dispatch_assignments WHERE driver_id=? AND status='OFFERED' ORDER BY created_at DESC LIMIT 1").get(registered.data.id);assert(offered);const driverPage=await pageFor(driver.email,driver.password);await driverPage.getByRole('button',{name:'Accept viewing',exact:true}).click();await driverPage.waitForFunction(()=>document.getElementById('app-bookings').textContent.includes('Status: assigned'));await operations.getByRole('button',{name:'Refresh status',exact:true}).click();await operations.waitForFunction(()=>document.getElementById('app-bookings').textContent.includes('Status: assigned'));
  await driverPage.getByRole('button',{name:'Complete viewing',exact:true}).click();await driverPage.waitForFunction(()=>document.getElementById('app-bookings').textContent.includes('Status: completed'));
  await client.getByRole('button',{name:'Refresh status',exact:true}).click();await client.waitForFunction(()=>document.getElementById('app-bookings').textContent.includes('Status: completed'));
  await client.locator('#supply-customer-viewings').getByRole('button',{name:'Record viewing outcome',exact:true}).click();await client.waitForFunction(()=>document.getElementById('supply-customer-viewings').textContent.includes('Outcome: INTERESTED'));
  await agentPage.evaluate(()=>window.R2V.refresh());assert(await agentPage.locator('#supply-lead-list').textContent().then(s=>s.includes('VIEWED')));
  const propertyCard=agentPage.locator('[data-property-id="'+listing.data.id+'"]');
  await propertyCard.getByText('Photos, video and 360 tour',{exact:true}).click();await propertyCard.locator('[name=url]').fill('https://example.test/property-video');await propertyCard.locator('[name=caption]').fill('Property video');await propertyCard.getByRole('button',{name:'Add media',exact:true}).click();await agentPage.waitForFunction(()=>document.getElementById('app-status').textContent.includes('Media added.'));
  await propertyCard.getByText('Property documents and publication',{exact:true}).click();await propertyCard.getByRole('button',{name:'Submit publication review',exact:true}).click();await agentPage.waitForFunction(()=>document.getElementById('app-status').textContent==='Review requested.');
  await operations.evaluate(()=>window.R2V.refresh());const publication=operations.locator('#supply-review-list [data-check-kind="publication"][data-target-id="'+listing.data.id+'"]');await publication.locator('[name=reason]').fill('Reviewed property video and documentary checks');await publication.locator('[name=expiresAt]').fill('2035-01-01T10:00');await publication.getByRole('button',{name:'Record review decision',exact:true}).click();await operations.waitForFunction(()=>document.getElementById('app-status').textContent==='Review recorded.');assert.equal(app.supply.listPublic().length,1);
  await agentPage.locator('#supply-document-form [name=kind]').selectOption('ownership');await agentPage.locator('#supply-document-form [name=file]').setInputFiles({name:'browser-evidence.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.7\nSynthetic browser evidence fixture.\n%%EOF')});await agentPage.getByRole('button',{name:'Upload private evidence',exact:true}).click();await agentPage.waitForFunction(()=>document.getElementById('supply-documents').textContent.includes('browser-evidence.pdf'));
  // Exercise the complete three-property package through connected role workspaces.
  await client.locator('#journey-profile [name=phone]').fill('+254700000001');await client.locator('#journey-profile [name=pickup]').fill('Nairobi browser pickup');await client.getByRole('button',{name:'Save contact and pickup',exact:true}).click();await client.waitForFunction(()=>document.querySelector('#journey-profile [name=pickup]').value==='Nairobi browser pickup');
  const packageProperties=[listing.data];for(let i=1;i<3;i++){const p=(await call('/listings',{title:'Package property '+i,description:'Browser package property',price:40000,location:{city:'Nairobi'},property:{bedrooms:2}},agent.cookie)).data;await publishProperty(supplyCall,p.id,agent.cookie,admin);packageProperties.push(p);}
  for(let i=0;i<3;i++){const startAt=new Date(Date.now()+8*86400000+i*90*60000).toISOString();await call('/properties/'+packageProperties[i].id+'/slots',{startAt,endAt:new Date(Date.parse(startAt)+45*60000).toISOString()},agent.cookie);}
  for(const p of packageProperties)await client.evaluate(p=>window.R2VJourney.addProperty(p),p);
  await client.locator('#journey-planner [name=returnJourney]').selectOption('yes');await client.getByRole('button',{name:'Request reviewed package quote',exact:true}).click();await client.waitForFunction(()=>document.getElementById('journey-list').textContent.includes('DRAFT'));
  const packageId=app.db.prepare('SELECT id FROM viewing_journeys').get().id;
  await operations.evaluate(()=>window.R2V.refresh());const operationsPackage=operations.locator('[data-journey-id="'+packageId+'"]');for(let i=0;i<2;i++){await operationsPackage.locator('[name=km'+i+']').fill(String(i+2));await operationsPackage.locator('[name=minutes'+i+']').fill('20');}await operationsPackage.locator('[name=evidenceRef]').fill('Synthetic reviewed browser route');await operationsPackage.getByRole('button',{name:'Publish reviewed quote',exact:true}).click();await operations.waitForFunction(()=>document.getElementById('journey-list').textContent.includes('QUOTED'));
  await client.evaluate(()=>window.R2V.refresh());const clientPackage=client.locator('[data-journey-id="'+packageId+'"]');await clientPackage.locator('[name=acceptPolicy]').check();await clientPackage.getByRole('button',{name:'Accept price and request all agents',exact:true}).click();await client.waitForFunction(()=>document.getElementById('journey-list').textContent.includes('PENDING_AGENTS'));
  await agentPage.evaluate(()=>window.R2V.refresh());for(let i=0;i<3;i++){await agentPage.locator('[data-journey-id="'+packageId+'"]').getByRole('button',{name:'Confirm package stop',exact:true}).first().click();await agentPage.waitForFunction(n=>Array.from(document.querySelectorAll('#journey-list button')).filter(b=>b.textContent==='Confirm package stop').length===n,2-i);}
  await operations.evaluate(()=>window.R2V.refresh());await operations.getByLabel('Transaction reference').fill('BROWSER_PACKAGE_PAID');await operations.getByRole('button',{name:'Verify received payment',exact:true}).click();await operations.getByRole('button',{name:'Offer viewing to driver',exact:true}).click();await operations.waitForFunction(()=>document.getElementById('app-status').textContent.includes('Viewing offered'));
  await driverPage.evaluate(()=>window.R2V.refresh());await driverPage.getByRole('button',{name:'Accept viewing',exact:true}).click();await driverPage.getByRole('button',{name:'Start package transport',exact:true}).click();await driverPage.waitForFunction(()=>document.getElementById('journey-list').textContent.includes('IN_PROGRESS'));
  for(let i=0;i<3;i++){await driverPage.getByRole('button',{name:'Complete package stop '+(i+1),exact:true}).click();await driverPage.waitForFunction(i=>!Array.from(document.querySelectorAll('#journey-list button')).some(b=>b.textContent==='Complete package stop '+(i+1)),i);}
  await driverPage.getByRole('button',{name:'Finish package transport and return',exact:true}).click();await driverPage.waitForFunction(()=>document.getElementById('journey-list').textContent.includes('Viewing package · COMPLETED'));
  await client.evaluate(()=>window.R2V.refresh());await clientPackage.getByRole('button',{name:'Record property outcome',exact:true}).first().click();await client.waitForFunction(()=>document.getElementById('journey-list').textContent.includes('Outcome: INTERESTED'));assert.equal(app.db.prepare('SELECT COUNT(*) n FROM dispatch_assignments').get().n,2);
  // Exercise driver resubmission/review and a separate Ride2Go trip through the UI.
  await driverPage.locator('#mobility-driver [name=plate]').fill('BROWSER-002');await driverPage.getByRole('button',{name:'Save driver profile',exact:true}).click();await driverPage.waitForFunction(()=>document.getElementById('mobility-driver').textContent.includes('DRAFT'));
  await driverPage.locator('#mobility-driver [name=file]').setInputFiles({name:'driver-browser-evidence.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.7\nSynthetic driver browser evidence.\n%%EOF')});await driverPage.locator('#mobility-driver [name=expiresAt]').fill('2035-01-01T10:00');await driverPage.getByRole('button',{name:'Upload mobility evidence',exact:true}).click();await driverPage.waitForFunction(()=>document.getElementById('mobility-driver').textContent.includes('driver-browser-evidence.pdf'));
  const driverSubmission=driverPage.locator('#mobility-driver form').filter({has:driverPage.getByRole('button',{name:'Submit driver review',exact:true})});for(const input of await driverSubmission.locator('[name=evidence]').all())await input.check();await driverSubmission.locator('[name=adultConfirmed]').check();await driverSubmission.getByRole('button',{name:'Submit driver review',exact:true}).click();await driverPage.waitForFunction(()=>document.getElementById('mobility-driver').textContent.includes('PENDING'));
  await operations.evaluate(()=>window.R2V.refresh());const driverReview=operations.locator('[data-mobility-subject="'+registered.data.id+'"][data-mobility-kind="driver"]');await driverReview.locator('[name=reason]').fill('Synthetic identity licence vehicle and adult eligibility reviewed');await driverReview.locator('[name=adultVerified]').check();await driverReview.locator('[name=expiresAt]').fill(new Date(Date.now()+60*86400000).toISOString().slice(0,16));await driverReview.getByRole('button',{name:'Record mobility review',exact:true}).click();await operations.waitForFunction(()=>document.getElementById('mobility-reviewer').textContent.includes('APPROVED'));
  await driverPage.evaluate(()=>window.R2V.refresh());await driverPage.getByRole('button',{name:'Go online',exact:true}).click();await driverPage.getByRole('button',{name:'Go offline',exact:true}).waitFor();
  const policyForm=operations.locator('#ride2go-policy form');for(const [name,value]of [['general','350'],['women','750'],['students','450'],['vip','2000'],['perKmKES','7']])await policyForm.locator('[name='+name+']').fill(value);await policyForm.getByRole('button',{name:'Publish Ride2Go pricing policy',exact:true}).click();await operations.waitForFunction(()=>document.getElementById('ride2go-policy').textContent.includes('Current version 1'));
  await client.evaluate(()=>window.R2V.refresh());const requestForm=client.locator('#ride2go-request form');await requestForm.locator('[name=pickup]').fill('Nairobi pickup');await requestForm.locator('[name=destination]').fill('Nairobi destination');await requestForm.locator('[name=phone]').fill('+254700000001');await requestForm.locator('[name=scheduledAt]').fill(new Date(Date.now()+86400000).toISOString().slice(0,16));await requestForm.getByRole('button',{name:'Request Ride2Go quote',exact:true}).click();await client.waitForFunction(()=>document.getElementById('ride2go-trips').textContent.includes('REQUESTED'));
  const rideId=app.db.prepare('SELECT id FROM ride2go_trips').get().id;await operations.evaluate(()=>window.R2V.refresh());const operationsRide=operations.locator('[data-ride-id="'+rideId+'"]');await operationsRide.locator('[name=distanceKm]').fill('5');await operationsRide.locator('[name=minutes]').fill('25');await operationsRide.locator('[name=evidenceRef]').fill('Synthetic browser route review');await operationsRide.getByRole('button',{name:'Publish Ride2Go quote',exact:true}).click();await operations.waitForFunction(()=>document.getElementById('ride2go-trips').textContent.includes('QUOTED'));
  await client.evaluate(()=>window.R2V.refresh());const clientRide=client.locator('[data-ride-id="'+rideId+'"]');await clientRide.locator('[name=acceptPolicy]').check();await clientRide.getByRole('button',{name:'Accept Ride2Go fare',exact:true}).click();await client.waitForFunction(()=>document.getElementById('ride2go-trips').textContent.includes('PAYABLE'));
  await operations.evaluate(()=>window.R2V.refresh());await operationsRide.locator('[name=reference]').fill('BROWSER_RIDE2GO_PAID');await operationsRide.getByRole('button',{name:'Verify Ride2Go payment',exact:true}).click();await operationsRide.getByRole('button',{name:'Offer Ride2Go to driver',exact:true}).click();await operations.waitForFunction(()=>document.getElementById('ride2go-trips').textContent.includes('OFFERED'));
  await driverPage.evaluate(()=>window.R2V.refresh());const driverRide=driverPage.locator('[data-ride-id="'+rideId+'"]');await driverRide.getByRole('button',{name:'Accept Ride2Go',exact:true}).click();await driverRide.getByRole('button',{name:'Confirm Ride2Go arrival',exact:true}).click();await driverRide.locator('[name=pickupCode]').waitFor();assert(!(await driverRide.textContent()).includes('Private pickup code'));
  await client.evaluate(()=>window.R2V.refresh());const code=(await clientRide.textContent()).match(/Private pickup code: (\d{6})/)[1];await driverRide.locator('[name=pickupCode]').fill(code);await driverRide.getByRole('button',{name:'Start Ride2Go trip',exact:true}).click();await driverRide.getByRole('button',{name:'Complete Ride2Go trip',exact:true}).click();await driverPage.waitForFunction(()=>document.getElementById('ride2go-trips').textContent.includes('COMPLETED'));
  await client.setViewportSize({width:390,height:844});assert(await client.locator('#app-workspace').isVisible());assert.equal(await client.evaluate(()=>{const e=document.getElementById('app-workspace');return e.scrollWidth>e.clientWidth;}),false);
  await client.getByRole('button',{name:'View design preview',exact:true}).click();await client.getByRole('button',{name:'Open booking workspace',exact:true}).click();
  await client.getByRole('button',{name:'Voice search',exact:true}).click();assert(await client.locator('#voice-overlay').isVisible());await client.locator('#app-voice-close').click();
  await agentPage.setViewportSize({width:390,height:844});assert.equal(await agentPage.evaluate(()=>{const e=document.getElementById('app-workspace');return e.scrollWidth>e.clientWidth;}),false);
  if(process.env.R2V_SCREENSHOT_DIR){await agentPage.locator('#supply-agent').scrollIntoViewIfNeeded();await agentPage.screenshot({path:process.env.R2V_SCREENSHOT_DIR+'/agent-mobile.png'});await operations.locator('#supply-review-panel').scrollIntoViewIfNeeded();await operations.screenshot({path:process.env.R2V_SCREENSHOT_DIR+'/reviewer.png'});}
  assert.deepEqual(errors,[]);console.log('Browser single-viewing, package, onboarding and Ride2Go journeys passed: profile → search → choose slot → request → agent accept → verify → offer → driver accept → complete → outcome/lead; customer and agent mobile layouts and voice controls passed.');
 } finally {if(browser)await browser.close();await app.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
