const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const { createApp } = require('../server/app');
const {approveAgent,publishProperty,createSlot}=require('./helpers/supply.cjs');
(async()=>{
 const app=createApp({dbPath:':memory:',adminEmail:'admin@example.test',adminPassword:'Administrator-Test-Only-42'});
 let browser;
 try {
  await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+app.server.address().port;
  async function call(path,body,cookie,method='POST'){const r=await fetch(base+'/api'+path,{method,headers:{'Content-Type':'application/json',...(cookie?{Cookie:cookie}:{})},body:body?JSON.stringify(body):undefined});assert(r.ok,await r.clone().text());return {data:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};}
  const admin=(await call('/auth/login',{email:'admin@example.test',password:'Administrator-Test-Only-42'})).cookie;
  const customer={email:'customer@example.test',name:'Customer Test',password:'Customer-Test-Only-42',role:'customer'};
  const driver={email:'driver@example.test',name:'Driver Test',password:'Driver-Test-Only-42',role:'driver'};
  await call('/auth/register',customer);const registered=await call('/auth/register',driver);await call('/admin/users/'+registered.data.id+'/approve',{},admin);
  const supplyCall=async(path,method='GET',body,cookie,expected=200)=>{const r=await fetch(base+'/api'+path,{method,headers:{'Content-Type':'application/json',...(cookie?{Cookie:cookie}:{})},body:body?JSON.stringify(body):undefined});const data=await r.json();assert.equal(r.status,expected,JSON.stringify(data));return {data,cookie:r.headers.get('set-cookie')?.split(';')[0]};};
  const agentAccount={email:'agent@example.test',name:'Agent Test',password:'Agent-Test-Only-42',role:'agent'};const agentRegistration=await call('/auth/register',agentAccount);const agent={id:agentRegistration.data.id,cookie:(await call('/auth/login',agentAccount)).cookie};await approveAgent(supplyCall,agent,admin);
  const listing=await call('/listings',{title:'Kilimani 2 bedroom',description:'A Nairobi property for viewing',price:45000,location:{city:'Nairobi'},property:{bedrooms:2},timing:{duration:45}},agent.cookie);
  await publishProperty(supplyCall,listing.data.id,agent.cookie,admin);await createSlot(supplyCall,listing.data.id,agent.cookie,365);
  browser=await chromium.launch({headless:true,executablePath:process.env.R2V_CHROMIUM_EXECUTABLE||undefined,args:['--no-sandbox','--disable-dev-shm-usage']});
  const errors=[];
  async function pageFor(email,password){const context=await browser.newContext();await context.route('https://**/*',r=>r.abort());const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(base);await page.waitForFunction(()=>document.getElementById('app-status').textContent.startsWith('Ready.'));await page.locator('#app-auth-form [name=email]').fill(email);await page.locator('#app-auth-form [name=password]').fill(password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.waitForFunction(()=>!document.getElementById('app-account').hidden);return page;}
  const client=await pageFor(customer.email,customer.password);
  await client.locator('#supply-preferences [name=budget]').fill('50000');await client.getByRole('button',{name:'Save preferences',exact:true}).click();await client.waitForFunction(()=>document.getElementById('app-status').textContent==='Preferences saved.');
  const agentPage=await pageFor(agentAccount.email,agentAccount.password);assert(await agentPage.locator('#supply-agent').isVisible());
  await client.locator('#app-search [name=message]').fill('Find a 2 bedroom property in Nairobi');await client.locator('#app-search [name=availableTime]').fill('1 hour');await client.locator('#app-search button').filter({hasText:/^Search$/}).click();await client.getByRole('button',{name:'Choose property',exact:true}).click();
  await client.locator('#app-booking-form [name=slotId]').selectOption({index:0});await client.getByRole('button',{name:'Request viewing',exact:true}).click();await client.waitForFunction(()=>document.getElementById('supply-customer-viewings').textContent.includes('REQUESTED'));
  await agentPage.evaluate(()=>window.R2V.refresh());await agentPage.getByRole('button',{name:'Accept viewing request',exact:true}).click();await agentPage.waitForFunction(()=>document.getElementById('supply-agent-viewings').textContent.includes('ACCEPTED'));
  await client.getByRole('button',{name:'Refresh status',exact:true}).click();await client.waitForFunction(()=>document.getElementById('app-bookings').textContent.includes('Payment: pending'));
  const operations=await pageFor('admin@example.test','Administrator-Test-Only-42');await operations.getByLabel('Transaction reference').fill('BROWSER_RECEIPT_001');await operations.getByRole('button',{name:'Verify received payment',exact:true}).click();await operations.getByRole('button',{name:'Offer viewing to driver',exact:true}).click();await operations.waitForFunction(()=>document.getElementById('app-status').textContent.includes('Viewing offered to driver.'));const offered=app.db.prepare("SELECT * FROM dispatch_assignments WHERE driver_id=? AND status='OFFERED' ORDER BY created_at DESC LIMIT 1").get(registered.data.id);assert(offered);const driverPage=await pageFor(driver.email,driver.password);await driverPage.getByRole('button',{name:'Accept viewing',exact:true}).click();await driverPage.waitForFunction(()=>document.getElementById('app-bookings').textContent.includes('Status: assigned'));await operations.getByRole('button',{name:'Refresh status',exact:true}).click();await operations.waitForFunction(()=>document.getElementById('app-bookings').textContent.includes('Status: assigned'));
  await driverPage.getByRole('button',{name:'Complete viewing',exact:true}).click();await driverPage.waitForFunction(()=>document.getElementById('app-bookings').textContent.includes('Status: completed'));
  await client.getByRole('button',{name:'Refresh status',exact:true}).click();await client.waitForFunction(()=>document.getElementById('app-bookings').textContent.includes('Status: completed'));
  await client.locator('#supply-customer-viewings').getByRole('button',{name:'Record viewing outcome',exact:true}).click();await client.waitForFunction(()=>document.getElementById('supply-customer-viewings').textContent.includes('Outcome: INTERESTED'));
  await agentPage.evaluate(()=>window.R2V.refresh());assert(await agentPage.locator('#supply-lead-list').textContent().then(s=>s.includes('VIEWED')));
  const propertyCard=agentPage.locator('[data-property-id="'+listing.data.id+'"]');
  await propertyCard.getByText('Photos, video and 360 tour',{exact:true}).click();await propertyCard.locator('[name=url]').fill('https://example.test/property-video');await propertyCard.locator('[name=caption]').fill('Property video');await propertyCard.getByRole('button',{name:'Add media',exact:true}).click();await agentPage.waitForFunction(()=>document.getElementById('app-status').textContent.includes('Media added.'));
  await propertyCard.getByText('Property documents and publication',{exact:true}).click();await propertyCard.getByRole('button',{name:'Submit publication review',exact:true}).click();await agentPage.waitForFunction(()=>document.getElementById('app-status').textContent==='Review requested.');
  await operations.evaluate(()=>window.R2V.refresh());const publication=operations.locator('#supply-review-list [data-check-kind="publication"][data-target-id="'+listing.data.id+'"]');await publication.locator('[name=reason]').fill('Reviewed property video and documentary checks');await publication.locator('[name=expiresAt]').fill('2035-01-01T10:00');await publication.getByRole('button',{name:'Record review decision',exact:true}).click();await operations.waitForFunction(()=>document.getElementById('app-status').textContent==='Review recorded.');assert.equal(app.supply.listPublic().length,1);
  await agentPage.locator('#supply-document-form [name=kind]').selectOption('ownership');await agentPage.locator('#supply-document-form [name=file]').setInputFiles({name:'browser-evidence.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.7\nSynthetic browser evidence fixture.\n%%EOF')});await agentPage.getByRole('button',{name:'Upload private evidence',exact:true}).click();await agentPage.waitForFunction(()=>document.getElementById('supply-documents').textContent.includes('browser-evidence.pdf'));
  await client.setViewportSize({width:390,height:844});assert(await client.locator('#app-workspace').isVisible());assert.equal(await client.evaluate(()=>{const e=document.getElementById('app-workspace');return e.scrollWidth>e.clientWidth;}),false);
  await client.getByRole('button',{name:'View design preview',exact:true}).click();await client.getByRole('button',{name:'Open booking workspace',exact:true}).click();
  await client.getByRole('button',{name:'Voice search',exact:true}).click();assert(await client.locator('#voice-overlay').isVisible());await client.locator('#app-voice-close').click();
  await agentPage.setViewportSize({width:390,height:844});assert.equal(await agentPage.evaluate(()=>{const e=document.getElementById('app-workspace');return e.scrollWidth>e.clientWidth;}),false);
  if(process.env.R2V_SCREENSHOT_DIR){await agentPage.locator('#supply-agent').scrollIntoViewIfNeeded();await agentPage.screenshot({path:process.env.R2V_SCREENSHOT_DIR+'/agent-mobile.png'});await operations.locator('#supply-review-panel').scrollIntoViewIfNeeded();await operations.screenshot({path:process.env.R2V_SCREENSHOT_DIR+'/reviewer.png'});}
  assert.deepEqual(errors,[]);console.log('Browser journey passed: profile → search → choose slot → request → agent accept → verify → offer → driver accept → complete → outcome/lead; customer and agent mobile layouts and voice controls passed.');
 } finally {if(browser)await browser.close();await app.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
