const test=require('node:test');const assert=require('node:assert/strict');const {DatabaseSync}=require('node:sqlite');const {mkdtempSync,rmSync}=require('node:fs');const {join}=require('node:path');const {tmpdir}=require('node:os');const {openStore}=require('../server/store');const {CURRENT_SCHEMA_VERSION,runMigrations,migrations,checksum}=require('../server/migrations');
test('openStore records current schema version on a fresh database',()=>{const db=openStore(':memory:');const rows=db.prepare('SELECT version,name FROM schema_migrations').all();assert.equal(rows.length,CURRENT_SCHEMA_VERSION);assert.equal(rows.at(-1).version,CURRENT_SCHEMA_VERSION);assert.ok(db.prepare('SELECT checksum FROM schema_migrations WHERE version=1').get().checksum);db.close();});
test('legacy commerce price confirmation schema upgrades without losing order or price evidence',()=>{const dir=mkdtempSync(join(tmpdir(),'r2v-migrate-')),file=join(dir,'legacy.sqlite');const legacy=new DatabaseSync(file);legacy.exec(`PRAGMA foreign_keys=ON;
CREATE TABLE commerce_orders(id TEXT PRIMARY KEY,customer_id TEXT NOT NULL,merchant_id TEXT NOT NULL,basket TEXT NOT NULL,total INTEGER NOT NULL,currency TEXT NOT NULL,status TEXT NOT NULL,idempotency_key TEXT NOT NULL UNIQUE,version INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE commerce_price_confirmations(id TEXT PRIMARY KEY,order_id TEXT UNIQUE NOT NULL REFERENCES commerce_orders(id),merchant_id TEXT NOT NULL,amount INTEGER NOT NULL,currency TEXT NOT NULL,inventory_versions TEXT NOT NULL,confirmed_by TEXT,created_at TEXT NOT NULL);
INSERT INTO commerce_orders VALUES('o1','c1','m1','[{"sku":"x","qty":1}]',100,'KES','PRICE_CONFIRMED','legacy-o1',1,'2026-09-01T00:00:00.000Z','2026-09-01T00:00:00.000Z');
INSERT INTO commerce_price_confirmations VALUES('pc1','o1','m1',100,'KES','[["x",1]]','m1','2026-09-01T00:00:00.000Z');`);legacy.close();const db=openStore(file);const pc=db.prepare("SELECT * FROM commerce_price_confirmations WHERE id='pc1'").get();assert.equal(pc.order_id,'o1');assert.equal(pc.amount,100);assert.equal(pc.status,'ACTIVE');assert.equal(pc.supersedes_id,null);assert.equal(db.prepare("SELECT total FROM commerce_orders WHERE id='o1'").get().total,100);assert.equal(db.prepare('SELECT MAX(version) AS version FROM schema_migrations').get().version,CURRENT_SCHEMA_VERSION);const cols=db.prepare("PRAGMA table_info('commerce_price_confirmations')").all().map(x=>x.name);assert.ok(cols.includes('customer_acknowledged_at'));db.close();rmSync(dir,{recursive:true,force:true});});
test('migration is idempotent across repeated startup',()=>{const dir=mkdtempSync(join(tmpdir(),'r2v-migrate-repeat-')),file=join(dir,'db.sqlite');let db=openStore(file);db.close();db=openStore(file);assert.equal(db.prepare('SELECT COUNT(*) AS n FROM schema_migrations').get().n,CURRENT_SCHEMA_VERSION);db.close();rmSync(dir,{recursive:true,force:true});});
test('startup fails closed when database schema version is newer than application',()=>{const dir=mkdtempSync(join(tmpdir(),'r2v-migrate-newer-')),file=join(dir,'db.sqlite');const raw=new DatabaseSync(file);raw.exec("CREATE TABLE schema_migrations(version INTEGER PRIMARY KEY,name TEXT NOT NULL,applied_at TEXT NOT NULL); INSERT INTO schema_migrations VALUES(999,'future','2026-10-01T00:00:00.000Z')");raw.close();assert.throws(()=>openStore(file),e=>e.code==='DATABASE_SCHEMA_NEWER_THAN_APPLICATION');rmSync(dir,{recursive:true,force:true});});

test('migration checksum tampering fails closed',()=>{const dir=mkdtempSync(join(tmpdir(),'r2v-migrate-integrity-')),file=join(dir,'db.sqlite');let db=openStore(file);db.prepare("UPDATE schema_migrations SET checksum='tampered' WHERE version=1").run();db.close();assert.throws(()=>openStore(file),e=>e.code==='DATABASE_MIGRATION_CHECKSUM_MISMATCH');rmSync(dir,{recursive:true,force:true});});
test('pre-check failure does not partially apply a migration',()=>{const dir=mkdtempSync(join(tmpdir(),'r2v-migrate-identity-')),file=join(dir,'db.sqlite');const raw=new DatabaseSync(file);raw.exec("CREATE TABLE schema_migrations(version INTEGER PRIMARY KEY,name TEXT NOT NULL,applied_at TEXT NOT NULL,checksum TEXT); INSERT INTO schema_migrations VALUES(1,'wrong-identity','2026-10-01T00:00:00.000Z',NULL)");raw.close();assert.throws(()=>openStore(file),e=>e.code==='DATABASE_MIGRATION_IDENTITY_MISMATCH');const check=new DatabaseSync(file);assert.equal(check.prepare('SELECT COUNT(*) AS n FROM schema_migrations').get().n,1);assert.equal(check.prepare("SELECT 1 FROM pragma_table_info('schema_migrations') WHERE name='checksum'").get()[1],1);check.close();rmSync(dir,{recursive:true,force:true});});

test('callback lease generation exists on fresh schema and migration registry',()=>{const db=openStore(':memory:');const cols=db.prepare("PRAGMA table_info('provider_callback_inbox')").all().map(x=>x.name);assert.ok(cols.includes('lease_version'));assert.equal(db.prepare('SELECT MAX(version) AS version FROM schema_migrations').get().version,CURRENT_SCHEMA_VERSION);assert.equal(db.prepare("SELECT name FROM schema_migrations WHERE version=8").get().name,'provider-callback-lease-generation');db.close();});


test('support recovery schema is migration-versioned and available before callback recovery',()=>{const db=openStore(':memory:');for(const table of ['support_cases','support_case_events','support_recovery_actions'])assert.equal(db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name=?").get(table).name,table);assert.equal(db.prepare("SELECT name FROM schema_migrations WHERE version=9").get().name,'support-recovery-schema');const indexes=new Set(db.prepare("SELECT name FROM sqlite_master WHERE type='index'").all().map(x=>x.name));for(const name of ['support_customer','support_journey','support_correlation','support_case_events_case'])assert.ok(indexes.has(name));db.close();});


test('payment initiation lease generation is versioned and upgrades a V9-shaped database',()=>{const fresh=openStore(':memory:');let cols=fresh.prepare("PRAGMA table_info('payment_initiation_outbox')").all().map(x=>x.name);assert.ok(cols.includes('lease_version'));assert.equal(fresh.prepare("SELECT name FROM schema_migrations WHERE version=10").get().name,'payment-initiation-lease-generation');fresh.close();const dir=mkdtempSync(join(tmpdir(),'r2v-migrate-v10-')),file=join(dir,'db.sqlite');let db=openStore(file);db.prepare('DELETE FROM schema_migrations WHERE version=10').run();db.close();const raw=new DatabaseSync(file);raw.exec("ALTER TABLE payment_initiation_outbox RENAME TO payment_initiation_outbox_v9; CREATE TABLE payment_initiation_outbox(id TEXT PRIMARY KEY,payment_intent_id TEXT UNIQUE NOT NULL REFERENCES payment_intents(id),provider TEXT NOT NULL,payload TEXT NOT NULL,status TEXT NOT NULL,attempts INTEGER NOT NULL DEFAULT 0,last_error TEXT,provider_request_id TEXT,next_attempt_at TEXT,lease_owner TEXT,lease_expires_at TEXT,provider_acknowledgement TEXT,provider_acknowledged_at TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL); INSERT INTO payment_initiation_outbox(id,payment_intent_id,provider,payload,status,attempts,last_error,provider_request_id,next_attempt_at,lease_owner,lease_expires_at,provider_acknowledgement,provider_acknowledged_at,created_at,updated_at) SELECT id,payment_intent_id,provider,payload,status,attempts,last_error,provider_request_id,next_attempt_at,lease_owner,lease_expires_at,provider_acknowledgement,provider_acknowledged_at,created_at,updated_at FROM payment_initiation_outbox_v9; DROP TABLE payment_initiation_outbox_v9;");raw.close();db=openStore(file);cols=db.prepare("PRAGMA table_info('payment_initiation_outbox')").all().map(x=>x.name);assert.ok(cols.includes('lease_version'));assert.equal(db.prepare('SELECT MAX(version) AS version FROM schema_migrations').get().version,CURRENT_SCHEMA_VERSION);db.close();rmSync(dir,{recursive:true,force:true});});


test('payment initiation acceptance ambiguity is versioned in fresh schema',()=>{const db=openStore(':memory:');try{const cols=db.prepare("PRAGMA table_info('payment_initiation_outbox')").all().map(x=>x.name);assert.ok(cols.includes('acceptance_ambiguous'));assert.equal(db.prepare("SELECT name FROM schema_migrations WHERE version=11").get().name,'payment-initiation-acceptance-ambiguity');assert.equal(db.prepare('SELECT MAX(version) AS version FROM schema_migrations').get().version,CURRENT_SCHEMA_VERSION);}finally{db.close();}});


test('migration v12 preserves initiation lifetime attempt history',()=>{const db=new DatabaseSync(':memory:');db.exec("CREATE TABLE schema_migrations(version INTEGER PRIMARY KEY,name TEXT NOT NULL,applied_at TEXT NOT NULL,checksum TEXT); CREATE TABLE payment_initiation_outbox(id TEXT PRIMARY KEY,attempts INTEGER NOT NULL DEFAULT 0); INSERT INTO payment_initiation_outbox(id,attempts) VALUES('historic-init',5);");for(const m of migrations.filter(x=>x.version<12)){db.prepare('INSERT INTO schema_migrations(version,name,applied_at,checksum) VALUES(?,?,?,?)').run(m.version,m.name,new Date().toISOString(),checksum(m));}runMigrations(db);const row=db.prepare("SELECT attempts,total_attempts FROM payment_initiation_outbox WHERE id='historic-init'").get();assert.equal(row.attempts,5);assert.equal(row.total_attempts,5);assert.equal(db.prepare('SELECT MAX(version) AS version FROM schema_migrations').get().version,CURRENT_SCHEMA_VERSION);db.close();});


test('migration v13 adds provider rejection evidence without losing initiation history',()=>{const db=new DatabaseSync(':memory:');db.exec("CREATE TABLE schema_migrations(version INTEGER PRIMARY KEY,name TEXT NOT NULL,applied_at TEXT NOT NULL,checksum TEXT); CREATE TABLE payment_initiation_outbox(id TEXT PRIMARY KEY,attempts INTEGER NOT NULL DEFAULT 0,total_attempts INTEGER NOT NULL DEFAULT 0,last_error TEXT); INSERT INTO payment_initiation_outbox(id,attempts,total_attempts,last_error) VALUES('historic-v13',4,11,'PROVIDER_ACCEPTANCE_REJECTED');");for(const m of migrations.filter(x=>x.version<13)){db.prepare('INSERT INTO schema_migrations(version,name,applied_at,checksum) VALUES(?,?,?,?)').run(m.version,m.name,new Date().toISOString(),checksum(m));}runMigrations(db);const cols=new Set(db.prepare("PRAGMA table_info('payment_initiation_outbox')").all().map(x=>x.name));for(const name of ['provider_rejection_code','provider_rejection_reason','provider_rejected_at'])assert.ok(cols.has(name));const row=db.prepare("SELECT attempts,total_attempts,last_error,provider_rejection_code,provider_rejection_reason,provider_rejected_at FROM payment_initiation_outbox WHERE id='historic-v13'").get();assert.equal(row.attempts,4);assert.equal(row.total_attempts,11);assert.equal(row.last_error,'PROVIDER_ACCEPTANCE_REJECTED');assert.equal(row.provider_rejection_code,null);assert.equal(row.provider_rejection_reason,null);assert.equal(row.provider_rejected_at,null);assert.equal(db.prepare("SELECT name FROM schema_migrations WHERE version=13").get().name,'provider-initiation-rejection-evidence');assert.equal(db.prepare('SELECT MAX(version) AS version FROM schema_migrations').get().version,CURRENT_SCHEMA_VERSION);db.close();});


test('failed migration rolls back schema, data, and migration registry atomically',()=>{const db=new DatabaseSync(':memory:');db.exec("CREATE TABLE schema_migrations(version INTEGER PRIMARY KEY,name TEXT NOT NULL,applied_at TEXT NOT NULL,checksum TEXT); CREATE TABLE payment_initiation_outbox(id TEXT PRIMARY KEY,attempts INTEGER NOT NULL DEFAULT 0); INSERT INTO payment_initiation_outbox(id,attempts) VALUES('rollback-proof',7);");for(const m of migrations.filter(x=>x.version<12)){db.prepare('INSERT INTO schema_migrations(version,name,applied_at,checksum) VALUES(?,?,?,?)').run(m.version,m.name,new Date().toISOString(),checksum(m));}const target=migrations.find(x=>x.version===12),original=target.up;target.up=database=>{original(database);database.prepare("UPDATE payment_initiation_outbox SET total_attempts=999 WHERE id='rollback-proof'").run();throw Object.assign(new Error('INJECTED_MIGRATION_FAILURE'),{code:'INJECTED_MIGRATION_FAILURE'});};try{assert.throws(()=>runMigrations(db),e=>e.code==='INJECTED_MIGRATION_FAILURE');const cols=new Set(db.prepare("PRAGMA table_info('payment_initiation_outbox')").all().map(x=>x.name));assert.equal(cols.has('total_attempts'),false);assert.equal(db.prepare("SELECT attempts FROM payment_initiation_outbox WHERE id='rollback-proof'").get().attempts,7);assert.equal(db.prepare('SELECT 1 FROM schema_migrations WHERE version=12').get(),undefined);}finally{target.up=original;db.close();}});
