const test=require('node:test');const assert=require('node:assert/strict');const {DatabaseSync}=require('node:sqlite');const {mkdtempSync,rmSync}=require('node:fs');const {join}=require('node:path');const {tmpdir}=require('node:os');const {openStore}=require('../server/store');const {CURRENT_SCHEMA_VERSION}=require('../server/migrations');
test('openStore records current schema version on a fresh database',()=>{const db=openStore(':memory:');const rows=db.prepare('SELECT version,name FROM schema_migrations').all();assert.equal(rows.length,1);assert.equal(rows[0].version,CURRENT_SCHEMA_VERSION);db.close();});
test('legacy commerce price confirmation schema upgrades without losing order or price evidence',()=>{const dir=mkdtempSync(join(tmpdir(),'r2v-migrate-')),file=join(dir,'legacy.sqlite');const legacy=new DatabaseSync(file);legacy.exec(`PRAGMA foreign_keys=ON;
CREATE TABLE commerce_orders(id TEXT PRIMARY KEY,customer_id TEXT NOT NULL,merchant_id TEXT NOT NULL,basket TEXT NOT NULL,total INTEGER NOT NULL,currency TEXT NOT NULL,status TEXT NOT NULL,idempotency_key TEXT NOT NULL UNIQUE,version INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE commerce_price_confirmations(id TEXT PRIMARY KEY,order_id TEXT UNIQUE NOT NULL REFERENCES commerce_orders(id),merchant_id TEXT NOT NULL,amount INTEGER NOT NULL,currency TEXT NOT NULL,inventory_versions TEXT NOT NULL,confirmed_by TEXT,created_at TEXT NOT NULL);
INSERT INTO commerce_orders VALUES('o1','c1','m1','[{"sku":"x","qty":1}]',100,'KES','PRICE_CONFIRMED','legacy-o1',1,'2026-09-01T00:00:00.000Z','2026-09-01T00:00:00.000Z');
INSERT INTO commerce_price_confirmations VALUES('pc1','o1','m1',100,'KES','[["x",1]]','m1','2026-09-01T00:00:00.000Z');`);legacy.close();const db=openStore(file);const pc=db.prepare("SELECT * FROM commerce_price_confirmations WHERE id='pc1'").get();assert.equal(pc.order_id,'o1');assert.equal(pc.amount,100);assert.equal(pc.status,'ACTIVE');assert.equal(pc.supersedes_id,null);assert.equal(db.prepare("SELECT total FROM commerce_orders WHERE id='o1'").get().total,100);assert.equal(db.prepare('SELECT version FROM schema_migrations').get().version,CURRENT_SCHEMA_VERSION);const cols=db.prepare("PRAGMA table_info('commerce_price_confirmations')").all().map(x=>x.name);assert.ok(cols.includes('customer_acknowledged_at'));db.close();rmSync(dir,{recursive:true,force:true});});
test('migration is idempotent across repeated startup',()=>{const dir=mkdtempSync(join(tmpdir(),'r2v-migrate-repeat-')),file=join(dir,'db.sqlite');let db=openStore(file);db.close();db=openStore(file);assert.equal(db.prepare('SELECT COUNT(*) AS n FROM schema_migrations').get().n,1);db.close();rmSync(dir,{recursive:true,force:true});});
test('startup fails closed when database schema version is newer than application',()=>{const dir=mkdtempSync(join(tmpdir(),'r2v-migrate-newer-')),file=join(dir,'db.sqlite');const raw=new DatabaseSync(file);raw.exec("CREATE TABLE schema_migrations(version INTEGER PRIMARY KEY,name TEXT NOT NULL,applied_at TEXT NOT NULL); INSERT INTO schema_migrations VALUES(999,'future','2026-10-01T00:00:00.000Z')");raw.close();assert.throws(()=>openStore(file),e=>e.code==='DATABASE_SCHEMA_NEWER_THAN_APPLICATION');rmSync(dir,{recursive:true,force:true});});
