const assert=require('node:assert/strict'),{chromium}=require('playwright'),{createBrowserApp:createApp}=require('./helpers/browser-app.cjs');
(async()=>{const app=createApp({dbPath:':memory:',adminEmail:'admin@intel.test',adminPassword:'Test-Administrator-1234',startOperationsRuntime:false,startSideEffectRuntime:false});let browser;try{
 await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+app.server.address().port,admin=app.db.prepare("SELECT id,role FROM users WHERE role='admin'").get();const p=app.supply.createListing(admin,{title:'Synthetic public market home',description:'Test only',price:40000,transactionType:'rent',location:{city:'Nairobi'},property:{bedrooms:2}});app.db.prepare('UPDATE listings SET approved=1 WHERE id=?').run(p.id);app.db.prepare("UPDATE supply_checks SET status='APPROVED',expires_at=? WHERE target_id=?").run(new Date(Date.now()+86400000).toISOString(),p.id);for(let i=0;i<10;i++)app.intelligence.recordFailure(401,'/api/auth/login');
 const reg=await fetch(base+'/api/auth/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'Synthetic agent',email:'agent@intel.test',password:'Test-Agent-123456',role:'agent'})});assert.equal(reg.status,201);const agent=await reg.json();const other=app.supply.createListing(admin,{title:'Agent lead property',description:'Test only',price:30000,transactionType:'rent',location:{city:'Nairobi'},property:{bedrooms:1}});app.db.prepare('UPDATE listings SET owner_id=? WHERE id=?').run(agent.id,other.id);const time=new Date().toISOString();app.db.prepare("INSERT INTO property_slots VALUES('intel-slot',?,'2030-01-01T00:00:00Z','2030-01-01T01:00:00Z',1,?)").run(other.id,time);app.db.prepare("INSERT INTO viewing_requests VALUES('intel-request',?,?,'intel-slot','general','ACCEPTED',NULL,'intel-request',NULL,?,?)").run(admin.id,other.id,time,time);app.db.prepare("INSERT INTO property_leads VALUES('intel-request','NEGOTIATING','PRIVATE-NOTES',?)").run(time);
 browser=await chromium.launch({headless:true,...(process.env.R2V_CHROMIUM_EXECUTABLE?{executablePath:process.env.R2V_CHROMIUM_EXECUTABLE}:{}),args:['--no-sandbox','--disable-dev-shm-usage']});const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));const root=page.locator('#app-agents');
 async function login(email,password){await page.goto(base);await page.locator('#app-auth-form [name=email]').fill(email);await page.locator('#app-auth-form [name=password]').fill(password);await page.locator('#app-auth-form').getByRole('button',{name:'Sign in',exact:true}).click();await root.getByRole('button',{name:'Run assessment',exact:true}).waitFor();}
 await login('admin@intel.test','Test-Administrator-1234');await root.getByLabel('Choose assistant').selectOption('security-intelligence');await root.getByRole('button',{name:'Run assessment',exact:true}).click();await root.getByRole('button',{name:'Inspect security signals',exact:true}).click();await root.getByText(/minute: .*kind: AUTH_FAILURE/).waitFor();await root.getByRole('button',{name:'Mark reviewed',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#app-agents [data-workflow-id]>summary')?.textContent.endsWith('reviewed'));
 await root.getByLabel('Choose assistant').selectOption('market-intelligence');await root.getByRole('button',{name:'Run assessment',exact:true}).click();await root.getByRole('button',{name:'Inspect market source records',exact:true}).click();await root.getByText(/title: Synthetic public market home/).waitFor();await page.setViewportSize({width:390,height:844});assert.equal(await root.evaluate(e=>e.scrollWidth>e.clientWidth),false);await page.locator('#app-logout').click();await page.waitForFunction(()=>document.getElementById('app-agents').hidden);assert.equal(await root.textContent(),'');
 await login('agent@intel.test','Test-Agent-123456');assert.equal(await root.locator('option[value="security-intelligence"]').count(),0);await root.getByLabel('Choose assistant').selectOption('sales-intelligence');await root.getByRole('button',{name:'Run assessment',exact:true}).click();await root.getByRole('button',{name:'Inspect sales source records',exact:true}).click();await root.getByText(/id: intel-request · listing id:/).waitFor();assert(!(await root.textContent()).includes('PRIVATE-NOTES'));assert.equal(await root.evaluate(e=>e.scrollWidth>e.clientWidth),false);await page.locator('#app-logout').click();await page.waitForFunction(()=>document.getElementById('app-agents').hidden);assert.equal(await root.textContent(),'');assert.deepEqual(errors,[]);console.log('Intelligence browser: security/market admin reports, sales ownership, evidence, review, mobile and logout passed.');
 }finally{if(browser)await browser.close();await app.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
