const assert=require('node:assert/strict'),{chromium}=require('playwright'),{createApp}=require('../server/app');
(async()=>{const app=createApp({dbPath:':memory:',adminEmail:'admin@memory.test',adminPassword:'Test-Administrator-1234',startOperationsRuntime:false,startSideEffectRuntime:false});let browser;
 try{
  await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+app.server.address().port,email='customer@memory.test',password='Test-Customer-1234';
  const registration=await fetch(base+'/api/auth/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'Memory customer',email,password,role:'customer'})});assert.equal(registration.status,201);const customer=await registration.json(),actor={id:customer.id,role:'customer'},admin=app.db.prepare("SELECT id,role FROM users WHERE role='admin'").get();
  const p=app.supply.createListing(admin,{title:'Synthetic memory home',description:'Test only',price:40000,transactionType:'rent',location:{city:'Nairobi'},property:{bedrooms:2}});app.db.prepare('UPDATE listings SET approved=1 WHERE id=?').run(p.id);app.db.prepare("UPDATE supply_checks SET status='APPROVED',expires_at=? WHERE target_id=?").run(new Date(Date.now()+86400000).toISOString(),p.id);app.supply.profile(actor,{city:'Nairobi',budget:50000,goal:'rent',bedrooms:2});
  browser=await chromium.launch({headless:true,...(process.env.R2V_CHROMIUM_EXECUTABLE?{executablePath:process.env.R2V_CHROMIUM_EXECUTABLE}:{}),args:['--no-sandbox','--disable-dev-shm-usage']});const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(base);await page.locator('#app-auth-form [name=email]').fill(email);await page.locator('#app-auth-form [name=password]').fill(password);await page.locator('#app-auth-form').getByRole('button',{name:'Sign in',exact:true}).click();
  const root=page.locator('#app-agents'),panel=page.locator('#app-agent-memory');await panel.locator('summary').click();await panel.getByRole('button',{name:'Enable memory',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#app-agent-memory')?.textContent.includes('Memory is on.'));
  await root.getByRole('button',{name:'Run assessment',exact:true}).click();await root.getByRole('button',{name:'Remember as helpful',exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('[data-memory-id]').length===1);
  await root.getByRole('button',{name:'Exclude from future advice: Synthetic memory home',exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('[data-memory-id]').length===2);
  await root.getByLabel('Choose assistant').selectOption('opportunities');await root.getByRole('button',{name:'Run assessment',exact:true}).click();await page.waitForFunction(()=>Array.from(document.querySelectorAll('[data-workflow-id]>summary')).some(e=>e.textContent.startsWith('Property opportunities')&&e.textContent.endsWith('partial')));
  await page.reload();await panel.locator('summary').click();assert.equal(await panel.locator('[data-memory-id]').count(),2);
  const exclusion=panel.locator('[data-memory-id]').filter({hasText:'exclude property'});await exclusion.getByRole('button',{name:'Forget this entry',exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('[data-memory-id]').length===1);
  await root.getByLabel('Choose assistant').selectOption('memory-learning');await root.getByRole('button',{name:'Run assessment',exact:true}).click();await page.waitForFunction(()=>Array.from(document.querySelectorAll('[data-workflow-id]>summary')).some(e=>e.textContent.startsWith('Shared memory and learning')));
  await panel.locator('summary').click();await panel.getByRole('button',{name:'Pause memory',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#app-agent-memory')?.textContent.includes('Memory is off.'));assert.equal(await panel.locator('[data-memory-id]').count(),1);
  await panel.locator('summary').click();await panel.getByRole('button',{name:'Clear memory and turn off',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#app-agent-memory')?.textContent.includes('No memory entries saved.'));
  await page.setViewportSize({width:390,height:844});assert.equal(await root.evaluate(e=>e.scrollWidth>e.clientWidth),false);await page.locator('#app-logout').click();await page.waitForFunction(()=>document.getElementById('app-agents').hidden);assert.equal(await root.textContent(),'');assert.deepEqual(errors,[]);console.log('Memory browser: opt-in, feedback, exclusion, persisted controls, forget, report, pause, clear, mobile and logout passed.');
 }finally{if(browser)await browser.close();await app.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
