const test=require('node:test'),assert=require('node:assert/strict');
const {createApp}=require('../server/app'),{randomUUID,createHash}=require('node:crypto');
const {mkdtempSync,rmSync}=require('node:fs'),{tmpdir}=require('node:os'),{join}=require('node:path');
function fixture(t){const dir=mkdtempSync(join(tmpdir(),'r2v-memory-')),dbPath=join(dir,'db.sqlite');let app=createApp({dbPath,startOperationsRuntime:false,startSideEffectRuntime:false});t.after(async()=>{await app.close();rmSync(dir,{recursive:true,force:true});});const users={};for(const [id,role] of [['customer','customer'],['other','customer'],['admin','admin'],['driver','driver']]){app.db.prepare('INSERT INTO users VALUES(?,?,?,?,?,1)').run(id,id+'@example.test',id,'unused',role);users[id]={id,role};}return {get app(){return app;},...users,restart:async()=>{await app.close();app=createApp({dbPath,startOperationsRuntime:false,startSideEffectRuntime:false});}};}
const run=(f,u,workflow='property-advice',extra={})=>f.app.agentWorkflows.create(u,{workflow,idempotencyKey:randomUUID(),...extra});
const enable=(f,u)=>f.app.memory.configure(u,{version:f.app.memory.view(u).version,enabled:true});
const remember=(f,u,source,extra={})=>f.app.memory.remember(u,{version:f.app.memory.view(u).version,kind:'FEEDBACK',sourceWorkflowId:source.id,value:'HELPFUL',...extra});
function property(f){const p=f.app.supply.createListing(f.admin,{title:'Synthetic memory home',description:'Testing only',price:40000,transactionType:'rent',location:{city:'Nairobi'},property:{bedrooms:2}});f.app.db.prepare('UPDATE listings SET approved=1 WHERE id=?').run(p.id);f.app.db.prepare("UPDATE supply_checks SET status='APPROVED',expires_at=? WHERE target_id=?").run(new Date(Date.now()+86400000).toISOString(),p.id);f.app.supply.profile(f.customer,{city:'Nairobi',budget:50000,goal:'rent',bedrooms:2});return p;}
test('memory defaults off, is explicit, survives restart and counts feedback once',async t=>{
 const f=fixture(t),source=await run(f,f.customer);assert.equal(f.app.memory.view(f.customer).enabled,false);assert.throws(()=>remember(f,f.customer,source),/Enable/);enable(f,f.customer);remember(f,f.customer,source);remember(f,f.customer,source,{value:'NOT_HELPFUL'});await f.restart();const s=f.app.memory.snapshot(f.customer);assert.deepEqual(s.feedback,{HELPFUL:0,NOT_HELPFUL:1});assert.equal(f.app.memory.view(f.customer).entries.length,1);const report=await run(f,f.customer,'memory-learning');assert.equal(report.nodes[0].output.feedback.NOT_HELPFUL,1);assert.equal(report.nodes[0].confidence,null);
});
test('explicit exclusions are reused across property specialists and opportunities, and forgetting restores eligibility',async t=>{
 const f=fixture(t),p=property(f);enable(f,f.customer);const source=await run(f,f.customer);remember(f,f.customer,source,{kind:'EXCLUDE_PROPERTY',listingId:p.id,value:'EXCLUDE'});
 const next=await run(f,f.customer),opp=await run(f,f.customer,'opportunities');assert.equal(next.nodes.find(n=>n.agent==='property-agent').output.properties.length,0);assert.equal(next.nodes.find(n=>n.agent==='lead-qualification-agent').output.assessments.length,0);assert.equal(opp.nodes[0].output.opportunities.length,0);assert.equal(next.memory.exclusions[0].sourceWorkflowId,source.id);
 await assert.rejects(run(f,f.customer,'property-advice',{listingId:p.id}),/excluded/);const v=f.app.memory.view(f.customer);f.app.memory.forget(f.customer,v.entries[0].id,{version:v.version});assert.equal((await run(f,f.customer,'opportunities')).nodes[0].output.opportunities[0].id,p.id);
 // Profile remains authoritative even with memory enabled.
 f.app.supply.profile(f.customer,{city:'Nairobi',budget:1000,goal:'rent'});assert.equal((await run(f,f.customer,'opportunities')).nodes[0].output.opportunities.length,0);
});
test('pause and clear affect future advice, expiration excludes old feedback and no other account memory changes',async t=>{
 const f=fixture(t),p=property(f);enable(f,f.customer);const source=await run(f,f.customer);remember(f,f.customer,source,{kind:'EXCLUDE_PROPERTY',listingId:p.id,value:'EXCLUDE'});let v=f.app.memory.view(f.customer);f.app.memory.configure(f.customer,{version:v.version,enabled:false});assert.equal(f.app.memory.snapshot(f.customer).exclusions.length,0);assert.equal(f.app.memory.view(f.customer).entries.length,1);enable(f,f.customer);assert.equal(f.app.memory.snapshot(f.customer).exclusions.length,1);f.app.db.prepare("UPDATE agent_memory_entries SET expires_at='2000-01-01T00:00:00Z'").run();assert.equal(f.app.memory.snapshot(f.customer).exclusions.length,0);remember(f,f.customer,source);enable(f,f.other);const other=await run(f,f.other);remember(f,f.other,other);v=f.app.memory.view(f.customer);f.app.memory.clear(f.customer,{version:v.version});assert.equal(f.app.memory.view(f.customer).entries.length,0);assert.equal(f.app.memory.view(f.customer).enabled,false);assert.equal(f.app.memory.view(f.other).entries.length,1);assert.equal(f.app.agentWorkflows.get(f.customer,source.id).id,source.id);
});
test('source ownership, role access and recommendation membership are enforced',async t=>{
 const f=fixture(t),source=await run(f,f.customer);for(const u of [f.customer,f.other,f.admin])enable(f,u);for(const u of [f.other,f.admin])assert.throws(()=>remember(f,u,source),/not found/);assert.throws(()=>remember(f,f.customer,source,{kind:'EXCLUDE_PROPERTY',listingId:'invented',value:'EXCLUDE'}),/not a recommendation/);remember(f,f.customer,source);const item=f.app.memory.view(f.customer).entries[0];assert.throws(()=>f.app.memory.forget(f.other,item.id,{version:f.app.memory.view(f.other).version}),/not found/);const demoted={id:'customer',role:'driver'};assert.equal(f.app.memory.view(demoted).entries.length,0);assert.throws(()=>remember(f,demoted,source),/not available/);assert.equal(f.app.memory.view(f.admin).entries.length,0);
});
test('stale writes roll back and disabling memory fences pending assessments',async t=>{
 const f=fixture(t);enable(f,f.customer);const source=await run(f,f.customer);const version=f.app.memory.view(f.customer).version;remember(f,f.customer,source);assert.throws(()=>f.app.memory.clear(f.customer,{version}),/changed/);assert.equal(f.app.memory.view(f.customer).entries.length,1);
 const fresh=await run(f,f.customer);f.app.db.prepare("UPDATE agent_workflows SET status='RUNNING',lease_until=0 WHERE id=?").run(fresh.id);f.app.memory.clear(f.customer,{version:f.app.memory.view(f.customer).version});await assert.rejects(f.app.agentWorkflows.execute(f.customer,fresh.id),/Memory changed/);
});
test('memory changes while an assessment executes prevent stale publication',async t=>{
 const f=fixture(t);enable(f,f.customer);const pending=run(f,f.customer);f.app.memory.clear(f.customer,{version:f.app.memory.view(f.customer).version});await assert.rejects(pending,/Memory changed/);assert.notEqual(f.app.db.prepare('SELECT status FROM agent_workflows').get().status,'COMPLETED');
});
test('unsupported inputs cannot write inferred traits or recursive feedback',async t=>{
 const f=fixture(t);enable(f,f.customer);const source=await run(f,f.customer),report=await run(f,f.customer,'memory-learning');assert.throws(()=>remember(f,f.customer,source,{trait:'religion'}),/Unexpected/);assert.throws(()=>remember(f,f.customer,report),/original/);assert.throws(()=>remember(f,f.customer,source,{kind:'UNKNOWN'}),/Unknown/);assert.equal(f.app.memory.view(f.customer).entries.length,0);
});
test('HTTP memory endpoints enforce authentication and owner-scoped bodies',async t=>{
 const f=fixture(t);f.app.db.prepare('INSERT INTO sessions VALUES(?,?,?)').run(createHash('sha256').update('customer').digest('hex'),'customer',Date.now()+60000);await new Promise(r=>f.app.server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+f.app.server.address().port+'/api/agents/memory';assert.equal((await fetch(url)).status,401);const headers={'Content-Type':'application/json',Cookie:'r2v_session=customer'};assert.equal((await fetch(url+'/settings',{method:'POST',headers,body:JSON.stringify({version:0,enabled:true,ownerId:'other'})})).status,400);assert.equal((await fetch(url+'/settings',{method:'POST',headers,body:JSON.stringify({version:0,enabled:true})})).status,200);assert.equal((await fetch(url+'/clear',{method:'POST',headers,body:JSON.stringify({version:0})})).status,409);
});
test('expired memory cannot be resumed and bounded storage rolls back without losing entries',async t=>{
 const f=fixture(t);enable(f,f.customer);const source=await run(f,f.customer);remember(f,f.customer,source);const report=await run(f,f.customer,'memory-learning');const row=f.app.db.prepare('SELECT journey FROM agent_workflows WHERE id=?').get(report.id),j=JSON.parse(row.journey);j.nodes[0].input.memoryState.validUntil='2000-01-01T00:00:00Z';f.app.db.prepare("UPDATE agent_workflows SET status='PENDING',journey=? WHERE id=?").run(JSON.stringify(j),report.id);await assert.rejects(f.app.agentWorkflows.execute(f.customer,report.id),/expired/);
 const time=new Date().toISOString(),expires=new Date(Date.now()+86400000).toISOString();for(let i=0;i<199;i++)f.app.db.prepare('INSERT INTO agent_memory_entries VALUES(?,?,?,?,?,?,?,?,?,?,?)').run('limit-'+i,f.customer.id,'customer','EXCLUDE_PROPERTY','limit-'+i,'EXCLUDE',source.id,source.version,time,time,expires);const next=await run(f,f.customer);const before=f.app.memory.view(f.customer).version;assert.throws(()=>remember(f,f.customer,next),/full/);assert.equal(f.app.memory.view(f.customer).version,before);assert.equal(f.app.memory.view(f.customer).entries.length,200);
});
test('migration 24 upgrades an existing database without rewriting previous migrations or domain records',async t=>{
 const f=fixture(t),source=await run(f,f.customer),before=f.app.db.prepare('SELECT version,checksum FROM schema_migrations WHERE version<24').all();f.app.db.exec('DROP TABLE agent_memory_entries; DROP TABLE agent_memory_settings; DELETE FROM schema_migrations WHERE version=24');await f.restart();assert.deepEqual(f.app.db.prepare('SELECT version,checksum FROM schema_migrations WHERE version<24').all(),before);assert.equal(f.app.agentWorkflows.get(f.customer,source.id).id,source.id);assert.equal(f.app.memory.view(f.customer).enabled,false);
});

test('memory reports retain source-role access after account demotion',async t=>{
 const f=fixture(t);enable(f,f.admin);const source=await run(f,f.admin,'data-quality');remember(f,f.admin,source);const report=await run(f,f.admin,'memory-learning');const demoted={id:f.admin.id,role:'customer'};assert.throws(()=>f.app.agentWorkflows.get(demoted,report.id),/not available/);assert.equal(f.app.agentWorkflows.list(demoted).length,0);assert.deepEqual(f.app.memory.snapshot(demoted).feedback,{HELPFUL:0,NOT_HELPFUL:0});
});
