const {createHash}=require('node:crypto');
const {rules}=require('./rules');
const fail=(status,message)=>{throw Object.assign(new Error(message),{status});};
function admin(a){if(!a)fail(401,'Sign in to continue');if(a.role!=='admin')fail(403,'Administrator access required');}
function createQuality({db,supply}){
 function rows(rule,{count=false,offset=0}={}){if(typeof rule!=='string'||!Object.hasOwn(rules,rule))fail(400,'Unknown quality rule');const sql=rules[rule].sql,params=sql.includes(':now')?{now:new Date().toISOString()}:{};return db.prepare(count?`SELECT count(*) n FROM (${sql})`:`SELECT * FROM (${sql}) ORDER BY id LIMIT 50 OFFSET :offset`).all(count?params:{...params,offset});}
 function snapshot(actor){admin(actor);db.exec('BEGIN');try{const checks=Object.entries(rules).map(([rule,r])=>({rule,title:r.title,severity:r.severity,count:rows(rule,{count:true})[0].n,suggestedAction:r.action,evidence:{rule}}));const result={generatedAt:new Date().toISOString(),checks};db.exec('COMMIT');return result;}catch(e){db.exec('ROLLBACK');throw e;}}
 function evidence(actor,input){admin(actor);const offset=input.offset??0;if(!Number.isSafeInteger(offset)||offset<0||offset>1000000)fail(400,'Invalid evidence offset');const total=rows(input.rule,{count:true})[0].n;return {rule:input.rule,title:rules[input.rule].title,total,offset,limit:50,records:rows(input.rule,{offset}),observedAt:new Date().toISOString()};}
 function target(actor,id){if(!actor)fail(401,'Sign in to continue');const row=db.prepare('SELECT * FROM agent_workflows WHERE id=? AND owner_id=?').get(id,actor.id);if(!row)fail(404,'Source assessment not found');if(row.workflow==='ai-critic')fail(409,'Choose an original assessment, not another critic');if(!['COMPLETED','REVIEW_REQUIRED','PARTIAL','REVIEWED','DISMISSED'].includes(row.status))fail(409,'Source assessment is still running');return row;}
 function criticSnapshot(actor,id){
  const row=target(actor,id);let journey;try{journey=JSON.parse(row.journey);}catch{journey=null;}
  const malformed=!journey||!Array.isArray(journey.nodes)||journey.nodes.some(n=>!n||typeof n!=='object'||Array.isArray(n));
  const nodes=malformed?[]:journey.nodes,currentChecks=[],add=(code,nodeId,sourceId,reason)=>currentChecks.push({code,severity:'MEDIUM',nodeId,sourceId,reason});
  for(const n of nodes){const o=n.output||{},i=n.input||{};
   if(n.responsible_agent==='transaction-agent'&&i.recordedPayment){const id=typeof i.recordedPayment.bookingId==='string'?i.recordedPayment.bookingId:'';const p=db.prepare('SELECT p.amount,p.status,b.customer_id FROM payments p JOIN bookings b ON b.id=p.booking_id WHERE b.id=?').get(id);if(!p||actor.role!=='admin'&&p.customer_id!==actor.id)add('PAYMENT_UNVERIFIABLE',n.node_id,id,'Current payment evidence is unavailable within your access.');else if(p.amount!==o.amount||p.status!==o.paymentStatus)add('PAYMENT_CHANGED',n.node_id,id,'The payment record has changed since this assessment.');}
   if(n.responsible_agent==='property-agent')for(const property of Array.isArray(o.properties)?o.properties:[]){if(!property||typeof property!=='object')continue;const p=db.prepare('SELECT * FROM listings WHERE id=?').get(typeof property.id==='string'?property.id:'');if(!p||!supply.visible(p))add('PROPERTY_UNAVAILABLE',n.node_id,property.id,'A recommended property is no longer publicly available.');else{let data;try{data=JSON.parse(p.payload);}catch{data=null;}if(!data||data.price!==property.price)add('PROPERTY_CHANGED',n.node_id,property.id,'Current property price cannot be confirmed against the recommendation.');}}
   if(n.responsible_agent==='lead-qualification-agent'){const prefs=db.prepare('SELECT preferences FROM customer_profiles WHERE user_id=?').get(actor.id);let current;try{current=JSON.parse(prefs?.preferences||'{}');}catch{current=null;}if(JSON.stringify(current)!==JSON.stringify(i.preferences||{}))add('PREFERENCES_CHANGED',n.node_id,actor.id,'Your saved preferences differ from the qualification snapshot.');}
   if(n.responsible_agent==='scheduling-agent'&&o.resource_id){const slot=db.prepare('SELECT * FROM property_slots WHERE id=?').get(typeof o.resource_id==='string'?o.resource_id:'');if(!slot||!slot.enabled||slot.start_at<=new Date().toISOString()||slot.start_at!==o.recommended_start||slot.end_at!==o.recommended_end||db.prepare("SELECT 1 FROM viewing_requests WHERE slot_id=? AND status IN ('REQUESTED','ACCEPTED')").get(o.resource_id))add('SLOT_CHANGED',n.node_id,o.resource_id,'The recommended slot is no longer the same future unoccupied slot. Booking must revalidate all calendar and eligibility rules.');}
   if(n.responsible_agent==='rideplate-agent'&&Array.isArray(o.basket))for(const item of o.basket){if(!item||typeof item!=='object')continue;const stock=db.prepare("SELECT i.quantity,i.unit_price,m.status FROM commerce_inventory i JOIN commerce_merchants m ON m.id=i.merchant_id WHERE i.merchant_id=? AND i.sku=?").get(typeof o.merchant_id==='string'?o.merchant_id:'',typeof item.sku==='string'?item.sku:'');if(!stock||stock.status!=='VERIFIED'||stock.quantity<item.qty)add('STOCK_CHANGED',n.node_id,item.sku,'Recommended stock is no longer confirmed as available.');else if(o.basket.length===1&&stock.unit_price*item.qty!==o.authoritative_total)add('PRICE_CHANGED',n.node_id,item.sku,'The current item price differs from the quoted recommendation.');}
  }
  return {id:row.id,version:row.version,status:row.status,createdAt:row.created_at,generatedAt:new Date().toISOString(),hash:createHash('sha256').update(row.journey).digest('hex'),expired:row.expires_at<=new Date().toISOString(),malformed,nodes,currentChecks};
 }
 function routes({path,method,user,body,send}){if(path==='/api/admin/quality/evidence'&&method==='POST'){send(200,evidence(user,body));return true;}return false;}
 return {snapshot,evidence,target,criticSnapshot,routes};
}
module.exports={createQuality};
