// Queries expose only identifiers and structured state, never document bodies or payment references.
const rules={
 booking_payment:{title:'Viewing payment amount differs from booking',severity:'HIGH',action:'Reconcile the booking and payment through the finance workflow before making changes.',sql:"SELECT b.id,b.status,b.amount booking_amount,p.amount payment_amount FROM bookings b JOIN payments p ON p.booking_id=b.id WHERE b.amount<>p.amount"},
 missing_payment:{title:'Viewing booking has no payment record',severity:'HIGH',action:'Inspect creation history; do not fabricate a payment or received-money record.',sql:'SELECT b.id,b.status,b.created_at FROM bookings b LEFT JOIN payments p ON p.booking_id=b.id WHERE p.id IS NULL'},
 commerce_payment:{title:'Order and payment disagree on amount or currency',severity:'HIGH',action:'Reconcile authoritative order and payment records before fulfilment.',sql:'SELECT o.id,o.status,o.total order_amount,p.amount payment_amount,o.currency order_currency,p.currency payment_currency FROM commerce_orders o JOIN commerce_payments p ON p.order_id=o.id WHERE o.total<>p.amount OR o.currency<>p.currency'},
 missing_reservation:{title:'Active viewing has no reservation binding',severity:'HIGH',action:'Inspect the booking reservation workflow before dispatching.',sql:"SELECT b.id,b.status FROM bookings b LEFT JOIN booking_reservations br ON br.booking_id=b.id WHERE b.status IN ('requested','confirmed','assigned') AND br.booking_id IS NULL"},
 ledger_binding:{title:'Ledger entry differs from its shared reference record',severity:'HIGH',action:'Inspect reconciliation evidence. Different entries are not proof of fraud.',sql:'SELECT l.id,l.kind,l.amount ledger_amount,r.amount reference_amount,l.currency ledger_currency,r.currency reference_currency FROM financial_ledger_events l JOIN payment_references r ON r.reference=l.reference WHERE l.amount<>r.amount OR l.currency<>r.currency'},
 missing_journal:{title:'Received payment has no matching capture journal',severity:'MEDIUM',action:'Review journal coverage and legacy records; absence is not proof that payment was never received.',sql:"SELECT p.id,'viewing' service,p.status,p.amount FROM payments p WHERE p.amount>0 AND p.status IN ('paid','refund_pending','refunded') AND NOT EXISTS(SELECT 1 FROM financial_ledger_events l WHERE l.reference=p.reference AND l.direction='CREDIT' AND l.event_type='PAYMENT_CAPTURED') UNION ALL SELECT p.id,'ride2go',p.status,p.amount FROM ride2go_payments p WHERE p.status IN ('paid','refund_pending','refunded') AND NOT EXISTS(SELECT 1 FROM financial_ledger_events l WHERE l.reference=p.reference AND l.direction='CREDIT' AND l.event_type='PAYMENT_CAPTURED') UNION ALL SELECT p.id,'commerce',p.status,p.amount FROM commerce_payments p WHERE p.status IN ('paid','refund_pending','refunded') AND NOT EXISTS(SELECT 1 FROM financial_ledger_events l WHERE l.reference=p.reference AND l.direction='CREDIT' AND l.event_type='PAYMENT_CAPTURED') UNION ALL SELECT p.case_id,'property_service',p.status,p.amount FROM property_service_payments p WHERE p.status IN ('paid','refund_pending','refunded') AND NOT EXISTS(SELECT 1 FROM financial_ledger_events l WHERE l.reference=p.reference AND l.direction='CREDIT' AND l.event_type='PAYMENT_CAPTURED')"},
 reconciliation_binding:{title:'Reconciliation expectation differs from its ledger entry',severity:'HIGH',action:'Compare the ledger event and reconciliation record without overwriting either.',sql:'SELECT r.id,r.status,r.expected_amount,l.amount ledger_amount,r.currency expected_currency,l.currency ledger_currency FROM reconciliation_records r JOIN financial_ledger_events l ON l.id=r.ledger_event_id WHERE r.expected_amount<>l.amount OR r.currency<>l.currency'},
 missing_reconciliation:{title:'Ledger entry has no reconciliation record',severity:'MEDIUM',action:'Review migration history and accounting evidence before restoring the missing binding.',sql:'SELECT l.id,l.kind,l.amount,l.currency FROM financial_ledger_events l LEFT JOIN reconciliation_records r ON r.ledger_event_id=l.id WHERE r.id IS NULL'},
 invalid_listing_json:{title:'Listing payload is not valid JSON',severity:'HIGH',action:'Review the original listing record and restore from verified source evidence.',sql:'SELECT id FROM listings WHERE NOT json_valid(payload)'},
 invalid_driver_json:{title:'Driver profile is not valid JSON',severity:'HIGH',action:'Review the driver profile; do not infer eligibility from malformed data.',sql:'SELECT user_id id,revision,online FROM driver_profiles WHERE NOT json_valid(payload)'},
 invalid_case_json:{title:'Property-service data is not valid JSON',severity:'HIGH',action:'Review the case history and evidence before restoring the data.',sql:'SELECT id,kind,status FROM property_service_cases WHERE NOT json_valid(data)'},
 invalid_workflow_json:{title:'Saved agent journey is not valid JSON',severity:'HIGH',action:'Inspect the saved assessment and its execution history.',sql:'SELECT id,workflow,status FROM agent_workflows WHERE NOT json_valid(journey)'},
 stale_publication:{title:'Publication flag lacks current property checks',severity:'MEDIUM',action:'Renew the required review through the property workflow. Normal public listing filters already check validity.',sql:"SELECT l.id FROM listings l WHERE l.approved=1 AND (NOT EXISTS(SELECT 1 FROM supply_checks c WHERE c.target_id=l.id AND c.kind='marketing' AND c.status='APPROVED' AND c.expires_at>:now) OR NOT EXISTS(SELECT 1 FROM supply_checks c WHERE c.target_id=l.id AND c.kind='ownership' AND c.status='APPROVED' AND c.expires_at>:now) OR NOT EXISTS(SELECT 1 FROM supply_checks c WHERE c.target_id=l.id AND c.kind='publication' AND c.status='APPROVED' AND c.expires_at>:now))"},
 stale_driver_review:{title:'Driver approval refers to an expired or changed profile',severity:'MEDIUM',action:'Review eligibility through onboarding. This does not establish unsafe driving or fraud.',sql:"SELECT d.user_id id,d.revision,c.profile_revision,c.expires_at FROM driver_profiles d JOIN mobility_checks c ON c.subject_id=d.user_id AND c.kind='driver' WHERE c.status='APPROVED' AND (c.profile_revision IS NULL OR c.profile_revision<>d.revision OR c.expires_at IS NULL OR c.expires_at<=:now)"},
 invalid_slot:{title:'Viewing slot has invalid or reversed times',severity:'HIGH',action:'Review the calendar record and affected requests before changing availability.',sql:'SELECT id,listing_id,start_at,end_at FROM property_slots WHERE julianday(start_at) IS NULL OR julianday(end_at) IS NULL OR julianday(start_at)>=julianday(end_at)'},
 missing_delivery_evidence:{title:'Delivered shipment lacks recorded delivery evidence',severity:'HIGH',action:'Inspect custody history; do not fabricate recipient confirmation or proof.',sql:"SELECT s.id,s.status FROM logistics_shipments s WHERE s.status='DELIVERED' AND NOT EXISTS(SELECT 1 FROM logistics_delivery_proofs p WHERE p.shipment_id=s.id AND length(trim(p.proof_ref))>0 AND length(trim(p.recipient_confirmation))>0) AND NOT EXISTS(SELECT 1 FROM logistics_events e WHERE e.shipment_id=s.id AND e.event_type='DELIVERED' AND length(trim(COALESCE(e.evidence_ref,'')))>0)"}
};
module.exports={rules};
