const {randomUUID,createHash}=require('node:crypto');
const {createLedgerAuthority}=require('../payments/ledger/ledger-authority');
const {remoteConflict}=require('./calendar');
const now=()=>new Date().toISOString();
function fail(status,message){throw Object.assign(new Error(message),{status});}
function text(v,label,max=2000){if(typeof v!=='string'||!v.trim()||v.length>max)fail(400,label+' is required');return v.trim();}
function role(a,...roles){if(!a)fail(401,'Sign in to continue');if(!roles.includes(a.role))fail(403,'This account cannot perform this action');}
function integer(v,min,max,label){if(!Number.isSafeInteger(v)||v<min||v>max)fail(400,label+' is outside the allowed range');return v;}
function instant(v){if(typeof v!=='string'||!/(Z|[+-]\d\d:\d\d)$/.test(v)||!Number.isFinite(Date.parse(v)))fail(400,'Use an explicit UTC offset');return new Date(v).toISOString();}
function createPropertyServices({db,supply,audit=()=>{},notify=()=>{}}){
 const ledger=createLedgerAuthority({db,audit});
 function tx(fn){db.exec('BEGIN IMMEDIATE');try{const r=fn();db.exec('COMMIT');return r;}catch(e){db.exec('ROLLBACK');throw e;}}
 function event(a,c,type,details={}){db.prepare('INSERT INTO property_service_events VALUES(?,?,?,?,?,?)').run(randomUUID(),c.id,a.id,type,JSON.stringify(details),now());audit(a,'property_service.'+type.toLowerCase(),c.id,details);}
 function raw(id){const c=db.prepare('SELECT * FROM property_service_cases WHERE id=?').get(id);if(!c)fail(404,'Service case not found');return {...c,data:JSON.parse(c.data)};}
 function access(a,id){role(a,'customer','agent','admin');const c=raw(id);if(a.role!=='admin'&&a.id!==c.customer_id&&a.id!==c.agent_id)fail(403,'This case belongs to another account');return c;}
 function save(a,c,type,details={}){db.prepare('UPDATE property_service_cases SET status=?,data=?,version=version+1,updated_at=? WHERE id=?').run(c.status,JSON.stringify(c.data),now(),c.id);event(a,c,type,details);notify(c.customer_id,'Property service '+c.kind+': '+type.toLowerCase().replaceAll('_',' '));return get(a,c.id);}
 function current(c){if(!supply.visible(supply.listing(c.listing_id)))fail(409,'Property verification or availability needs renewal');}
 function expired(c){return ['QUOTED','PAYABLE'].includes(c.status)&&c.data.expiresAt<=now();}
 function get(a,id){const c=access(a,id),d=c.data;if(expired(c))c.status='EXPIRED';const payment=db.prepare('SELECT * FROM property_service_payments WHERE case_id=?').get(id);const documents=db.prepare('SELECT id,name,mime,sha256,owner_id,created_at FROM property_service_documents WHERE case_id=? ORDER BY created_at').all(id);const agent=a.role==='agent';if(agent){delete d.report;delete d.reportDraft;delete d.reviewerId;delete d.reviewEvidence;delete d.paymentNote;}else if(a.role!=='admin')delete d.reportDraft;
 // Session and recording credentials are never present in collection responses or audit history.
 d.roomConfigured=Boolean(d.room);d.recordingAttached=Boolean(d.recording);delete d.room;delete d.recording;
 if(d.contact&&!d.contact.authorized&&a.role==='agent')delete d.contact;
 return {...c,data:d,listing:JSON.parse(supply.listing(c.listing_id).payload),payment:agent?undefined:payment,documents:agent?documents.filter(x=>x.owner_id===a.id):documents,events:db.prepare('SELECT event,created_at FROM property_service_events WHERE case_id=? ORDER BY rowid').all(id)};
 }
 function list(a){role(a,'customer','agent','admin');const where=a.role==='admin'?'1=1':a.role==='agent'?'agent_id=?':'customer_id=?';return (a.role==='admin'?db.prepare('SELECT id FROM property_service_cases WHERE '+where+' ORDER BY created_at DESC').all():db.prepare('SELECT id FROM property_service_cases WHERE '+where+' ORDER BY created_at DESC').all(a.id)).map(c=>get(a,c.id));}
 function configuration(a,b){role(a,'customer','agent','admin');const latest=()=>{const r=db.prepare('SELECT * FROM property_service_config ORDER BY version DESC LIMIT 1').get();return r?{version:r.version,...JSON.parse(r.data)}:{version:0,hosts:[],label:'Video provider not configured'};};if(b===undefined)return latest();role(a,'admin');if(!Array.isArray(b.hosts)||b.hosts.length>10)fail(400,'Provide up to ten approved video/recording hostnames');const hosts=[...new Set(b.hosts.map(h=>{h=text(h,'Hostname',253).toLowerCase();if(!/^(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z]{2,}$/.test(h))fail(400,'Use exact public provider hostnames');return h;}))];const config={hosts,label:text(b.label,'Provider arrangement label',150)};return tx(()=>{const version=latest().version+1;db.prepare('INSERT INTO property_service_config VALUES(?,?,?,?)').run(version,JSON.stringify(config),a.id,now());audit(a,'property_service.provider_configured',String(version),config);return {version,...config};});}
 function providerURL(a,url){const config=configuration(a);let u;try{u=new URL(url);}catch{fail(400,'Valid provider URL required');}if(u.protocol!=='https:'||u.username||u.password||u.port||!config.hosts.includes(u.hostname))fail(400,'Use an HTTPS URL on an operations-approved provider hostname');return u.toString();}
 function calendar(c){const d=c.data;if(remoteConflict(db,c.agent_id,c.listing_id,d.startAt,d.endAt,c.id))fail(409,'Agent or property already has a remote viewing');if(db.prepare(`SELECT v.id FROM viewing_requests v JOIN listings l ON l.id=v.listing_id JOIN property_slots s ON s.id=v.slot_id WHERE v.status='ACCEPTED' AND (l.owner_id=? OR l.id=?) AND s.start_at<? AND s.end_at>?`).get(c.agent_id,c.listing_id,d.endAt,d.startAt))fail(409,'Agent or property already has a physical viewing');if(db.prepare("SELECT id FROM reservations WHERE resource_id=? AND status IN ('HOLD_CREATED','CONFIRMED','ACTIVE','RESCHEDULED') AND (hold_expires_at IS NULL OR hold_expires_at>?) AND start_at<? AND end_at>?").get(c.listing_id,now(),d.endAt,d.startAt))fail(409,'Property reservation conflicts');}
 function create(a,b){role(a,'customer');const key=text(b.idempotencyKey,'Idempotency key',128);if(!['remote','diligence'].includes(b.kind))fail(400,'Select remote viewing or due diligence');const listing=supply.listing(b.listingId);const request={goal:text(b.goal,'Service questions or goals',2000)};if(b.kind==='remote'){request.startAt=instant(b.startAt);request.endAt=instant(b.endAt);if(request.startAt<=now()||Date.parse(request.startAt)>Date.now()+90*86400000||request.endAt<=request.startAt||Date.parse(request.endAt)-Date.parse(request.startAt)>120*60000)fail(400,'Choose a future session of up to two hours within 90 days');try{new Intl.DateTimeFormat('en',{timeZone:b.timeZone}).format();}catch{fail(400,'Valid IANA timezone required');}request.timeZone=text(b.timeZone,'Timezone',100);}
 return tx(()=>{const prior=db.prepare('SELECT id,listing_id,kind,data FROM property_service_cases WHERE customer_id=? AND idempotency_key=?').get(a.id,key);if(prior){if(prior.listing_id!==listing.id||prior.kind!==b.kind||JSON.stringify(JSON.parse(prior.data).request)!==JSON.stringify(request))fail(409,'Idempotency key belongs to another request');return {...get(a,prior.id),duplicate:true};}if(!supply.visible(listing))fail(409,'Choose a currently verified available property');const id=randomUUID(),stamp=now();db.prepare("INSERT INTO property_service_cases VALUES(?,?,?,?,?,'REQUESTED',1,?,?,?,?)").run(id,a.id,listing.owner_id,listing.id,b.kind,JSON.stringify({...request,request,questions:[],negotiation:[]}),key,stamp,stamp);const c=raw(id);event(a,c,'REQUESTED');notify(listing.owner_id,'New '+b.kind+' property service request');return get(a,id);});}
 function document(a,b){return tx(()=>{const c=access(a,b.caseId);if(c.status==='CANCELLED'||(c.status==='COMPLETED'&&a.id!==c.customer_id))fail(409,'Evidence collection has closed');const name=text(b.name,'Document name',120);if(!['application/pdf','image/png','image/jpeg'].includes(b.mime)||typeof b.data!=='string'||!b.data.length||b.data.length>2800000||!/^[A-Za-z0-9+/]*={0,2}$/.test(b.data))fail(400,'Upload PDF, PNG or JPEG up to 2 MiB');const bytes=Buffer.from(b.data,'base64');if(bytes.length>2097152||bytes.length<4||!(b.mime==='application/pdf'&&bytes.subarray(0,5).toString()==='%PDF-'||b.mime==='image/png'&&bytes.subarray(0,8).equals(Buffer.from('89504e470d0a1a0a','hex'))||b.mime==='image/jpeg'&&bytes[0]===255&&bytes[1]===216&&bytes[2]===255))fail(400,'Document content does not match its type');const id=randomUUID();db.prepare('INSERT INTO property_service_documents VALUES(?,?,?,?,?,?,?,?)').run(id,c.id,a.id,name,b.mime,bytes,createHash('sha256').update(bytes).digest('hex'),now());event(a,c,'EVIDENCE_UPLOADED',{documentId:id});return {id};});}
 function readDocument(a,id){const d=db.prepare('SELECT * FROM property_service_documents WHERE id=?').get(id);if(!d)fail(404,'Document not found');access(a,d.case_id);if(a.role==='agent'&&d.owner_id!==a.id)fail(403,'Customer and reviewer evidence is private');audit(a,'property_service.evidence_read',id);return d;}
 function claim(a,c,b,direction){const reference=text(b.reference,'Actual transfer reference',80),p=db.prepare('SELECT * FROM property_service_payments WHERE case_id=?').get(c.id);if(!p||b.amount!==p.amount||!/^[A-Za-z0-9_-]{6,80}$/.test(reference))fail(400,'Exact amount and valid transfer reference required');const refund=direction==='DEBIT',field=refund?'refund_reference':'reference';if(p[field]){if(p[field]===reference)return true;fail(409,'Transfer already recorded');}if(db.prepare('SELECT 1 FROM payment_references WHERE reference=?').get(reference))fail(409,'Reference already used');const kind=refund?'property_service_refund':'property_service_payment';db.prepare('INSERT INTO payment_references VALUES(?,?,?,?,?,?)').run(reference,kind,c.id,p.amount,'KES',now());ledger.recordInsideTransaction({eventType:refund?'REFUND_SETTLED':'PAYMENT_CAPTURED',kind,entityId:c.id,reference,amount:p.amount,currency:'KES',direction,provider:a.provider||'manual',actor:a});db.prepare(`UPDATE property_service_payments SET ${field}=?,status=?,verified_by=?,updated_at=? WHERE case_id=?`).run(reference,refund?'refunded':'paid',a.id,now(),c.id);return false;}
 function action(a,id,name,b){return tx(()=>{
 const c=access(a,id),d=c.data;const owner=()=>{role(a,'agent','admin');if(a.role!=='admin'&&a.id!==c.agent_id)fail(403,'Owning agent required');};const customer=()=>{role(a,'customer');if(a.id!==c.customer_id)fail(403,'Customer required');};const admin=()=>role(a,'admin');const state=(...s)=>{if(!s.includes(c.status)||expired(c))fail(409,'This action is not available in the current case state');};
 // Transfer retries bind to immutable references, independently of UI version.
 if(name==='verify'||name==='refund'){admin();const p=db.prepare('SELECT * FROM property_service_payments WHERE case_id=?').get(id),field=name==='verify'?'reference':'refund_reference';if(p?.[field]){if(p[field]!==b.reference||p.amount!==b.amount)fail(409,'Transfer already recorded');return {...get(a,id),duplicate:true};}}
 if(b.version!==c.version)fail(409,'Case changed; refresh before continuing');
 switch(name){
 case 'confirm':owner();state('REQUESTED');if(c.kind!=='remote')fail(409,'Remote request required');current(c);calendar(c);d.agentConfirmed=true;break;
 case 'quote':admin();state('REQUESTED','QUOTED');current(c);if(c.kind==='remote'){if(!d.agentConfirmed||d.startAt<=now())fail(409,'Agent must confirm a future session first');calendar(c);}d.quote={amountKES:integer(b.amountKES,1,10000000,'Service fee'),scope:text(b.scope,'Scope and deliverables',4000),dueAt:instant(b.dueAt),cancellation:'Full refund before work starts. Operations may cancel an undelivered service for a full refund.',currency:'KES',quotedAt:now(),quotedBy:a.id};if(d.quote.dueAt<=now())fail(400,'Future delivery deadline required');d.expiresAt=new Date(Math.min(Date.now()+24*3600000,c.kind==='remote'?Date.parse(d.startAt):Infinity)).toISOString();c.status='QUOTED';break;
 case 'accept':customer();state('QUOTED');current(c);if(b.acceptTerms!==true)fail(400,'Accept the displayed fee, scope and refund terms');if(c.kind==='remote')calendar(c);d.acceptedAt=now();d.expiresAt=new Date(Math.min(Date.now()+30*60000,c.kind==='remote'?Date.parse(d.startAt):Infinity)).toISOString();db.prepare("INSERT INTO property_service_payments VALUES(?,?,'pending',NULL,NULL,NULL,?)").run(id,d.quote.amountKES,now());c.status='PAYABLE';break;
 case 'verify':admin();state('PAYABLE');current(c);if(c.kind==='remote')calendar(c);claim(a,c,b,'CREDIT');c.status='CONFIRMED';break;
 case 'assign':admin();state('CONFIRMED','IN_PROGRESS');if(c.kind!=='diligence')fail(409,'Due diligence case required');if(!db.prepare("SELECT id FROM users WHERE id=? AND role='admin'").get(b.reviewerId))fail(400,'Assign an operations reviewer account');if(b.reviewerId===c.agent_id)fail(409,'Property agent cannot review their own supply');delete d.reportDraft;d.reviewerId=b.reviewerId;d.reviewEvidence=text(b.qualifications,'Reviewer competence and conflict-of-interest assessment',2000);break;
 case 'room':owner();state('CONFIRMED');if(c.kind!=='remote')fail(409,'Remote case required');d.room={url:providerURL(a,b.url),provider:text(b.provider,'Provider name',100),privacy:text(b.privacy,'Access controls and recording settings',1500)};if(b.accessControlled!==true||b.recordingDisabled!==true)fail(400,'Confirm participant-only access and recording disabled by default');break;
 case 'consent':if(c.kind!=='remote'||!['CONFIRMED','IN_PROGRESS','COMPLETED'].includes(c.status))fail(409,'Confirmed remote case required');if(a.id!==c.customer_id&&a.id!==c.agent_id)fail(403,'Only the two participants can consent');if(typeof b.allow!=='boolean')fail(400,'Explicit recording choice required');d.consents||={};d.consents[a.id]={allow:b.allow,at:now()};if(!b.allow){delete d.recording;d.recordingRemovalRequired=true;}break;
 case 'start':state('CONFIRMED');current(c);if(c.kind==='remote'){owner();if(!d.room||Date.now()<Date.parse(d.startAt)-15*60000||Date.now()>Date.parse(d.endAt))fail(409,'Configure a room and start within the session window');calendar(c);d.recordingAuthorizedAtStart=Boolean(d.consents?.[c.customer_id]?.allow&&d.consents?.[c.agent_id]?.allow);}else{admin();if(d.reviewerId!==a.id)fail(403,'Assigned reviewer required');}c.status='IN_PROGRESS';d.startedAt=now();break;
 case 'complete':owner();state('IN_PROGRESS');if(c.kind!=='remote')fail(409,'Use a reviewed report for due diligence');d.summary={text:text(b.summary,'Agent-authored tour summary',6000),authorId:a.id,createdAt:now(),source:'agent'};d.attendance=text(b.attendance,'Attendance and viewing outcome',1500);c.status='COMPLETED';break;
 case 'recording':owner();state('COMPLETED');if(c.kind!=='remote'||!d.recordingAuthorizedAtStart||!d.consents?.[c.customer_id]?.allow||!d.consents?.[c.agent_id]?.allow)fail(409,'Both participants must currently consent');if(b.accessControlled!==true)fail(400,'Confirm provider participant-only playback');d.recording={url:providerURL(a,b.url),expiresAt:instant(b.expiresAt)};if(d.recording.expiresAt<=now()||Date.parse(d.recording.expiresAt)>Date.now()+30*86400000)fail(400,'Recording retention must be at most 30 days');d.recordingRemovalRequired=false;break;
 case 'report':admin();state('IN_PROGRESS');if(c.kind!=='diligence'||d.reviewerId!==a.id)fail(403,'Assigned due diligence reviewer required');if(!Array.isArray(b.findings)||b.findings.length<1||b.findings.length>30)fail(400,'Provide 1–30 evidence-backed findings');d.reportDraft={findings:b.findings.map(f=>{if(!f||typeof f!=='object'||Array.isArray(f))fail(400,'Each finding must be an object');const documentId=text(f.documentId,'Evidence document ID',100);if(!db.prepare('SELECT id FROM property_service_documents WHERE id=? AND case_id=?').get(documentId,id))fail(400,'Finding evidence must belong to this case');if(!['CLEAR','CONCERN','UNVERIFIED'].includes(f.result))fail(400,'Use a finding result');return {topic:text(f.topic,'Finding topic',200),result:f.result,detail:text(f.detail,'Finding rationale',3000),documentId};}),limitations:text(b.limitations,'Limitations and unresolved checks',4000),summary:text(b.summary,'Report summary',6000),authorId:a.id,createdAt:now()};break;
 case 'release':admin();state('IN_PROGRESS');if(c.kind!=='diligence'||!d.reportDraft)fail(409,'Draft report required');if(a.id===d.reportDraft.authorId||a.id===c.agent_id)fail(403,'A second independent operations reviewer must release the report');d.report={...d.reportDraft,releasedBy:a.id,releasedAt:now(),reviewNote:text(b.reviewNote,'Independent report review',2000),notice:'Evidence review, not a title guarantee or legal clearance. Consult a qualified professional for the transaction.'};delete d.reportDraft;c.status='COMPLETED';break;
 case 'question':state('CONFIRMED','IN_PROGRESS','COMPLETED');if(d.questions.length>=100)fail(409,'Question limit reached');d.questions.push({id:randomUUID(),authorId:a.id,text:text(b.text,'Question or answer',2000),at:now()});break;
 case 'contact':customer();state('COMPLETED');if(typeof b.authorized!=='boolean')fail(400,'Explicit contact choice required');d.contact=b.authorized?{authorized:true,channel:text(b.channel,'Customer-chosen contact channel',200),message:text(b.message,'Instructions to the agent',1000),at:now()}:{authorized:false,at:now()};break;
 case 'negotiate':state('COMPLETED');if(!d.contact?.authorized)fail(409,'Customer must authorize agent contact first');if(d.negotiation.length>=100||['AGREED','CLOSED'].includes(d.deal?.status))fail(409,'Negotiation is closed');d.negotiation.push({id:randomUUID(),authorId:a.id,text:text(b.text,'Offer or negotiation note',2000),at:now()});d.deal={status:'NEGOTIATING'};break;
 case 'agreement':customer();state('COMPLETED');if(!d.contact?.authorized||!d.negotiation.length||d.deal?.status!=='NEGOTIATING')fail(409,'An active authorized negotiation is required');if(!['rent','buy'].includes(b.transaction)||b.confirmOutcome!==true)fail(400,'Confirm the recorded rent/buy outcome');const evidence=db.prepare('SELECT id FROM property_service_documents WHERE id=? AND case_id=? AND owner_id=?').get(b.documentId,id,a.id);if(!evidence)fail(400,'Upload your agreement evidence to this case first');d.deal={status:'AGREED',transaction:b.transaction,documentId:evidence.id,notes:text(b.notes,'Agreement outcome',2000),recordedBy:a.id,at:now(),notice:'Customer-reported agreement; no ownership transfer or contract execution performed by Ride2View'};break;
 case 'close':customer();state('COMPLETED');if(d.deal?.status==='AGREED')fail(409,'Recorded agreement is immutable');d.deal={status:'CLOSED',reason:text(b.reason,'Reason',1000),at:now()};break;
 case 'cancel':if(a.role!=='admin'&&a.id!==c.customer_id&&a.id!==c.agent_id)fail(403,'Case participant required');state('REQUESTED','QUOTED','PAYABLE','CONFIRMED','IN_PROGRESS');if(c.status==='IN_PROGRESS'&&a.role!=='admin')fail(409,'Contact operations for interrupted service recovery');d.cancellation={reason:text(b.reason,'Cancellation reason',1000),at:now(),actorId:a.id};db.prepare("UPDATE property_service_payments SET status=CASE WHEN status='paid' THEN 'refund_pending' ELSE 'cancelled' END,updated_at=? WHERE case_id=?").run(now(),id);delete d.room;delete d.recording;c.status='CANCELLED';break;
 case 'refund':admin();if(!a.provider&&db.prepare("SELECT 1 FROM operations_refunds WHERE kind='service' AND target_id=? AND status!='CONFIRMED'").get(id))fail(409,'External refund is pending; reconcile it first');if(db.prepare('SELECT status FROM property_service_payments WHERE case_id=?').get(id)?.status!=='refund_pending')fail(409,'No pending refund');claim(a,c,b,'DEBIT');break;
 default:fail(404,'Unknown service action');
 }
 return save(a,c,name.toUpperCase());
 });}
 function link(a,id,kind){const c=access(a,id),d=c.data;if(a.id!==c.customer_id&&a.id!==c.agent_id)fail(403,'Session participants only');let url;if(kind==='room'){if(!['CONFIRMED','IN_PROGRESS'].includes(c.status)||Date.now()<Date.parse(d.startAt)-15*60000||Date.now()>Date.parse(d.endAt))fail(409,'Session is outside its access window');current(c);url=d.room?.url;}else if(kind==='recording'){if(c.status!=='COMPLETED'||!d.consents?.[c.customer_id]?.allow||!d.consents?.[c.agent_id]?.allow||!d.recording||d.recording.expiresAt<=now())fail(409,'Recording unavailable or consent withdrawn');url=d.recording.url;}if(!url)fail(409,'Provider link has not been configured');providerURL(a,url);audit(a,'property_service.'+kind+'_accessed',id);return {url};}
 return {create,get,list,action,configuration,document,readDocument,link};
}
module.exports={createPropertyServices};
