const {randomUUID,randomInt,createHash,timingSafeEqual}=require('node:crypto');
const {assertCustomer,assertDriver,busy}=require('../onboarding/eligibility');
const {createLedgerAuthority}=require('../../payments/ledger/ledger-authority');
const now=()=>new Date().toISOString();
function fail(status,message){throw Object.assign(new Error(message),{status});}
function text(v,label,max=200){if(typeof v!=='string'||!v.trim()||v.length>max)fail(400,label+' is required');return v.trim();}
function integer(v,min,max,label){if(!Number.isSafeInteger(v)||v<min||v>max)fail(400,`${label} must be an integer between ${min} and ${max}`);return v;}
function createRideAuthority({db,audit=()=>{},notify=()=>{}}){
 const ledger=createLedgerAuthority({db,audit});
 function tx(fn){db.exec('BEGIN IMMEDIATE');try{const r=fn();db.exec('COMMIT');return r;}catch(e){db.exec('ROLLBACK');throw e;}}
 function role(a,...roles){if(!a)fail(401,'Sign in to continue');if(!roles.includes(a.role))fail(403,'This action is not permitted for this account');}
 function event(a,id,type,data={}){db.prepare('INSERT INTO ride2go_events VALUES(?,?,?,?,?,?)').run(randomUUID(),id,type,a?.id||null,JSON.stringify(data),now());audit(a,'ride2go.'+type.toLowerCase(),id,data);}
 function raw(id){const r=db.prepare('SELECT * FROM ride2go_trips WHERE id=?').get(id);if(!r)fail(404,'Ride not found');return r;}
 function access(a,id){role(a,'customer','driver','admin');const r=raw(id);const assigned=a.role==='driver'&&db.prepare("SELECT 1 FROM ride2go_assignments WHERE trip_id=? AND driver_id=? AND status IN ('OFFERED','ASSIGNED','ARRIVED','IN_PROGRESS','COMPLETED') AND (lease_expires_at IS NULL OR lease_expires_at>?)").get(id,a.id,now());if(a.role!=='admin'&&!(a.role==='customer'&&r.customer_id===a.id)&&!assigned)fail(403,'Ride belongs to another account');return r;}
 function version(r,data){if(data.version!==r.version)fail(409,'Ride changed; refresh before continuing');}
 function policy(a,data){if(data===undefined){const r=db.prepare('SELECT * FROM ride2go_policies ORDER BY version DESC LIMIT 1').get();return r?{version:r.version,policy:JSON.parse(r.policy)}:{version:null,policy:null,reason:'Operations must configure Ride2Go fares before quotes are available'};}role(a,'admin');const baseKES={};for(const tier of ['general','women','students','vip'])baseKES[tier]=integer(data.baseKES?.[tier],1,100000,'Tier base');const p={label:text(data.label,'Pricing policy label',100),baseKES,perKmKES:integer(data.perKmKES,0,1000,'Distance rate'),returnPercent:integer(data.returnPercent,0,100,'Return percentage'),waitingKESPerTwoMinutes:integer(data.waitingKESPerTwoMinutes,0,1000,'Waiting rate'),waitingGraceMinutes:integer(data.waitingGraceMinutes,0,120,'Waiting grace'),cancellation:'Full refund before trip start; operations recovery after start',routeMode:'Operations-reviewed estimate; no live maps or GPS',taxMode:'Fiscal integration pending; no VAT invoice issued'};return tx(()=>{const v=(policy().version||0)+1;db.prepare('INSERT INTO ride2go_policies VALUES(?,?,?,?)').run(v,JSON.stringify(p),a.id,now());audit(a,'ride2go.policy_published',String(v),p);return {version:v,policy:p};});}
 function create(a,data){role(a,'customer');const key=text(data.idempotencyKey,'Idempotency key',128);const plan={pickup:text(data.pickup,'Pickup',300),destination:text(data.destination,'Destination',300),phone:text(data.phone,'Contact phone',40),tier:data.tier,passengers:integer(data.passengers,1,4,'Passengers'),returnJourney:data.returnJourney};if(!['general','women','students','vip'].includes(plan.tier)||typeof plan.returnJourney!=='boolean')fail(400,'Valid tier and return choice required');if(typeof data.scheduledAt!=='string'||!/(Z|[+-]\d\d:\d\d)$/.test(data.scheduledAt)||!Number.isFinite(Date.parse(data.scheduledAt))||Date.parse(data.scheduledAt)<=Date.now()||Date.parse(data.scheduledAt)>Date.now()+30*86400000)fail(400,'Schedule a future ride within 30 days with explicit UTC offset');plan.scheduledAt=new Date(data.scheduledAt).toISOString();assertCustomer(db,a.id,plan.tier,plan.passengers,plan.scheduledAt);
 return tx(()=>{expireInside();const prior=db.prepare('SELECT * FROM ride2go_trips WHERE customer_id=? AND idempotency_key=?').get(a.id,key);if(prior){if(prior.plan!==JSON.stringify(plan))fail(409,'Idempotency key was used for another ride');return {...get(a,prior.id),duplicate:true};}const id=randomUUID(),time=now();db.prepare("INSERT INTO ride2go_trips(id,customer_id,plan,status,idempotency_key,created_at,updated_at) VALUES(?,?,?,'REQUESTED',?,?,?)").run(id,a.id,JSON.stringify(plan),key,time,time);event(a,id,'REQUESTED');notify(a.id,'Ride2Go request saved. Operations will review the route before quoting.');return get(a,id);});}
 function quote(a,id,data){role(a,'admin');return tx(()=>{expireInside();const r=access(a,id);version(r,data);if(!['REQUESTED','QUOTED'].includes(r.status))fail(409,'Only unaccepted requests can be quoted');const current=policy();if(!current.policy)fail(409,'Configure Ride2Go pricing before quoting');const p=current.policy,plan=JSON.parse(r.plan);const route={distanceMetres:integer(data.distanceMetres,0,1000000,'Reviewed distance'),minutes:integer(data.minutes,1,1440,'Reviewed duration'),waitingMinutes:integer(data.waitingMinutes??0,0,480,'Waiting estimate'),evidenceRef:text(data.evidenceRef,'Reviewed route evidence',512)};const baseMinor=p.baseKES[plan.tier]*100,distanceMinor=Math.ceil(route.distanceMetres*p.perKmKES/10),returnMinor=plan.returnJourney?p.baseKES[plan.tier]*p.returnPercent:0,waitingMinor=Math.ceil(Math.max(0,route.waitingMinutes-p.waitingGraceMinutes)/2)*p.waitingKESPerTwoMinutes*100;const totalKES=Math.ceil((baseMinor+distanceMinor+returnMinor+waitingMinor)/100),q={currency:'KES',policyVersion:current.version,policy:p,route,baseMinor,distanceMinor,returnMinor,waitingMinor,totalKES,roundingMinor:totalKES*100-baseMinor-distanceMinor-returnMinor-waitingMinor};const expires=new Date(Math.min(Date.now()+15*60000,Date.parse(plan.scheduledAt))).toISOString();db.prepare("UPDATE ride2go_trips SET status='QUOTED',quote=?,expires_at=?,version=version+1,updated_at=? WHERE id=?").run(JSON.stringify(q),expires,now(),id);event(a,id,'QUOTED',{amount:totalKES,policyVersion:current.version,evidenceRef:route.evidenceRef});notify(r.customer_id,'Your Ride2Go quote is ready for review.');return get(a,id);});}
 function accept(a,id,data){role(a,'customer');return tx(()=>{expireInside();const r=access(a,id);version(r,data);if(r.status!=='QUOTED'||r.expires_at<=now())fail(409,'A current quote is required');if(data.acceptPolicy!==true)fail(400,'Accept the displayed pricing and cancellation policy');const plan=JSON.parse(r.plan);assertCustomer(db,r.customer_id,plan.tier,plan.passengers,plan.scheduledAt);const q=JSON.parse(r.quote),time=now(),paymentId=randomUUID();db.prepare("INSERT INTO ride2go_payments VALUES(?,?,?,'pending',NULL,NULL,NULL)").run(paymentId,id,q.totalKES);const code=String(randomInt(100000,1000000));db.prepare('INSERT INTO ride2go_start_codes VALUES(?,?,0)').run(id,code);db.prepare("UPDATE ride2go_trips SET status='PAYABLE',expires_at=?,version=version+1,updated_at=? WHERE id=?").run(new Date(Math.min(Date.now()+30*60000,Date.parse(plan.scheduledAt))).toISOString(),time,id);event(a,id,'POLICY_ACCEPTED',{policyVersion:q.policyVersion,totalKES:q.totalKES});return get(a,id);});}
 function verify(a,id,data){role(a,'admin');return tx(()=>captureInside(a,id,data));}
 function captureInside(a,id,data){const r=raw(id),p=db.prepare('SELECT * FROM ride2go_payments WHERE trip_id=?').get(id);if(!p)fail(404,'Ride payment not found');const reference=text(data.reference,'Received payment reference',80);if(!/^[A-Za-z0-9_-]{6,80}$/.test(reference)||data.amount!==p.amount)fail(400,'Valid reference and exact received amount required');if(p.status==='paid'){if(p.reference===reference)return {...get(a,id),duplicate:true};fail(409,'Ride payment already verified');}if(r.status!=='PAYABLE'||p.status!=='pending'||r.expires_at<=now())fail(409,'Ride is no longer payable');const plan=JSON.parse(r.plan);assertCustomer(db,r.customer_id,plan.tier,plan.passengers,plan.scheduledAt);if(db.prepare('SELECT 1 FROM payment_references WHERE reference=?').get(reference))fail(409,'Payment reference already used');const time=now();db.prepare('INSERT INTO payment_references VALUES(?,?,?,?,?,?)').run(reference,'ride2go_payment',p.id,p.amount,'KES',time);ledger.recordInsideTransaction({eventType:'PAYMENT_CAPTURED',kind:'ride2go_payment',entityId:p.id,reference,amount:p.amount,currency:'KES',direction:'CREDIT',provider:a.provider||'manual',actor:a});db.prepare("UPDATE ride2go_payments SET status='paid',reference=?,verified_by=?,verified_at=? WHERE id=?").run(reference,a.id,time,p.id);db.prepare("UPDATE ride2go_trips SET status='CONFIRMED',expires_at=NULL,version=version+1,updated_at=? WHERE id=?").run(time,id);event(a,id,'PAYMENT_VERIFIED',{reference,amount:p.amount});notify(r.customer_id,'Ride2Go payment verified. Driver assignment is pending.');return get(a,id);}
 function expireOffers(){db.prepare("UPDATE ride2go_assignments SET status='EXPIRED',updated_at=? WHERE status='OFFERED' AND lease_expires_at<=?").run(now(),now());}
 function offer(a,id,data){role(a,'admin');const key=text(data.idempotencyKey,'Dispatch idempotency key',128);return tx(()=>{expireOffers();const r=access(a,id),p=db.prepare('SELECT status FROM ride2go_payments WHERE trip_id=?').get(id);const prior=db.prepare('SELECT * FROM ride2go_assignments WHERE idempotency_key=?').get(key);if(prior){if(prior.trip_id!==id||prior.driver_id!==data.driverId)fail(409,'Dispatch key belongs to another offer');return {assignment:prior,duplicate:true};}if(r.status!=='CONFIRMED'||p?.status!=='paid')fail(409,'Only paid confirmed rides can be offered');const plan=JSON.parse(r.plan);assertCustomer(db,r.customer_id,plan.tier,plan.passengers,plan.scheduledAt);assertDriver(db,data.driverId,plan.tier,plan.passengers,{atTime:plan.scheduledAt});if(busy(db,data.driverId,{tripId:id})||db.prepare("SELECT 1 FROM ride2go_assignments WHERE trip_id=? AND status IN ('OFFERED','ASSIGNED','ARRIVED','IN_PROGRESS')").get(id))fail(409,'Driver or ride already has an active assignment');const assignmentId=randomUUID(),time=now();db.prepare("INSERT INTO ride2go_assignments VALUES(?,?,?,'OFFERED',?,?,?,?)").run(assignmentId,id,data.driverId,new Date(Date.now()+60000).toISOString(),key,time,time);event(a,id,'DRIVER_OFFERED',{assignmentId,driverId:data.driverId});notify(data.driverId,'A Ride2Go trip awaits your response.');return {assignment:db.prepare('SELECT * FROM ride2go_assignments WHERE id=?').get(assignmentId)};});}
 function respond(a,id,data){role(a,'driver');return tx(()=>{expireOffers();const assignment=db.prepare('SELECT * FROM ride2go_assignments WHERE id=?').get(id);if(!assignment)fail(404,'Ride offer not found');if(assignment.driver_id!==a.id)fail(403,'Offer belongs to another driver');if(!['ACCEPTED','REJECTED'].includes(data.decision))fail(400,'Choose ACCEPTED or REJECTED');if(assignment.status==='ASSIGNED'&&data.decision==='ACCEPTED'||assignment.status==='REJECTED'&&data.decision==='REJECTED')return {assignment,duplicate:true};if(assignment.status!=='OFFERED')fail(409,'Offer is no longer available');const r=raw(assignment.trip_id);if(r.status!=='CONFIRMED')fail(409,'Ride is no longer eligible');if(data.decision==='REJECTED'){db.prepare("UPDATE ride2go_assignments SET status='REJECTED',lease_expires_at=NULL,updated_at=? WHERE id=?").run(now(),id);event(a,r.id,'DRIVER_REJECTED',{assignmentId:id});return {success:true};}const plan=JSON.parse(r.plan);assertCustomer(db,r.customer_id,plan.tier,plan.passengers,plan.scheduledAt);assertDriver(db,a.id,plan.tier,plan.passengers,{atTime:plan.scheduledAt});if(busy(db,a.id,{tripId:r.id}))fail(409,'Driver has another active assignment');db.prepare("UPDATE ride2go_assignments SET status='ASSIGNED',lease_expires_at=NULL,updated_at=? WHERE id=?").run(now(),id);db.prepare("UPDATE ride2go_trips SET status='ASSIGNED',driver_id=?,version=version+1,updated_at=? WHERE id=?").run(a.id,now(),r.id);event(a,r.id,'DRIVER_ASSIGNED',{driverId:a.id});notify(r.customer_id,'Your Ride2Go driver has accepted.');return get(a,r.id);});}
 function transition(a,id,action,data){role(a,'driver');const result=tx(()=>{const r=access(a,id);if(r.driver_id!==a.id)fail(403,'Only the assigned driver can operate this ride');version(r,data);const plan=JSON.parse(r.plan);const next={arrive:['ASSIGNED','ARRIVED'],start:['ARRIVED','IN_PROGRESS'],complete:['IN_PROGRESS','COMPLETED']}[action];if(!next||r.status!==next[0])fail(409,'Invalid ride transition');if(action!=='complete'){assertCustomer(db,r.customer_id,plan.tier,plan.passengers,plan.scheduledAt);assertDriver(db,a.id,plan.tier,plan.passengers,{requireOnline:false,atTime:plan.scheduledAt});}
 if(action==='start'){const c=db.prepare('SELECT * FROM ride2go_start_codes WHERE trip_id=?').get(id);if(!c||c.attempts>=5)fail(409,'Pickup code locked; contact operations');const candidate=String(data.pickupCode||'');const stored=createHash('sha256').update(c.code).digest(),supplied=createHash('sha256').update(candidate).digest();if(!/^\d{6}$/.test(candidate)||!timingSafeEqual(stored,supplied)){db.prepare('UPDATE ride2go_start_codes SET attempts=attempts+1 WHERE trip_id=?').run(id);event(a,id,'PICKUP_CODE_REJECTED');return {error:'Invalid pickup code'};}db.prepare('DELETE FROM ride2go_start_codes WHERE trip_id=?').run(id);}
 db.prepare('UPDATE ride2go_trips SET status=?,version=version+1,updated_at=? WHERE id=?').run(next[1],now(),id);db.prepare("UPDATE ride2go_assignments SET status=?,updated_at=? WHERE trip_id=? AND status IN ('ASSIGNED','ARRIVED','IN_PROGRESS')").run(next[1],now(),id);event(a,id,next[1]);notify(r.customer_id,'Ride2Go trip: '+next[1]);return get(a,id);});if(result.error)fail(400,result.error);return result;}
 function resetCode(a,id,data){role(a,'admin');return tx(()=>{const r=access(a,id);version(r,data);if(!['ASSIGNED','ARRIVED'].includes(r.status))fail(409,'Only an assigned unstarted ride can receive a new pickup code');const reason=text(data.reason,'Pickup code recovery evidence',1000);db.prepare('UPDATE ride2go_start_codes SET code=?,attempts=0 WHERE trip_id=?').run(String(randomInt(100000,1000000)),id);event(a,id,'PICKUP_CODE_REISSUED',{reason});notify(r.customer_id,'Operations reissued your private pickup code. Refresh before sharing it with your driver.');return get(a,id);});}
 function cancelInside(a,r,status,reason){const p=db.prepare('SELECT * FROM ride2go_payments WHERE trip_id=?').get(r.id);if(p?.status==='paid'){db.prepare("UPDATE ride2go_payments SET status='refund_pending' WHERE id=?").run(p.id);db.prepare("INSERT INTO ride2go_refunds(trip_id,amount,status) VALUES(?,?,'PENDING')").run(r.id,p.amount);}else if(p)db.prepare("UPDATE ride2go_payments SET status='cancelled' WHERE id=?").run(p.id);db.prepare("UPDATE ride2go_assignments SET status='CANCELLED',lease_expires_at=NULL,updated_at=? WHERE trip_id=? AND status IN ('OFFERED','ASSIGNED','ARRIVED')").run(now(),r.id);db.prepare('DELETE FROM ride2go_start_codes WHERE trip_id=?').run(r.id);db.prepare('UPDATE ride2go_trips SET status=?,version=version+1,updated_at=? WHERE id=?').run(status,now(),r.id);event(a,r.id,status,{reason});notify(r.customer_id,'Ride2Go '+status.toLowerCase()+'. Review any pending refund.');}
 function cancel(a,id,data){role(a,'customer','admin');return tx(()=>{expireInside();const r=access(a,id);version(r,data);if(['CANCELLED','EXPIRED'].includes(r.status))return get(a,id);if(['IN_PROGRESS','COMPLETED'].includes(r.status))fail(409,'Trip has started; contact operations for recovery');cancelInside(a,r,'CANCELLED',text(data.reason,'Cancellation reason',1000));return get(a,id);});}
 function refund(a,id,data){role(a,'admin');if(!a.provider&&db.prepare("SELECT 1 FROM operations_refunds WHERE kind='ride2go' AND target_id=? AND status!='CONFIRMED'").get(id))fail(409,'External refund is pending; reconcile it first');return tx(()=>{const r=access(a,id),p=db.prepare('SELECT * FROM ride2go_refunds WHERE trip_id=?').get(id);if(!p)fail(404,'Ride refund not found');const ref=text(data.reference,'Actual refund transaction reference',80);if(!/^[A-Za-z0-9_-]{6,80}$/.test(ref)||data.amount!==p.amount)fail(400,'Valid reference and exact amount required');if(p.status==='REFUNDED'){if(p.reference!==ref)fail(409,'Refund already settled');return {...get(a,id),duplicate:true};}if(db.prepare('SELECT 1 FROM payment_references WHERE reference=?').get(ref))fail(409,'Reference already used');db.prepare('INSERT INTO payment_references VALUES(?,?,?,?,?,?)').run(ref,'ride2go_refund',id,p.amount,'KES',now());ledger.recordInsideTransaction({eventType:'REFUND_SETTLED',kind:'ride2go_refund',entityId:id,reference:ref,amount:p.amount,currency:'KES',direction:'DEBIT',provider:a.provider||'manual',actor:a});db.prepare("UPDATE ride2go_refunds SET status='REFUNDED',reference=?,verified_by=?,verified_at=? WHERE trip_id=?").run(ref,a.id,now(),id);db.prepare("UPDATE ride2go_payments SET status='refunded' WHERE trip_id=?").run(id);event(a,id,'REFUND_SETTLED',{reference:ref,amount:p.amount});return get(a,id);});}
 function expireInside(){expireOffers();for(const r of db.prepare("SELECT * FROM ride2go_trips WHERE status IN ('REQUESTED','QUOTED','PAYABLE')").all()){const plan=JSON.parse(r.plan);if(r.expires_at&&r.expires_at<=now()||plan.scheduledAt<=now())cancelInside(null,r,'EXPIRED','Quote, payment or scheduled departure deadline expired');}}
 function get(a,id){const r=access(a,id),plan=JSON.parse(r.plan),payment=db.prepare('SELECT id,amount,status,reference FROM ride2go_payments WHERE trip_id=?').get(id)||null;const data={...r,plan,quote:r.quote?JSON.parse(r.quote):null,payment,refund:db.prepare('SELECT amount,status,reference FROM ride2go_refunds WHERE trip_id=?').get(id)||null,assignment:db.prepare('SELECT id,driver_id,status,lease_expires_at FROM ride2go_assignments WHERE trip_id=? ORDER BY created_at DESC,rowid DESC LIMIT 1').get(id)||null,events:db.prepare('SELECT event,details,created_at FROM ride2go_events WHERE trip_id=? ORDER BY created_at').all(id).map(e=>({...e,details:JSON.parse(e.details)}))};if(a.role==='customer')data.pickupCode=db.prepare('SELECT code FROM ride2go_start_codes WHERE trip_id=?').get(id)?.code||null;if(a.role==='driver'){if(data.assignment?.status==='OFFERED')delete data.plan.phone;delete data.payment;delete data.refund;delete data.quote;delete data.idempotency_key;delete data.events;}if(r.driver_id){const driver=db.prepare('SELECT name FROM users WHERE id=?').get(r.driver_id),p=db.prepare('SELECT payload FROM driver_profiles WHERE user_id=?').get(r.driver_id);const vehicle=p?JSON.parse(p.payload):{};data.driver={name:driver.name,plate:vehicle.plate,make:vehicle.make,model:vehicle.model};}return data;}
 function read(a,id){tx(expireInside);return get(a,id);}
 function list(a){role(a,'customer','driver','admin');tx(expireInside);return db.prepare('SELECT id FROM ride2go_trips ORDER BY created_at DESC').all().flatMap(({id})=>{try{return [get(a,id)];}catch(e){if(e.status===403)return [];throw e;}});}
 return {policy,create,quote,accept,verify,offer,respond,transition,cancel,refund,resetCode,get:read,list};
}
module.exports={createRideAuthority};
