const fail=(status,message)=>{throw Object.assign(new Error(message),{status});};
const day=86400000;
const median=a=>{const s=[...a].sort((a,b)=>a-b),i=Math.floor(s.length/2);return s.length?s.length%2?s[i]:(s[i-1]+s[i])/2:null;};
function createIntelligence({db,supply}){
 let collectionErrors=0;
 function access(actor,kind){if(!actor)fail(401,'Sign in to continue');if(!['security','market','sales'].includes(kind))fail(400,'Unknown intelligence scope');if(actor.role!==(kind==='sales'?'agent':'admin'))fail(403,'Intelligence is not available for this account');}
 function recordFailure(status,path){const kind=path==='/api/auth/login'&&status===401?'AUTH_FAILURE':status===403?'ACCESS_DENIED':status===429?'RATE_LIMITED':status>=500?'SERVER_ERROR':null;if(!kind)return;try{const now=Date.now(),minute=new Date(Math.floor(now/60000)*60000).toISOString();db.prepare('INSERT INTO security_signal_buckets VALUES(?,?,1) ON CONFLICT(minute,kind) DO UPDATE SET count=count+1').run(minute,kind);db.prepare('DELETE FROM security_signal_buckets WHERE minute<?').run(new Date(now-30*day).toISOString());}catch{collectionErrors++;}}
 function security(){const now=Date.now(),from=new Date(Math.floor((now-day)/60000)*60000).toISOString();const buckets=db.prepare('SELECT minute,kind,count FROM security_signal_buckets WHERE minute>=? AND minute<=? ORDER BY minute,kind').all(from,new Date(now).toISOString()),counts={AUTH_FAILURE:0,ACCESS_DENIED:0,RATE_LIMITED:0,SERVER_ERROR:0};for(const b of buckets)counts[b.kind]+=b.count;const sessions=db.prepare('SELECT user_id id,count(*) activeSessions FROM sessions WHERE expires>? GROUP BY user_id HAVING count(*)>10 ORDER BY activeSessions DESC,user_id').all(now);return {from,generatedAt:new Date(now).toISOString(),startedAt:db.prepare('SELECT started_at FROM security_collection_metadata WHERE id=1').get().started_at,counts,sessionAccounts:sessions,collectionErrors,thresholds:{authFailures:10,accessDenied:10,rateLimited:1,serverErrors:1,activeSessionsPerAccount:10},limitations:['Request counts are aggregate observations, not proof of an attack or compromise.','Coverage starts at collection installation; the window includes its first whole minute. No historical failures are reconstructed.','No IP addresses, credentials, tokens, submitted emails or request bodies are collected. Failures do not identify an attacker.','Session counts include all unexpired sessions, not distinct devices.','Signals are review-only. No account is blocked, session revoked or external scan performed. Collection failures are counted only for this process lifetime.']};}
 function publicRows(){return supply.listPublic().filter(p=>Number.isFinite(p.price)&&p.price>0&&['rent','sale'].includes(p.transactionType)).map(p=>({id:p.id,title:p.title,city:String(p.location?.city||'Unspecified').trim().toLowerCase(),transactionType:p.transactionType,bedrooms:p.property?.bedrooms??null,askingPriceKES:p.price}));}
 function market(){const now=Date.now(),from=new Date(now-30*day).toISOString(),properties=publicRows(),requests=new Map(db.prepare('SELECT listing_id,count(*) n FROM viewing_requests WHERE created_at>=? AND created_at<=? GROUP BY listing_id').all(from,new Date(now).toISOString()).map(r=>[r.listing_id,r.n])),groups=new Map();for(const p of properties){const key=JSON.stringify([p.city,p.transactionType,p.bedrooms]);if(!groups.has(key))groups.set(key,{city:p.city,transactionType:p.transactionType,bedrooms:p.bedrooms,prices:[],viewingRequests:0});const g=groups.get(key);g.prices.push(p.askingPriceKES);g.viewingRequests+=requests.get(p.id)||0;}return {generatedAt:new Date(now).toISOString(),from,scope:'Currently published Ride2View inventory and viewing requests created in the last 30 days for that inventory',currency:'KES',publishedListings:properties.length,groups:[...groups.values()].map(g=>({city:g.city,transactionType:g.transactionType,bedrooms:g.bedrooms,listings:g.prices.length,medianAskingPrice:median(g.prices),minimumAskingPrice:g.prices.reduce((a,b)=>Math.min(a,b),Infinity),maximumAskingPrice:g.prices.reduce((a,b)=>Math.max(a,b),-Infinity),viewingRequests:g.viewingRequests,sampleStrength:g.prices.length<5?'SMALL_SAMPLE':'DESCRIPTIVE_ONLY'})).sort((a,b)=>b.viewingRequests-a.viewingRequests||b.listings-a.listings||JSON.stringify(a).localeCompare(JSON.stringify(b))),limitations:['This is internal marketplace intelligence, not a representative Kenya property-market survey or valuation.','Rent and sale, cities and bedroom counts remain separate. Rental periods are not standardized by this report; confirm listing terms before comparing.','Prices are current asking prices, not completed transaction prices. No trend or appreciation forecast is inferred from a single snapshot.','Demand counts requests, including cancelled/declined requests and repeat customers; they are not unique buyers, purchase intent or completed sales.','Only currently public listings enter these cohorts. Unpublished historical stock and external market data are excluded.']};}
 function salesRows(actor){const now=Date.now();return db.prepare("SELECT p.request_id id,v.listing_id listingId,p.stage,p.updated_at updatedAt,v.status requestStatus FROM property_leads p JOIN viewing_requests v ON v.id=p.request_id JOIN listings l ON l.id=v.listing_id WHERE l.owner_id=? AND p.stage NOT IN ('WON','LOST') ORDER BY p.updated_at,p.request_id").all(actor.id).map(r=>({...r,ageHours:Number.isFinite(Date.parse(r.updatedAt))&&Date.parse(r.updatedAt)<=now?Math.max(0,Math.floor((now-Date.parse(r.updatedAt))/3600000)):null}));}
 function sales(actor){const rows=salesRows(actor),counts={QUALIFIED:0,VIEWED:0,FOLLOW_UP:0,NEGOTIATING:0};for(const r of rows)counts[r.stage]++;return {generatedAt:new Date().toISOString(),openLeads:rows.length,counts,leads:rows,limitations:['Only leads on properties currently owned by this agent are included.','Priority uses recorded stage, elapsed time and request status; it does not predict conversion or infer customer wealth, creditworthiness or sensitive traits.','Closed WON/LOST leads are excluded. Cancelled, declined or expired requests require consent/status review before any follow-up.','No messages are sent and no lead stages, notes, prices or bookings are changed.']};}
 function snapshot(actor,kind){access(actor,kind);db.exec('BEGIN');try{const result=kind==='security'?security():kind==='market'?market():sales(actor);db.exec('COMMIT');return result;}catch(e){db.exec('ROLLBACK');throw e;}}
 function evidence(actor,kind,input={}){access(actor,kind);const offset=input.offset??0;if(!Number.isSafeInteger(offset)||offset<0||offset>1000000)fail(400,'Invalid evidence offset');let records;if(kind==='security'){if(input.category==='sessions')records=security().sessionAccounts;else if(input.category==='signals'){const s=security();records=db.prepare('SELECT minute,kind,count FROM security_signal_buckets WHERE minute>=? AND minute<=? ORDER BY minute DESC,kind').all(s.from,s.generatedAt);}else fail(400,'Unknown security evidence category');}else records=kind==='market'?publicRows().sort((a,b)=>a.id.localeCompare(b.id)):salesRows(actor);return {kind,observedAt:new Date().toISOString(),offset,limit:50,total:records.length,records:records.slice(offset,offset+50)};}
 function routes({path,method,user,body,send}){const m=path.match(/^\/api\/intelligence\/(security|market|sales)\/evidence$/);if(m&&method==='POST'){send(200,evidence(user,m[1],body));return true;}return false;}
 return {snapshot,evidence,recordFailure,routes};
}
module.exports={createIntelligence};
