const {assertCustomer}=require('../mobility/onboarding/eligibility');
const {randomUUID}=require('node:crypto');
const {PILOT_POLICY,validatePolicy,price}=require('./pricing');
const {packageForBooking,stops,confirmPackageInsideTransaction}=require('./hooks');
const {createLedgerAuthority}=require('../payments/ledger/ledger-authority');
const now=()=>new Date().toISOString();
function fail(status,message){throw Object.assign(new Error(message),{status});}
function text(v,label,max=200){if(typeof v!=='string'||!v.trim()||v.length>max)fail(400,label+' is required');return v.trim();}
function createJourneyAuthority({db,supply,audit=()=>{},notify=()=>{},dispatch}){
 const ledger=createLedgerAuthority({db,audit});
 function tx(fn){db.exec('BEGIN IMMEDIATE');try{const r=fn();db.exec('COMMIT');return r;}catch(e){db.exec('ROLLBACK');throw e;}}
 function role(a,...roles){if(!a)fail(401,'Sign in to continue');if(!roles.includes(a.role))fail(403,'This action is not permitted for this account');}
 function event(a,id,type,data={}){db.prepare('INSERT INTO journey_events VALUES(?,?,?,?,?,?)').run(randomUUID(),id,type,a?.id||null,JSON.stringify(data),now());audit(a,'journey.'+type.toLowerCase(),id,data);}
 function raw(id){const j=db.prepare('SELECT * FROM viewing_journeys WHERE id=?').get(id);if(!j)fail(404,'Viewing journey not found');return j;}
 function access(a,id){role(a,'customer','agent','admin','driver');const j=raw(id);const owned=a.role==='agent'&&db.prepare('SELECT 1 FROM journey_stops s JOIN viewing_requests v ON v.id=s.request_id JOIN listings l ON l.id=v.listing_id WHERE s.journey_id=? AND l.owner_id=?').get(id,a.id);const driven=a.role==='driver'&&db.prepare("SELECT 1 FROM dispatch_assignments WHERE booking_id=? AND driver_id=? AND status IN ('OFFERED','ASSIGNED','DRIVER_EN_ROUTE','ARRIVED','TRIP_STARTED','TRIP_COMPLETED')").get(j.master_booking_id,a.id);if(a.role!=='admin'&&!(a.role==='customer'&&j.customer_id===a.id)&&!owned&&!driven)fail(403,'Journey belongs to another account');return j;}
 function version(j,data){if(data.version!==j.version)fail(409,'Journey changed; refresh before continuing');}
 function balance(id){return db.prepare('SELECT COALESCE(SUM(amount),0) amount FROM customer_credit_entries WHERE customer_id=?').get(id).amount;}
 function credit(j,amount,key){if(amount)db.prepare('INSERT INTO customer_credit_entries VALUES(?,?,?,?,?,?)').run(randomUUID(),j.customer_id,j.id,amount,key,now());}
 function policy(a,data){if(data!==undefined){role(a,'admin');const p=validatePolicy(data);return tx(()=>{const v=(db.prepare('SELECT MAX(version) v FROM journey_policies').get().v||0)+1;db.prepare('INSERT INTO journey_policies VALUES(?,?,?,?)').run(v,JSON.stringify(p),a.id,now());audit(a,'journey.policy_published',String(v),p);return {version:v,policy:p};});}const r=db.prepare('SELECT * FROM journey_policies ORDER BY version DESC LIMIT 1').get();return r?{version:r.version,policy:JSON.parse(r.policy)}:{version:0,policy:PILOT_POLICY};}
 function details(a,data){role(a,'customer');const prior=db.prepare('SELECT * FROM customer_details WHERE user_id=?').get(a.id);if(data===undefined)return {details:JSON.parse(prior?.details||'{}'),version:prior?.version||0,preferences:JSON.parse(supply.profile(a).preferences),history:db.prepare('SELECT snapshot,created_at FROM customer_profile_history WHERE user_id=? ORDER BY created_at DESC LIMIT 50').all(a.id).map(h=>({...h,snapshot:JSON.parse(h.snapshot)})),qualifications:db.prepare('SELECT q.request_id,q.snapshot,q.created_at FROM viewing_qualifications q JOIN viewing_requests v ON v.id=q.request_id WHERE v.customer_id=? ORDER BY q.created_at DESC LIMIT 100').all(a.id).map(q=>({...q,snapshot:JSON.parse(q.snapshot)}))};
 if(data.version!==(prior?.version||0))fail(409,'Profile changed; refresh before saving');const d={phone:text(data.phone,'Contact phone',40),pickup:text(data.pickup,'Pickup address',300),preferredContact:data.preferredContact||'phone',accessibilityNotes:String(data.accessibilityNotes||'')};if(!['phone','email','sms','whatsapp'].includes(d.preferredContact)||d.accessibilityNotes.length>1000)fail(400,'Invalid contact preference or accessibility notes');return tx(()=>{db.prepare('INSERT INTO customer_details VALUES(?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET details=excluded.details,version=excluded.version,updated_at=excluded.updated_at').run(a.id,JSON.stringify(d),(prior?.version||0)+1,now());db.prepare('INSERT INTO customer_profile_history VALUES(?,?,?,?)').run(randomUUID(),a.id,JSON.stringify({details:d}),now());audit(a,'customer.details_updated',a.id);return details(a);});}
 function validatePlan(a,data){const p=policy().policy;if(!Array.isArray(data.stops)||data.stops.length<1||data.stops.length>p.maxStops)fail(400,'Choose one to three distinct properties');if(data.stops.some(s=>!s||typeof s!=='object'||Array.isArray(s)))fail(400,'Valid property stops are required');if(new Set(data.stops.map(s=>s.listingId)).size!==data.stops.length)fail(400,'Choose distinct properties');if(!Object.hasOwn(p.baseKES,data.tier))fail(400,'Choose a valid ride tier');assertCustomer(db,a.id,data.tier,data.participants?.length);if(typeof data.returnJourney!=='boolean')fail(400,'Return journey choice required');if(!Array.isArray(data.participants)||!data.participants.length||data.participants.length>p.maxParticipants)fail(400,'Include one to four viewing participants');const participants=data.participants.map(v=>({name:text(v.name,'Participant name',100),relationship:text(v.relationship||'customer','Participant relationship',50)}));if(['women','students'].includes(data.tier)&&participants[0]?.name!==db.prepare('SELECT name FROM users WHERE id=?').get(a.id).name)fail(409,'Protected-tier pilot participant must be the verified account holder');const d=details(a).details;if(!d.phone||!d.pickup)fail(409,'Complete your contact and pickup profile');const plan={stops:data.stops.map(s=>({listingId:text(s.listingId,'Property ID',100),slotId:text(s.slotId,'Slot ID',100)})),tier:data.tier,returnJourney:data.returnJourney,participants,contact:d};validateSlots(plan);qualify(a,plan);return plan;}
 function qualify(a,plan){assertCustomer(db,a.id,plan.tier,plan.participants.length,db.prepare('SELECT start_at FROM property_slots WHERE id=?').get(plan.stops[0].slotId)?.start_at);const preferences=JSON.parse(supply.profile(a).preferences);if(!preferences.city||!preferences.budget||!preferences.goal)fail(409,'Complete city, budget and rent/buy preferences');return plan.stops.map(s=>{const row=supply.listing(s.listingId);if(!supply.visible(row))fail(409,'A property is unavailable or its verification expired');const p=JSON.parse(row.payload);if(preferences.budget<p.price||preferences.city.toLowerCase()!==p.location.city.toLowerCase()||preferences.goal!==(p.transactionType==='sale'?'buy':'rent'))fail(409,'Every property must match your saved city, budget and rent/buy goal');return {preferences,listingPrice:p.price,listingTransactionType:p.transactionType||'rent',status:'QUALIFIED'};});}
 function validateSlots(plan,route,excludeJourney=''){
 let end=null;return plan.stops.map((s,i)=>{const slot=db.prepare('SELECT * FROM property_slots WHERE id=? AND listing_id=? AND enabled=1 AND start_at>?').get(s.slotId,s.listingId,now());if(!slot)fail(409,'Choose enabled future availability for every stop');if(end&&Date.parse(slot.start_at)<Date.parse(end)+(route?.legs[i-1]?.minutes||0)*60000)fail(409,'Slots overlap or do not leave enough transfer time');end=slot.end_at;
 const occupied=db.prepare("SELECT v.id FROM viewing_requests v LEFT JOIN journey_stops js ON js.request_id=v.id WHERE v.listing_id=? AND v.status IN ('REQUESTED','ACCEPTED') AND (js.journey_id IS NULL OR js.journey_id<>?) AND EXISTS(SELECT 1 FROM property_slots ps WHERE ps.id=v.slot_id AND ps.start_at<? AND ps.end_at>?)").get(s.listingId,excludeJourney,slot.end_at,slot.start_at);if(occupied)fail(409,'A property slot is already occupied');
 const owner=supply.listing(s.listingId).owner_id;const conflict=db.prepare("SELECT v.id FROM viewing_requests v JOIN listings l ON l.id=v.listing_id JOIN property_slots ps ON ps.id=v.slot_id LEFT JOIN journey_stops js ON js.request_id=v.id WHERE l.owner_id=? AND v.status='ACCEPTED' AND (js.journey_id IS NULL OR js.journey_id<>?) AND ps.start_at<? AND ps.end_at>?").get(owner,excludeJourney,slot.end_at,slot.start_at);if(conflict)fail(409,'An agent has an overlapping confirmed viewing');
 const reserved=db.prepare("SELECT r.id FROM reservations r LEFT JOIN booking_reservations br ON br.reservation_id=r.id LEFT JOIN journey_stops js ON js.booking_id=br.booking_id WHERE r.resource_id=? AND r.status IN ('HOLD_CREATED','CONFIRMED','ACTIVE','RESCHEDULED') AND (r.hold_expires_at IS NULL OR r.hold_expires_at>?) AND (js.journey_id IS NULL OR js.journey_id<>?) AND r.start_at<? AND r.end_at>?").get(s.listingId,now(),excludeJourney,slot.end_at,slot.start_at);if(reserved)fail(409,'A property reservation conflicts');return slot;});
 }
 function create(a,data){role(a,'customer');if(!Array.isArray(data.participants)||data.participants.some(p=>!p||typeof p.name!=='string'||(p.relationship!==undefined&&typeof p.relationship!=='string')))fail(400,'Valid participants are required');const key=text(data.idempotencyKey,'Idempotency key',128);return tx(()=>{expireInside();const previous=db.prepare('SELECT * FROM viewing_journeys WHERE customer_id=? AND idempotency_key=?').get(a.id,key);if(previous){const p=JSON.parse(previous.plan);if(JSON.stringify(p.stops)!==JSON.stringify(data.stops)||p.tier!==data.tier||p.returnJourney!==data.returnJourney||JSON.stringify(p.participants)!==JSON.stringify(data.participants.map(v=>({name:v.name.trim(),relationship:(v.relationship||'customer').trim()}))))fail(409,'Idempotency key belongs to another plan');return {...get(a,previous.id),duplicate:true};}const plan=validatePlan(a,data),id=randomUUID(),time=now();db.prepare("INSERT INTO viewing_journeys(id,customer_id,status,plan,idempotency_key,created_at,updated_at) VALUES(?,?,'DRAFT',?,?,?,?)").run(id,a.id,JSON.stringify(plan),key,time,time);event(a,id,'CREATED');return get(a,id);});}
 function quote(a,id,data){role(a,'admin');return tx(()=>{const j=access(a,id);version(j,data);if(!['DRAFT','QUOTED'].includes(j.status))fail(409,'Only a draft can receive a new quote');const plan=JSON.parse(j.plan),p=policy(),q={...price(p.policy,plan,data.route),policyVersion:p.version};validateSlots(plan,q.route,id);const expiry=new Date(Math.min(Date.now()+15*60000,Date.parse(db.prepare('SELECT start_at FROM property_slots WHERE id=?').get(plan.stops[0].slotId).start_at))).toISOString();db.prepare("UPDATE viewing_journeys SET status='QUOTED',quote=?,quote_expires_at=?,version=version+1,updated_at=? WHERE id=?").run(JSON.stringify(q),expiry,now(),id);event(a,id,'QUOTED',{policyVersion:p.version,amount:q.totalKES,evidenceRef:q.route.evidenceRef});notify(j.customer_id,'Your reviewed viewing package quote is ready. Review and accept before it expires.');return get(a,id);});}
 function accept(a,id,data){role(a,'customer');return tx(()=>{expireInside();const j=access(a,id);version(j,data);if(j.status!=='QUOTED'||j.quote_expires_at<=now())fail(409,'A current quote is required');if(data.acceptPolicy!==true)fail(400,'Accept the displayed pricing and cancellation policy');const plan=JSON.parse(j.plan),q=JSON.parse(j.quote);const slots=validateSlots(plan,q.route,id),qualified=qualify(a,plan);for(let i=0;i<slots.length;i++){const requestId=randomUUID(),time=now(),s=plan.stops[i];db.prepare("INSERT INTO viewing_requests VALUES(?,?,?,?,?,'REQUESTED',NULL,?,NULL,?,?)").run(requestId,a.id,s.listingId,s.slotId,plan.tier,'package:'+id+':'+i,time,time);db.prepare('INSERT INTO journey_stops(journey_id,position,request_id) VALUES(?,?,?)').run(id,i,requestId);db.prepare("INSERT INTO property_leads VALUES(?,'QUALIFIED','',?)").run(requestId,time);db.prepare('INSERT INTO viewing_qualifications VALUES(?,?,?)').run(requestId,JSON.stringify({...qualified[i],journeyId:id,participantCount:plan.participants.length,policyVersion:q.policyVersion}),time);notify(supply.listing(s.listingId).owner_id,'A package viewing awaits your confirmation.');}
 if(data.useCredits!==undefined&&typeof data.useCredits!=='boolean')fail(400,'Credit choice must be boolean');plan.useCredits=data.useCredits===true;plan.confirmationExpiresAt=new Date(Math.min(Date.now()+24*60*60000,Date.parse(slots[0].start_at))).toISOString();db.prepare("UPDATE viewing_journeys SET status='PENDING_AGENTS',plan=?,version=version+1,updated_at=? WHERE id=?").run(JSON.stringify(plan),now(),id);event(a,id,'POLICY_ACCEPTED',{policyVersion:q.policyVersion,totalKES:q.totalKES});return get(a,id);});}
 function agentConfirm(a,id,position,data){role(a,'agent','admin');return tx(()=>{expireInside();const j=access(a,id);version(j,data);if(j.status!=='PENDING_AGENTS')fail(409,'Package is not awaiting confirmations');const ss=stops(db,id),s=ss.find(s=>s.position===position);if(!s)fail(404,'Package stop not found');supply.listing(s.listing_id,a);const plan=JSON.parse(j.plan),q=JSON.parse(j.quote);validateSlots(plan,q.route,id);qualify({id:j.customer_id,role:'customer'},plan);
 if(data.decision==='DECLINED'){text(data.reason,'Decline reason',1000);cancelInside(a,j,'DECLINED','REFUND',data.reason);return get(a,id);}if(data.decision!=='ACCEPTED')fail(400,'Choose ACCEPTED or DECLINED');if(s.request_status==='ACCEPTED')return {...get(a,id),duplicate:true};db.prepare("UPDATE viewing_requests SET status='ACCEPTED',updated_at=? WHERE id=?").run(now(),s.request_id);event(a,id,'AGENT_CONFIRMED',{position});
 if(stops(db,id).every(s=>s.request_status==='ACCEPTED'))makePayable(a,raw(id));else db.prepare('UPDATE viewing_journeys SET version=version+1,updated_at=? WHERE id=?').run(now(),id);return get(a,id);});}
 function makePayable(a,j){const plan=JSON.parse(j.plan),q=JSON.parse(j.quote),slots=validateSlots(plan,q.route,j.id),ss=stops(db,j.id),time=now(),expiry=new Date(Math.min(Date.now()+30*60000,Date.parse(slots[0].start_at))).toISOString();
 if(!j.master_booking_id){const creditAmount=plan.useCredits?Math.min(balance(j.customer_id),q.totalKES):0;credit(j,-creditAmount,'reserve:'+j.id);const net=q.totalKES-creditAmount;let master;
 for(const s of ss){const booking=randomUUID(),payment=randomUUID(),reservation=randomUUID(),slot=slots[s.position],amount=s.position===0?net:0;if(s.position===0)master=booking;db.prepare("INSERT INTO bookings VALUES(?,?,?,?,?,'requested',?,NULL,?)").run(booking,j.customer_id,s.listing_id,plan.tier,amount,slot.start_at,time);db.prepare("INSERT INTO payments VALUES(?,?,?,'pending',NULL,NULL,NULL)").run(payment,booking,amount);db.prepare("INSERT INTO reservations VALUES(?,?,?,?,?,?,'HOLD_CREATED',?,?,'[\"PAYMENT_CONFIRMED\"]',1,?,?)").run(reservation,j.customer_id,s.listing_id,'property',slot.start_at,slot.end_at,expiry,'package:'+j.id+':'+s.position,time,time);db.prepare('INSERT INTO booking_reservations VALUES(?,?,?)').run(booking,reservation,time);db.prepare('INSERT INTO reservation_events VALUES(?,?,?,?,?)').run(randomUUID(),reservation,'HOLD_CREATED','package:'+j.id,time);db.prepare('UPDATE viewing_requests SET booking_id=? WHERE id=?').run(booking,s.request_id);db.prepare('UPDATE journey_stops SET booking_id=? WHERE request_id=?').run(booking,s.request_id);}
 db.prepare("UPDATE viewing_journeys SET status='PAYABLE',master_booking_id=?,credit_amount=?,version=version+1,updated_at=? WHERE id=?").run(master,creditAmount,time,j.id);if(net===0){confirmPackageInsideTransaction(db,master,a);db.prepare("UPDATE bookings SET status='confirmed' WHERE id=?").run(master);db.prepare("UPDATE payments SET status='paid',reference=?,verified_by=?,verified_at=? WHERE booking_id=?").run('CREDIT_'+j.id,a.id,time,master);event(a,j.id,'CREDITS_PAID',{amount:creditAmount});}
 }else{const p=db.prepare('SELECT status FROM payments WHERE booking_id=?').get(j.master_booking_id);const paid=p.status==='paid';for(const s of ss){const slot=slots[s.position];db.prepare("UPDATE reservations SET status=?,hold_expires_at=?,version=version+1,updated_at=? WHERE id=(SELECT reservation_id FROM booking_reservations WHERE booking_id=?)").run(paid?'CONFIRMED':'HOLD_CREATED',paid?null:expiry,time,s.booking_id);db.prepare('UPDATE bookings SET status=? WHERE id=?').run(paid?'confirmed':'requested',s.booking_id);}db.prepare('UPDATE viewing_journeys SET status=?,version=version+1,updated_at=? WHERE id=?').run(paid?'CONFIRMED':'PAYABLE',time,j.id);}
 event(a,j.id,'ALL_AGENTS_CONFIRMED');notify(j.customer_id,'All viewing stops confirmed. Review the package payment status and deadline.');}
 function cancelInside(a,j,status,disposition,reason){const time=now(),p=j.master_booking_id?db.prepare('SELECT * FROM payments WHERE booking_id=?').get(j.master_booking_id):null;if(p?.status==='paid'){credit(j,j.credit_amount,'restore:'+j.id);if(disposition==='CREDIT'){credit(j,p.amount,'cancel-credit:'+j.id);db.prepare("UPDATE payments SET status='refunded' WHERE id=?").run(p.id);}else{db.prepare("UPDATE payments SET status=? WHERE id=?").run(p.amount?'refund_pending':'refunded',p.id);if(p.amount)db.prepare("INSERT INTO journey_refunds(journey_id,amount,status) VALUES(?,?,'PENDING')").run(j.id,p.amount);}}else{credit(j,j.credit_amount,'restore:'+j.id);if(p)db.prepare("UPDATE payments SET status='cancelled' WHERE id=?").run(p.id);}
 for(const s of stops(db,j.id)){db.prepare("UPDATE viewing_requests SET status=?,reason=?,updated_at=? WHERE id=?").run(status==='EXPIRED'?'EXPIRED':status==='DECLINED'?'DECLINED':'CANCELLED',reason,time,s.request_id);db.prepare("UPDATE property_leads SET stage='LOST',updated_at=? WHERE request_id=?").run(time,s.request_id);if(s.booking_id){db.prepare("UPDATE bookings SET status='cancelled' WHERE id=?").run(s.booking_id);db.prepare("UPDATE reservations SET status='CANCELLED',hold_expires_at=NULL,version=version+1,updated_at=? WHERE id=(SELECT reservation_id FROM booking_reservations WHERE booking_id=?)").run(time,s.booking_id);if(s.booking_id!==j.master_booking_id)db.prepare("UPDATE payments SET status='cancelled' WHERE booking_id=?").run(s.booking_id);}}
 if(j.master_booking_id)db.prepare("UPDATE dispatch_assignments SET status='CANCELLED',lease_expires_at=NULL,version=version+1,updated_at=? WHERE booking_id=? AND status IN ('OFFERED','ACCEPTED','ASSIGNED','DRIVER_EN_ROUTE','ARRIVED')").run(time,j.master_booking_id);db.prepare('UPDATE viewing_journeys SET status=?,version=version+1,updated_at=? WHERE id=?').run(status,time,j.id);event(a,j.id,status,{disposition,reason});notify(j.customer_id,'Your whole viewing package was '+status.toLowerCase()+'. Review the credit or refund status.');}
 function expireInside(){for(const j of db.prepare("SELECT * FROM viewing_journeys WHERE status IN ('QUOTED','PENDING_AGENTS','PAYABLE')").all()){const p=JSON.parse(j.plan);const start=db.prepare('SELECT start_at FROM property_slots WHERE id=?').get(p.stops[0].slotId)?.start_at;const hold=j.master_booking_id?db.prepare('SELECT r.hold_expires_at FROM reservations r JOIN booking_reservations br ON br.reservation_id=r.id WHERE br.booking_id=?').get(j.master_booking_id)?.hold_expires_at:null;if(j.status==='QUOTED'&&j.quote_expires_at<=now()||['PENDING_AGENTS','PAYABLE'].includes(j.status)&&start<=now()||j.status==='PENDING_AGENTS'&&p.confirmationExpiresAt&&p.confirmationExpiresAt<=now()||['PENDING_AGENTS','PAYABLE'].includes(j.status)&&j.master_booking_id&&hold<=now())cancelInside(null,j,'EXPIRED','REFUND','Quote, confirmation or payment deadline expired');}}
 function cancel(a,id,data){role(a,'customer','admin');return tx(()=>{expireInside();const j=access(a,id);version(j,data);if(['CANCELLED','DECLINED','EXPIRED'].includes(j.status))return get(a,id);if(['IN_PROGRESS','COMPLETED'].includes(j.status))fail(409,'Trip has started; contact operations for recovery');const disposition=data.disposition||'REFUND';if(!['REFUND','CREDIT'].includes(disposition))fail(400,'Choose REFUND or CREDIT');cancelInside(a,j,'CANCELLED',disposition,text(data.reason,'Cancellation reason',1000));return get(a,id);});}
 function reschedule(a,id,data){role(a,'customer','admin');return tx(()=>{expireInside();const j=access(a,id);version(j,data);if(!['PENDING_AGENTS','PAYABLE','CONFIRMED','ASSIGNED'].includes(j.status))fail(409,'Package cannot be rescheduled');const assignment=db.prepare("SELECT status FROM dispatch_assignments WHERE booking_id=? AND status IN ('DRIVER_EN_ROUTE','ARRIVED','TRIP_STARTED')").get(j.master_booking_id);if(assignment)fail(409,'Driver has started pickup; contact operations for recovery');const plan=JSON.parse(j.plan);if(!Array.isArray(data.slotIds)||data.slotIds.length!==plan.stops.length)fail(400,'Provide a new slot for every property');const next={...plan,stops:plan.stops.map((s,i)=>({...s,slotId:data.slotIds[i]}))},q=JSON.parse(j.quote),slots=validateSlots(next,q.route,id);qualify({id:j.customer_id,role:'customer'},next);next.confirmationExpiresAt=new Date(Math.min(Date.now()+30*60000,Date.parse(slots[0].start_at))).toISOString();
 // Release all old unique slot claims before claiming the new itinerary, in one transaction.
 db.prepare("UPDATE viewing_requests SET status='CANCELLED' WHERE id IN (SELECT request_id FROM journey_stops WHERE journey_id=?)").run(id);
 const time=now(),expires=new Date(Math.min(Date.now()+30*60000,Date.parse(slots[0].start_at))).toISOString();for(const s of stops(db,id)){const slot=slots[s.position];db.prepare("UPDATE viewing_requests SET status='REQUESTED',slot_id=?,updated_at=? WHERE id=?").run(slot.id,time,s.request_id);if(s.booking_id){const r=db.prepare('SELECT r.* FROM reservations r JOIN booking_reservations br ON br.reservation_id=r.id WHERE br.booking_id=?').get(s.booking_id);db.prepare('INSERT INTO reservation_revisions VALUES(?,?,?,?,?,?,?,?)').run(randomUUID(),r.id,r.start_at,r.end_at,slot.start_at,slot.end_at,'package-reschedule:'+id+':'+j.version+':'+s.position,time);db.prepare("UPDATE reservations SET start_at=?,end_at=?,status='HOLD_CREATED',hold_expires_at=?,version=version+1,updated_at=? WHERE id=?").run(slot.start_at,slot.end_at,expires,time,r.id);db.prepare("UPDATE bookings SET scheduled_at=?,status='requested',driver_id=NULL WHERE id=?").run(slot.start_at,s.booking_id);}notify(supply.listing(s.listing_id).owner_id,'Package rescheduled: please confirm the new viewing time.');}
 if(j.master_booking_id)db.prepare("UPDATE dispatch_assignments SET status='CANCELLED',lease_expires_at=NULL,version=version+1,updated_at=? WHERE booking_id=? AND status IN ('OFFERED','ACCEPTED','ASSIGNED')").run(time,j.master_booking_id);db.prepare("UPDATE viewing_journeys SET status='PENDING_AGENTS',plan=?,version=version+1,updated_at=? WHERE id=?").run(JSON.stringify(next),time,id);event(a,id,'RESCHEDULED',{slotIds:data.slotIds});return get(a,id);});}
 function transport(a,id,action){role(a,'driver','admin');const j=access(a,id),assignment=db.prepare("SELECT * FROM dispatch_assignments WHERE booking_id=? AND status IN ('ASSIGNED','DRIVER_EN_ROUTE','ARRIVED','TRIP_STARTED','TRIP_COMPLETED') ORDER BY created_at DESC LIMIT 1").get(j.master_booking_id);if(!assignment||a.role==='driver'&&assignment.driver_id!==a.id)fail(403,'An accepted transport assignment is required');if(action==='start'){if(j.status==='IN_PROGRESS')return get(a,id);if(j.status!=='ASSIGNED')fail(409,'Package must have an assigned driver'); let current=assignment.status;for(const to of ['DRIVER_EN_ROUTE','ARRIVED','TRIP_STARTED']){const order=['ASSIGNED','DRIVER_EN_ROUTE','ARRIVED','TRIP_STARTED'];if(order.indexOf(current)<order.indexOf(to)){dispatch.transition({assignmentId:assignment.id,to,actor:a});current=to;}}
 }else{dispatch.transition({assignmentId:assignment.id,to:'TRIP_COMPLETED',actor:a});}return get(a,id);}
 function stopComplete(a,id,position,data){role(a,'driver','admin');return tx(()=>{const j=access(a,id);version(j,data);if(j.status!=='IN_PROGRESS')fail(409,'Start package transport first');const ss=stops(db,id),s=ss.find(s=>s.position===position);if(!s)fail(404,'Stop not found');if(s.status==='COMPLETED')return get(a,id);if(ss.some(t=>t.position<position&&t.status!=='COMPLETED'))fail(409,'Complete stops in itinerary order');db.prepare("UPDATE journey_stops SET status='COMPLETED' WHERE journey_id=? AND position=?").run(id,position);db.prepare("UPDATE bookings SET status='completed' WHERE id=?").run(s.booking_id);db.prepare('UPDATE viewing_journeys SET version=version+1,updated_at=? WHERE id=?').run(now(),id);event(a,id,'STOP_COMPLETED',{position});return get(a,id);});}
 function settleRefund(a,id,data){role(a,'admin');return tx(()=>{access(a,id);const r=db.prepare('SELECT * FROM journey_refunds WHERE journey_id=?').get(id);if(!r)fail(404,'Pending refund not found');const ref=text(data.reference,'Actual refund transaction reference',80);if(!/^[A-Za-z0-9_-]{6,80}$/.test(ref)||data.amount!==r.amount)fail(400,'Refund reference and exact amount required');if(r.status==='REFUNDED'){if(r.reference!==ref)fail(409,'Refund already settled');return get(a,id);}if(db.prepare('SELECT 1 FROM payment_references WHERE reference=?').get(ref))fail(409,'Transaction reference already used');db.prepare('INSERT INTO payment_references VALUES(?,?,?,?,?,?)').run(ref,'journey_refund',id,r.amount,'KES',now());ledger.recordInsideTransaction({eventType:'REFUND_SETTLED',kind:'journey_refund',entityId:id,reference:ref,amount:r.amount,currency:'KES',direction:'DEBIT',provider:'manual',actor:a});db.prepare("UPDATE journey_refunds SET status='REFUNDED',reference=?,verified_by=?,verified_at=? WHERE journey_id=?").run(ref,a.id,now(),id);db.prepare("UPDATE payments SET status='refunded' WHERE booking_id=(SELECT master_booking_id FROM viewing_journeys WHERE id=?)").run(id);event(a,id,'REFUND_SETTLED',{reference:ref,amount:r.amount});return get(a,id);});}
 function get(a,id){const j=access(a,id),ss=stops(db,id),plan=JSON.parse(j.plan),q=j.quote?JSON.parse(j.quote):null;const p=j.master_booking_id?db.prepare('SELECT id,amount,status,reference FROM payments WHERE booking_id=?').get(j.master_booking_id):null;const data={...j,plan,quote:q,payment:p,refund:db.prepare('SELECT amount,status,reference FROM journey_refunds WHERE journey_id=?').get(id)||null,stops:ss.map(s=>{const v=db.prepare('SELECT v.*,l.owner_id,l.payload,ps.start_at,ps.end_at FROM viewing_requests v JOIN listings l ON l.id=v.listing_id JOIN property_slots ps ON ps.id=v.slot_id WHERE v.id=?').get(s.request_id);return {...s,listing:JSON.parse(v.payload),ownerId:v.owner_id,startAt:v.start_at,endAt:v.end_at,outcome:db.prepare('SELECT outcome,notes FROM viewing_outcomes WHERE request_id=?').get(s.request_id)||null};}),events:db.prepare('SELECT event,details,created_at FROM journey_events WHERE journey_id=? ORDER BY created_at').all(id).map(e=>({...e,details:JSON.parse(e.details)}))};if(a.role==='agent'){// An agent receives only their own stops and no customer's contact/participant or payment data.
 data.stops=data.stops.filter(s=>s.ownerId===a.id);data.plan={tier:plan.tier,stops:plan.stops.filter(s=>data.stops.some(t=>t.listing_id===s.listingId))};delete data.quote;delete data.payment;delete data.refund;delete data.credit_amount;delete data.events;delete data.idempotency_key;
 }return data;}
 function list(a){role(a,'customer','agent','admin','driver');tx(expireInside);const ids=db.prepare('SELECT id FROM viewing_journeys ORDER BY created_at DESC').all();return ids.flatMap(({id})=>{try{return [get(a,id)];}catch(e){if(e.status===403)return [];throw e;}});}
 function wallet(a){role(a,'customer');return {currency:'KES',balanceKES:balance(a.id),entries:db.prepare('SELECT journey_id,amount,event_key,created_at FROM customer_credit_entries WHERE customer_id=? ORDER BY created_at DESC').all(a.id)};}
 function guardBooking(id){if(packageForBooking(db,id))fail(409,'Manage the whole viewing package through its journey');}
 function guardRequest(id){if(db.prepare('SELECT 1 FROM journey_stops WHERE request_id=?').get(id))fail(409,'Manage this stop through its whole viewing package');}
 function read(a,id){tx(expireInside);return get(a,id);}
 return {create,quote,accept,agentConfirm,cancel,reschedule,transport,stopComplete,settleRefund,get:read,list,policy,details,wallet,guardBooking,guardRequest};
}
module.exports={createJourneyAuthority};
