const {randomUUID,createHash,createHmac,timingSafeEqual}=require('node:crypto');
const {now,fail,role,phone,text,transaction}=require('./common');
const {paymentTarget,allPayments}=require('./targets');
const {createLedgerAuthority}=require('../payments/ledger/ledger-authority');
function createCollections({db,jobs,connected,callbackSecret,paymentAuthority,rides,services,audit=()=>{}}){
 const actor={id:null,role:'admin',provider:'integration_gateway'},ledger=createLedgerAuthority({db,audit});
 function get(a,id){role(a,'customer','admin');const c=db.prepare('SELECT * FROM collection_requests WHERE id=?').get(id);if(!c)fail(404,'Collection request not found');if(a.role!=='admin'&&c.customer_id!==a.id)fail(403,'Collection belongs to another customer');return c;}
 function list(a){role(a,'customer','admin');return a.role==='admin'?db.prepare('SELECT * FROM collection_requests ORDER BY created_at DESC LIMIT 500').all():db.prepare('SELECT * FROM collection_requests WHERE customer_id=? ORDER BY created_at DESC').all(a.id);}
 function payable(a){role(a,'customer','admin');return allPayments(db).filter(p=>p.payable&&(a.role==='admin'||p.customer_id===a.id)).map(p=>({kind:p.kind,targetId:p.target_id,amount:p.amount}));}
 function request(a,b){role(a,'customer');if(!connected||!callbackSecret)fail(503,'Payment gateway and authenticated callback are not configured');const contact=phone(b.phone),key=text(b.idempotencyKey,'Idempotency key',128);return transaction(db,()=>{const previous=db.prepare('SELECT id,kind,target_id,phone FROM collection_requests WHERE customer_id=? AND idempotency_key=?').get(a.id,key);if(previous){if(previous.kind!==b.kind||previous.target_id!==b.targetId||previous.phone!==contact)fail(409,'Request key belongs to another payment');return get(a,previous.id);}const p=paymentTarget(db,b.kind,b.targetId);if(p.customer_id!==a.id)fail(403,'Payment belongs to another customer');if(!p.payable||p.amount<=0)fail(409,'Payment is no longer payable');if(db.prepare("SELECT id FROM collection_requests WHERE kind=? AND target_id=? AND status IN ('QUEUED','WAITING','REVIEW','CONFIRMED')").get(b.kind,b.targetId))fail(409,'An existing collection must finish or be reconciled first');const id=randomUUID();db.prepare("INSERT INTO collection_requests VALUES(?,?,?,?,?,?,?,'QUEUED',NULL,NULL,NULL,?,?)").run(id,a.id,b.kind,b.targetId,p.amount,contact,key,now(),now());jobs.enqueue({kind:'payment.collect',customerId:a.id,targetKind:b.kind,targetId:b.targetId,key:'collect:'+id,payload:{collectionId:id,amount:p.amount,currency:'KES',phone:contact,description:'Ride2View '+b.kind+' service'}});audit(a,'collection.requested',id,{kind:b.kind,targetId:b.targetId,amount:p.amount});return get(a,id);});}
 function prepare(j){const c=db.prepare('SELECT * FROM collection_requests WHERE id=?').get(j.payload.collectionId);if(!c||c.status!=='QUEUED')return false;const p=paymentTarget(db,c.kind,c.target_id);if(!p.payable){db.prepare("UPDATE collection_requests SET status='CANCELLED',updated_at=? WHERE id=?").run(now(),c.id);return false;}return true;}
 function acknowledged(j,r){const requestId=text(r.requestId,'Provider request ID',200);db.prepare("UPDATE collection_requests SET status='WAITING',provider_request_id=?,updated_at=? WHERE id=? AND status='QUEUED'").run(requestId,now(),j.payload.collectionId);}
 function authenticate(raw,headers){if(!callbackSecret)fail(503,'Authenticated payment callback is not configured');const timestamp=String(headers['x-r2v-timestamp']||''),signature=String(headers['x-r2v-signature']||'');if(!/^\d{10}$/.test(timestamp)||Math.abs(Date.now()/1000-Number(timestamp))>300)fail(401,'Callback timestamp is invalid');const expected=createHmac('sha256',callbackSecret).update(timestamp+'.'+raw).digest('hex');if(!/^[a-f0-9]{64}$/.test(signature)||!timingSafeEqual(Buffer.from(expected),Buffer.from(signature)))fail(401,'Callback signature is invalid');}
 function apply(id){const e=db.prepare('SELECT * FROM collection_events WHERE id=?').get(id);if(!e)fail(404,'Callback event not found');if(e.status==='APPLIED')return {duplicate:true};const b=JSON.parse(e.payload),c=db.prepare('SELECT * FROM collection_requests WHERE id=?').get(e.collection_id);if(c.status==='REFUNDED')fail(409,'Unapplied payment already refunded');try{if(!c.provider_request_id){db.prepare("UPDATE collection_events SET status='REVIEW',error='Awaiting provider acknowledgement' WHERE id=?").run(id);return {status:'REVIEW'};}if(c.provider_request_id!==b.requestId)fail(409,'Provider request ID mismatch');if(b.status==='FAILED'){db.prepare("UPDATE collection_requests SET status='FAILED',updated_at=? WHERE id=? AND status='WAITING'").run(now(),c.id);}else{const p=paymentTarget(db,c.kind,c.target_id);if(c.kind==='booking')paymentAuthority.verifyBookingProvider({paymentId:p.id,amount:c.amount,reference:b.reference,currency:'KES',provider:'integration_gateway',correlationId:c.id,actor});else if(c.kind==='ride2go')rides.verify(actor,c.target_id,{amount:c.amount,reference:b.reference});else services.action(actor,c.target_id,'verify',{version:services.get(actor,c.target_id).version,amount:c.amount,reference:b.reference});db.prepare("UPDATE collection_requests SET status='CONFIRMED',reference=?,updated_at=? WHERE id=?").run(b.reference,now(),c.id);}db.prepare("UPDATE collection_events SET status='APPLIED',error=NULL WHERE id=?").run(id);return {status:b.status==='FAILED'?'FAILED':'CONFIRMED'};}catch(e){db.prepare("UPDATE collection_events SET status='REVIEW',error=? WHERE id=?").run('Domain payment could not be applied; reconcile received funds',id);db.prepare("UPDATE collection_requests SET status='REVIEW',reference=COALESCE(?,reference),updated_at=? WHERE id=? AND status!='CONFIRMED'").run(b.status==='SUCCEEDED'?b.reference:null,now(),c.id);return {status:'REVIEW'};}}
 function receive(raw,headers){authenticate(raw,headers);let b;try{b=JSON.parse(raw);}catch{fail(400,'Invalid callback JSON');}const id=text(b.eventId,'Provider event ID',128),hash=createHash('sha256').update(raw).digest('hex');const c=db.prepare('SELECT * FROM collection_requests WHERE id=?').get(b.collectionId);if(!c||c.amount!==b.amount||b.currency!=='KES'||!['SUCCEEDED','FAILED'].includes(b.status)||!b.requestId)fail(400,'Callback does not match the collection');if(c.provider_request_id&&c.provider_request_id!==b.requestId)fail(400,'Provider request ID mismatch');if(b.status==='SUCCEEDED'&&!/^[A-Za-z0-9_-]{6,80}$/.test(b.reference||''))fail(400,'Valid provider receipt reference required');const old=db.prepare('SELECT hash FROM collection_events WHERE id=?').get(id);if(old){if(old.hash!==hash)fail(409,'Callback replay differs from original');return apply(id);}if(db.prepare('SELECT id FROM collection_events WHERE collection_id=?').get(c.id))fail(409,'Collection already has a final provider event');db.prepare("INSERT INTO collection_events VALUES(?,?,?,?,'RECEIVED',NULL,?)").run(id,c.id,hash,raw,now());return apply(id);}
 function retry(a,id){role(a,'admin');return apply(id);}
 function unappliedRefund(a,id,b){role(a,'admin');const c=get(a,id);const e=db.prepare('SELECT payload FROM collection_events WHERE collection_id=?').get(id);if(!e||JSON.parse(e.payload).status!=='SUCCEEDED'||JSON.parse(e.payload).requestId!==c.provider_request_id||!c.reference)fail(409,'No evidenced received funds');if(c.status==='REFUNDED'){if(c.refund_reference===b.reference)return c;fail(409,'Refund already recorded');}if(c.status!=='REVIEW')fail(409,'Only unapplied received funds can use this recovery');const p=paymentTarget(db,c.kind,c.target_id);if(p.reference===c.reference)fail(409,'Payment is already applied; use its normal refund workflow');if(b.amount!==c.amount||!/^[A-Za-z0-9_-]{6,80}$/.test(b.reference||''))fail(400,'Exact amount and actual refund reference required');return transaction(db,()=>{for(const [ref,kind]of [[c.reference,'unapplied_collection'],[b.reference,'unapplied_refund']]){if(db.prepare('SELECT 1 FROM payment_references WHERE reference=?').get(ref))fail(409,'Transfer reference already claimed');db.prepare('INSERT INTO payment_references VALUES(?,?,?,?,?,?)').run(ref,kind,id,c.amount,'KES',now());}for(const [ref,direction]of [[c.reference,'CREDIT'],[b.reference,'DEBIT']])ledger.recordInsideTransaction({eventType:direction==='CREDIT'?'UNAPPLIED_RECEIVED':'UNAPPLIED_REFUNDED',kind:'unapplied_collection',entityId:id,reference:ref,amount:c.amount,currency:'KES',direction,actor:a});db.prepare("UPDATE collection_requests SET status='REFUNDED',refund_reference=?,updated_at=? WHERE id=?").run(b.reference,now(),id);return get(a,id);});}
 function recoverPending(){for(const e of db.prepare("SELECT e.id FROM collection_events e JOIN collection_requests c ON c.id=e.collection_id WHERE c.status='WAITING' AND e.status IN ('RECEIVED','REVIEW')").all())apply(e.id);}
 return {request,list,payable,get,prepare,acknowledged,receive,retry,unappliedRefund,recoverPending};
}
module.exports={createCollections};
