const {randomInt,createHash,timingSafeEqual}=require('node:crypto');
const {now,fail,role,phone,transaction}=require('./common');
const digest=v=>createHash('sha256').update(v).digest('hex');
function createCommunications({db,jobs,connected,audit=()=>{}}){
 function preferences(a){role(a,'customer','agent','driver','admin');const p=db.prepare('SELECT channel,destination,consent,verified_at,updated_at FROM communication_preferences WHERE user_id=?').get(a.id);return p||{channel:'sms',destination:'',consent:0,verified_at:null};}
 function configure(a,b){role(a,'customer','agent','driver','admin');if(b.consent!==true){db.prepare('UPDATE communication_preferences SET consent=0,code_hash=NULL,code_expires=NULL,updated_at=? WHERE user_id=?').run(now(),a.id);return preferences(a);}if(!connected)fail(503,'Messaging provider is not configured');if(!['sms','whatsapp'].includes(b.channel))fail(400,'Choose SMS or WhatsApp');const destination=phone(b.destination),prior=db.prepare('SELECT * FROM communication_preferences WHERE user_id=?').get(a.id);if(prior&&Date.parse(prior.updated_at)>Date.now()-60000)fail(429,'Wait one minute before requesting another verification code');const code=String(randomInt(100000,1000000)),expires=new Date(Date.now()+10*60000).toISOString();return transaction(db,()=>{db.prepare(`INSERT INTO communication_preferences VALUES(?,?,?,1,NULL,?,?,0,?) ON CONFLICT(user_id) DO UPDATE SET channel=excluded.channel,destination=excluded.destination,consent=1,verified_at=NULL,code_hash=excluded.code_hash,code_expires=excluded.code_expires,attempts=0,updated_at=excluded.updated_at`).run(a.id,b.channel,destination,digest(a.id+':'+code),expires,now());jobs.enqueue({kind:'message.verify',customerId:a.id,key:'verify:'+a.id+':'+expires,payload:{channel:b.channel,destination,text:'Your Ride2View verification code is '+code+'. It expires in ten minutes.',expiresAt:expires}});audit(a,'communications.verification_requested',a.id,{channel:b.channel});return preferences(a);});}
 function verify(a,b){role(a,'customer','agent','driver','admin');const p=db.prepare('SELECT * FROM communication_preferences WHERE user_id=?').get(a.id);if(!p?.consent||!p.code_hash||p.code_expires<=now()||p.attempts>=5)fail(409,'Request a new verification code');db.prepare('UPDATE communication_preferences SET attempts=attempts+1 WHERE user_id=?').run(a.id);const supplied=digest(a.id+':'+String(b.code));if(!timingSafeEqual(Buffer.from(supplied),Buffer.from(p.code_hash)))fail(400,'Incorrect verification code');db.prepare('UPDATE communication_preferences SET verified_at=?,code_hash=NULL,code_expires=NULL,updated_at=? WHERE user_id=?').run(now(),now(),a.id);audit(a,'communications.contact_verified',a.id);return preferences(a);}
 function prepare(j){const p=db.prepare('SELECT * FROM communication_preferences WHERE user_id=?').get(j.customer_id);if(!p?.consent||p.destination!==j.payload.destination||p.channel!==j.payload.channel)return false;if(j.kind==='message.verify')return Boolean(p.code_hash&&p.code_expires===j.payload.expiresAt&&p.code_expires>now());if(!p.verified_at)return false;if(j.payload.expiresAt&&j.payload.expiresAt<=now())return false;if(j.payload.reminder){const r=j.payload.reminder;let current;if(r.kind==='booking')current=db.prepare("SELECT scheduled_at AS start,status FROM bookings WHERE id=?").get(r.id);else if(r.kind==='ride2go'){const row=db.prepare('SELECT plan,status FROM ride2go_trips WHERE id=?').get(r.id);if(row)current={start:JSON.parse(row.plan).scheduledAt,status:row.status};}else{const row=db.prepare('SELECT data,status FROM property_service_cases WHERE id=?').get(r.id);if(row)current={start:JSON.parse(row.data).startAt,status:row.status};}if(!current||current.start!==r.start||!['confirmed','assigned','CONFIRMED','ASSIGNED','ARRIVED'].includes(current.status))return false;}return true;}
 function acknowledged(j,r){if(typeof r.messageId!=='string'||!r.messageId)fail(502,'Messaging acknowledgement missing');}
 function enqueueMessage(key,userId,message,extra={}){const p=db.prepare('SELECT * FROM communication_preferences WHERE user_id=?').get(userId);if(!p?.consent||!p.verified_at)return;return jobs.enqueue({kind:'message.send',customerId:userId,key,payload:{channel:p.channel,destination:p.destination,text:message,...extra}});}
 function scan(){// Backlogs before consent/verification are not sent.
 for(const n of db.prepare("SELECT n.* FROM notifications n JOIN communication_preferences p ON p.user_id=n.user_id WHERE p.consent=1 AND p.verified_at IS NOT NULL AND n.created_at>=p.verified_at AND NOT EXISTS(SELECT 1 FROM integration_jobs j WHERE j.event_key='notification:'||n.id) ORDER BY n.created_at LIMIT 500").all())enqueueMessage('notification:'+n.id,n.user_id,'Ride2View has an update for you. Sign in to view your booking and messages.');
 const reminders=[...db.prepare("SELECT id,customer_id,scheduled_at AS start,'booking' AS kind FROM bookings WHERE status IN ('confirmed','assigned') AND id NOT IN (SELECT booking_id FROM journey_stops WHERE position>0)").all(),...db.prepare("SELECT id,customer_id,json_extract(plan,'$.scheduledAt') AS start,'ride2go' AS kind FROM ride2go_trips WHERE status IN ('CONFIRMED','ASSIGNED','ARRIVED')").all(),...db.prepare("SELECT id,customer_id,json_extract(data,'$.startAt') AS start,'service' AS kind FROM property_service_cases WHERE kind='remote' AND status='CONFIRMED'").all()];for(const r of reminders){const remaining=Date.parse(r.start)-Date.now();if(remaining>0&&remaining<=86400000)enqueueMessage('reminder:'+r.kind+':'+r.id+':'+r.start,r.customer_id,'Ride2View reminder: your appointment is '+new Date(r.start).toLocaleString('en-GB',{timeZone:'Africa/Nairobi'})+' (Africa/Nairobi). Sign in for details.',{expiresAt:r.start,reminder:r});}
 for(const r of db.prepare("SELECT b.id,b.customer_id,a.id AS assignment FROM bookings b JOIN dispatch_assignments a ON a.booking_id=b.id WHERE a.status='ARRIVED' AND b.status='assigned'").all())enqueueMessage('arrival:booking:'+r.assignment,r.customer_id,'Your Ride2View driver has arrived. Sign in for details.',{expiresAt:new Date(Date.now()+15*60000).toISOString()});
 for(const r of db.prepare("SELECT id,customer_id FROM ride2go_trips WHERE status='ARRIVED'").all())enqueueMessage('arrival:ride2go:'+r.id,r.customer_id,'Your Ride2Go driver has arrived. Sign in to view your private pickup code.',{expiresAt:new Date(Date.now()+15*60000).toISOString()});
 // OTPs need not remain in persisted jobs after expiry/acknowledgement.
 for(const j of db.prepare("SELECT id,payload,status FROM integration_jobs WHERE kind='message.verify'").all()){const p=JSON.parse(j.payload);if(j.status==='SENT'||p.expiresAt<=now()){delete p.text;db.prepare('UPDATE integration_jobs SET payload=? WHERE id=?').run(JSON.stringify(p),j.id);}}
 }
 return {preferences,configure,verify,prepare,acknowledged,scan};
}
module.exports={createCommunications};
