const {randomUUID}=require('node:crypto');
const {now,fail,role,text,transaction}=require('./common');
const {createLedgerAuthority}=require('../payments/ledger/ledger-authority');
const {paymentTarget,allPayments}=require('./targets');
function createFinance({db,jobs,connected,refundsConnected=connected,rides,services,journeys,audit=()=>{}}){
 const ledger=createLedgerAuthority({db,audit});
 function policy(a,b){role(a,'admin');if(b===undefined){const p=db.prepare('SELECT * FROM fiscal_policies ORDER BY version DESC LIMIT 1').get();return p?{version:p.version,...JSON.parse(p.data)}:null;}if(!Number.isSafeInteger(b.taxBasisPoints)||b.taxBasisPoints<0||b.taxBasisPoints>10000)fail(400,'Provide the reviewed inclusive tax rate in basis points');if(b.taxInclusive!==true)fail(400,'Current quoted amounts must be treated as tax-inclusive; do not add undisclosed charges');const data={supplierName:text(b.supplierName,'Registered supplier name'),supplierPin:text(b.supplierPin,'Supplier tax PIN',40),supplierAddress:text(b.supplierAddress,'Supplier address',500),taxCategory:text(b.taxCategory,'Provider tax category',100),taxBasisPoints:b.taxBasisPoints,taxInclusive:true,evidence:text(b.evidence,'Tax treatment review evidence',2000)};return transaction(db,()=>{const version=(policy(a)?.version||0)+1;db.prepare('INSERT INTO fiscal_policies VALUES(?,?,?,?)').run(version,JSON.stringify(data),a.id,now());audit(a,'fiscal.policy_published',String(version),data);return {version,...data};});}
 function sync(){for(const p of allPayments(db)){if(p.companion||p.amount<=0||!p.reference||!['paid','refund_pending','refunded'].includes(p.status))continue;const snapshot={kind:p.kind,targetId:p.target_id,amountKES:p.amount,currency:'KES',paymentReference:p.reference,receivedAt:p.verified_at||null,label:'Payment receipt — not a fiscal tax invoice'};db.prepare('INSERT OR IGNORE INTO customer_receipts(id,kind,target_id,customer_id,amount,reference,snapshot,created_at) VALUES(?,?,?,?,?,?,?,?)').run(randomUUID(),p.kind,p.target_id,p.customer_id,p.amount,p.reference,JSON.stringify(snapshot),now());}}
 function get(a,id){role(a,'customer','admin');const r=db.prepare('SELECT * FROM customer_receipts WHERE id=?').get(id);if(!r)fail(404,'Receipt not found');if(a.role!=='admin'&&r.customer_id!==a.id)fail(403,'Receipt belongs to another customer');const p=paymentTarget(db,r.kind,r.target_id);return {...r,receiptNumber:'R2V-'+String(r.number).padStart(8,'0'),snapshot:JSON.parse(r.snapshot),paymentStatus:p.status,fiscal:db.prepare('SELECT * FROM fiscal_documents WHERE receipt_id=? ORDER BY created_at').all(id).map(x=>({...x,snapshot:JSON.parse(x.snapshot),provider_result:x.provider_result?JSON.parse(x.provider_result):null}))};}
 function list(a){role(a,'customer','admin');sync();return (a.role==='admin'?db.prepare('SELECT id FROM customer_receipts ORDER BY number DESC').all():db.prepare('SELECT id FROM customer_receipts WHERE customer_id=? ORDER BY number DESC').all(a.id)).map(r=>get(a,r.id));}
 function document(a,id,b){role(a,'admin');if(!connected)fail(503,'Fiscal integration gateway is not configured');const r=get(a,id),kind=b.kind||'invoice';if(!['invoice','credit'].includes(kind))fail(400,'Select invoice or credit note');const prior=db.prepare('SELECT id FROM fiscal_documents WHERE receipt_id=? AND kind=?').get(id,kind);if(prior)return get(a,id);let config=policy(a),original=null;if(!config)fail(409,'Configure reviewed supplier/tax policy first');if(kind==='credit'){const origin=db.prepare("SELECT * FROM fiscal_documents WHERE receipt_id=? AND kind='invoice' AND status='ACCEPTED'").get(id);if(r.paymentStatus!=='refunded'||!origin)fail(409,'A settled refund and accepted original fiscal invoice are required');original=JSON.parse(origin.provider_result).invoiceNumber;config=JSON.parse(origin.snapshot).policy;}const grossMinor=r.amount*100,taxMinor=Math.round(grossMinor*config.taxBasisPoints/(10000+config.taxBasisPoints));const snapshot={receiptNumber:r.receiptNumber,receiptId:id,customerId:r.customer_id,description:'Ride2View '+r.kind+' service',currency:'KES',grossMinor,taxMinor,netMinor:grossMinor-taxMinor,kind,originalInvoice:original,policy:config};return transaction(db,()=>{const documentId=randomUUID();db.prepare("INSERT INTO fiscal_documents VALUES(?,?,?,?,'QUEUED',NULL,?)").run(documentId,id,kind,JSON.stringify(snapshot),now());jobs.enqueue({kind:'fiscal.submit',customerId:r.customer_id,targetKind:r.kind,targetId:r.target_id,key:'fiscal:'+documentId,payload:{documentId,...snapshot}});audit(a,'fiscal.document_queued',documentId,{receiptId:id,kind});return get(a,id);});}
 function acknowledged(j,r){if(r.accepted!==true||typeof r.invoiceNumber!=='string'||!r.invoiceNumber||typeof r.controlCode!=='string'||!r.controlCode)fail(502,'Provider must supply fiscal acceptance evidence');if(r.verificationUrl){let u;try{u=new URL(r.verificationUrl);}catch{fail(502,'Invalid fiscal verification URL');}if(u.protocol!=='https:'||u.username||u.password)fail(502,'Invalid fiscal verification URL');}db.prepare("UPDATE fiscal_documents SET status='ACCEPTED',provider_result=? WHERE id=? AND status='QUEUED'").run(JSON.stringify({invoiceNumber:r.invoiceNumber,controlCode:r.controlCode,verificationUrl:r.verificationUrl||null,acceptedAt:now()}),j.payload.documentId);}
 function refund(a,kind,id,b){role(a,'admin');const p=paymentTarget(db,kind,id);if(p.status!=='refund_pending')fail(409,'Only an existing refund liability can be submitted');if(!refundsConnected)fail(503,'Refund integration gateway is not configured');return transaction(db,()=>{const prior=db.prepare('SELECT * FROM operations_refunds WHERE kind=? AND target_id=?').get(kind,id);if(prior)return prior;const refundId=randomUUID();db.prepare("INSERT INTO operations_refunds VALUES(?,?,?,?,'QUEUED',NULL,?,?)").run(refundId,kind,id,p.amount,now(),now());jobs.enqueue({kind:'payment.refund',customerId:p.customer_id,targetKind:kind,targetId:id,key:'refund:'+refundId,payload:{refundId,amount:p.amount,currency:'KES',originalReference:p.reference,reason:text(b.reason,'Refund reason',1000)}});audit(a,'refund.provider_requested',refundId,{kind,targetId:id,amount:p.amount});return db.prepare('SELECT * FROM operations_refunds WHERE id=?').get(refundId);});}
 function refundAcknowledged(j,r){if(r.amount!==j.payload.amount||r.currency!=='KES'||!/^[A-Za-z0-9_-]{6,80}$/.test(r.reference||''))fail(502,'Exact settled refund amount and reference required');db.prepare("UPDATE operations_refunds SET reference=?,status='SETTLED_UNAPPLIED',updated_at=? WHERE id=?").run(r.reference,now(),j.payload.refundId);}
 function applyRefunds(){for(const r of db.prepare("SELECT * FROM operations_refunds WHERE status='SETTLED_UNAPPLIED'").all()){const a={id:null,role:'admin',provider:'integration_gateway'},body={amount:r.amount,reference:r.reference};try{if(r.kind==='ride2go')rides.refund(a,r.target_id,body);else if(r.kind==='service')services.action(a,r.target_id,'refund',{...body,version:services.get(a,r.target_id).version});else{const j=db.prepare('SELECT id FROM viewing_journeys WHERE master_booking_id=?').get(r.target_id);if(j)journeys.settleRefund(a,j.id,body);else transaction(db,()=>{const p=paymentTarget(db,r.kind,r.target_id);if(p.status==='refunded'){const ref=db.prepare("SELECT reference FROM financial_ledger_events WHERE kind='booking_refund' AND entity_id=?").get(p.id);if(ref?.reference!==r.reference)fail(409,'Refund differs from settled evidence');return;}if(p.status!=='refund_pending'||p.amount!==r.amount)fail(409,'Refund liability changed');if(db.prepare('SELECT 1 FROM payment_references WHERE reference=?').get(r.reference))fail(409,'Reference already used');db.prepare('INSERT INTO payment_references VALUES(?,?,?,?,?,?)').run(r.reference,'booking_refund',p.id,p.amount,'KES',now());ledger.recordInsideTransaction({eventType:'REFUND_SETTLED',kind:'booking_refund',entityId:p.id,reference:r.reference,amount:p.amount,currency:'KES',direction:'DEBIT',provider:a.provider,actor:a});db.prepare("UPDATE payments SET status='refunded' WHERE id=?").run(p.id);});}db.prepare("UPDATE operations_refunds SET status='CONFIRMED',updated_at=? WHERE id=?").run(now(),r.id);}catch{db.prepare("UPDATE operations_refunds SET status='REVIEW',updated_at=? WHERE id=?").run(now(),r.id);audit(null,'refund.application_requires_review',r.id);}}}
 function retryRefund(a,id,reason){role(a,'admin');text(reason,'Recovery reason',1000);db.prepare("UPDATE operations_refunds SET status='SETTLED_UNAPPLIED' WHERE id=? AND status='REVIEW'").run(id);applyRefunds();return db.prepare('SELECT * FROM operations_refunds WHERE id=?').get(id)||null;}
 function refunds(a){role(a,'admin');return {requests:db.prepare('SELECT * FROM operations_refunds ORDER BY created_at DESC').all(),pending:allPayments(db).filter(p=>p.status==='refund_pending'&&!p.companion).map(p=>({kind:p.kind,targetId:p.target_id,amount:p.amount}))};}
 function reconciliations(a){role(a,'admin');return db.prepare('SELECT r.*,l.reference,l.kind,l.direction,l.entity_id FROM reconciliation_records r JOIN financial_ledger_events l ON l.id=r.ledger_event_id ORDER BY r.created_at DESC LIMIT 500').all();}
 function reconcile(a,id,b){role(a,'admin');if(!Number.isSafeInteger(b.observedAmount)||b.observedAmount<0)fail(400,'Observed amount must be a nonnegative whole-KES amount');if(!db.prepare('SELECT id FROM financial_ledger_events WHERE id=?').get(id))fail(404,'Ledger record not found');try{return ledger.reconcile({ledgerEventId:id,observedAmount:b.observedAmount,evidenceRef:text(b.evidenceRef,'Statement or provider evidence',500),actor:a});}catch(e){if(e.code==='RECONCILIATION_ALREADY_FINAL')fail(409,'Reconciliation is already final');throw e;}}
 return {policy,sync,get,list,document,acknowledged,refund,refundAcknowledged,applyRefunds,refunds,retryRefund,reconciliations,reconcile};
}
module.exports={createFinance};
