const {randomUUID}=require('node:crypto');
const {now,fail,role,text,transaction}=require('./common');
function createJobs({db,gateway,audit=()=>{},prepare=()=>true,settle=()=>{},enabled=()=>true}){
 let timer=null,running=null,stopped=false;
 function get(id){const j=db.prepare('SELECT * FROM integration_jobs WHERE id=?').get(id);if(!j)fail(404,'Integration job not found');return {...j,payload:JSON.parse(j.payload),result:j.result?JSON.parse(j.result):null};}
 function enqueue({kind,customerId=null,targetKind=null,targetId=null,key,payload}){const previous=db.prepare('SELECT id FROM integration_jobs WHERE event_key=?').get(key);if(previous)return get(previous.id);const id=randomUUID();db.prepare("INSERT INTO integration_jobs VALUES(?,?,?,?,?,?,?,'PENDING',0,NULL,NULL,NULL,NULL,?,?)").run(id,kind,customerId,targetKind,targetId,key,JSON.stringify(payload),now(),now());return get(id);}
 function markReview(id,token){db.prepare("UPDATE integration_jobs SET status='REVIEW',last_error='Delivery outcome requires provider lookup',lease_token=NULL,lease_until=NULL,updated_at=? WHERE id=? AND lease_token=?").run(now(),id,token);}
 function finish(job,result,token){if(!result||typeof result!=='object')throw new Error('Invalid provider acknowledgement');const current=get(job.id);if(current.lease_token!==token||current.status!=='PROCESSING'||current.lease_until<=now())fail(409,'Integration job lease changed');transaction(db,()=>{settle(job,result);db.prepare("UPDATE integration_jobs SET status='SENT',result=?,lease_token=NULL,lease_until=NULL,last_error=NULL,updated_at=? WHERE id=? AND lease_token=?").run(JSON.stringify(result),now(),job.id,token);audit(null,'integration.job_acknowledged',job.id,{kind:job.kind});});}
 async function process(id,recover=false){if(!gateway||!enabled(get(id)))fail(503,'External gateway capability is not configured');let job,token;transaction(db,()=>{job=get(id);if(job.status==='SENT'||job.status==='CANCELLED')return;if(job.status==='PROCESSING'&&job.lease_until>now())fail(409,'Integration job is already processing');if(!['PENDING','REVIEW','PROCESSING'].includes(job.status))fail(409,'Job cannot be processed');if(job.status!=='PENDING'&&!recover)fail(409,'Ambiguous deliveries require lookup');if(!recover&&!prepare(job)){db.prepare("UPDATE integration_jobs SET status='CANCELLED',updated_at=? WHERE id=?").run(now(),id);return;}token=randomUUID();db.prepare("UPDATE integration_jobs SET status='PROCESSING',attempts=attempts+1,lease_token=?,lease_until=?,updated_at=? WHERE id=?").run(token,new Date(Date.now()+30000).toISOString(),now(),id);});if(!token)return get(id);
 try{let result;if(recover){const found=await gateway.lookup(job);if(found?.status==='NOT_FOUND'){// Positive provider absence is the only permission to send again.
 const allowed=transaction(db,()=>{if(prepare(job))return true;db.prepare("UPDATE integration_jobs SET status='CANCELLED',lease_token=NULL,lease_until=NULL,updated_at=? WHERE id=? AND lease_token=?").run(now(),id,token);return false;});if(!allowed)return get(id);result=await gateway.send(job);
 }else if(found?.status==='COMPLETED')result=found.result;else throw new Error('Provider lookup is inconclusive');}else result=await gateway.send(job);finish(job,result,token);return get(id);}catch(e){markReview(id,token);throw Object.assign(new Error('Provider delivery needs reconciliation; no blind retry was performed'),{status:502});}}
 function review(a){role(a,'admin');return db.prepare('SELECT id,kind,target_kind,target_id,status,attempts,last_error,created_at,updated_at FROM integration_jobs ORDER BY created_at DESC LIMIT 500').all();}
 async function reconcile(a,id,reason){role(a,'admin');text(reason,'Reconciliation reason',1000);audit(a,'integration.lookup_requested',id,{reason});return process(id,true);}
 function drain(){if(running||stopped)return running||Promise.resolve();running=(async()=>{db.prepare("UPDATE integration_jobs SET status='REVIEW',last_error='Worker interrupted; provider lookup required',lease_token=NULL,lease_until=NULL WHERE status='PROCESSING' AND lease_until<=?").run(now());if(gateway)for(const j of db.prepare("SELECT id,kind FROM integration_jobs WHERE status='PENDING' ORDER BY created_at").all().filter(enabled).slice(0,20)){if(stopped)break;try{await process(j.id);}catch{}}})().finally(()=>{running=null;});return running;}
 function start(){stopped=false;if(timer)return;timer=setInterval(()=>{void drain().catch(()=>{});},5000);timer.unref();}
 async function stop(){stopped=true;clearInterval(timer);timer=null;if(running)await running;}
 return {get,enqueue,process,review,reconcile,drain,start,stop};
}
module.exports={createJobs};
