const {now,fail,role,text,transaction}=require('./common');
const {packageForBooking}=require('../journeys/hooks');
function coordinate(v){if(!v||typeof v.latitude!=='number'||!Number.isFinite(v.latitude)||Math.abs(v.latitude)>90||typeof v.longitude!=='number'||!Number.isFinite(v.longitude)||Math.abs(v.longitude)>180)fail(400,'Valid latitude/longitude coordinates required');return {latitude:v.latitude,longitude:v.longitude};}
function createTracking({db,maps,audit=()=>{}}){
 const busy=new Set(),geocodeLimits=new Map();
 function trip(kind,id){let t;if(kind==='booking'){const b=db.prepare('SELECT * FROM bookings WHERE id=?').get(id);if(b){const j=packageForBooking(db,id);if(j&&j.master_booking_id!==id)fail(409,'Track the main viewing-package booking');const assignment=db.prepare("SELECT * FROM dispatch_assignments WHERE booking_id=? AND status IN ('ASSIGNED','DRIVER_EN_ROUTE','ARRIVED','TRIP_STARTED') ORDER BY created_at DESC LIMIT 1").get(id);t={id,kind,customerId:b.customer_id,driverId:assignment?.driver_id||null,status:assignment?.status||b.status,active:b.status==='assigned'&&!!assignment,inProgress:assignment?.status==='TRIP_STARTED',label:'Property viewing',scheduledAt:b.scheduled_at};}}
 else if(kind==='ride2go'){const r=db.prepare('SELECT * FROM ride2go_trips WHERE id=?').get(id);if(r){const p=JSON.parse(r.plan);t={id,kind,customerId:r.customer_id,driverId:r.driver_id,status:r.status,active:['ASSIGNED','ARRIVED','IN_PROGRESS'].includes(r.status),inProgress:r.status==='IN_PROGRESS',label:p.pickup+' → '+p.destination,scheduledAt:p.scheduledAt};}}if(!t)fail(404,'Trip not found');return t;}
 function access(a,kind,id){role(a,'customer','driver','admin');const t=trip(kind,id);if(a.role!=='admin'&&a.id!==t.customerId&&a.id!==t.driverId)fail(403,'Trip belongs to another account');return t;}
 function read(a,kind,id){const t=access(a,kind,id),r=db.prepare('SELECT * FROM trip_routes WHERE kind=? AND target_id=?').get(kind,id);if(!t.active)db.prepare('DELETE FROM driver_positions WHERE kind=? AND target_id=?').run(kind,id);const p=db.prepare('SELECT * FROM driver_positions WHERE kind=? AND target_id=? AND driver_id=?').get(kind,id,t.driverId||'');const fresh=!!p&&Date.parse(p.received_at)>Date.now()-60000&&Date.parse(p.captured_at)>Date.now()-90000;const eta=db.prepare('SELECT * FROM trip_eta WHERE kind=? AND target_id=?').get(kind,id);const phase=t.inProgress?'destination':'pickup';const currentEta=t.active&&fresh&&eta&&eta.driver_id===t.driverId&&eta.route_version===r?.version&&eta.phase===phase&&Date.parse(eta.updated_at)>Date.now()-60000;return {...t,route:r?{version:r.version,...JSON.parse(r.data)}:null,location:t.active&&p?{latitude:p.latitude,longitude:p.longitude,accuracy:p.accuracy,capturedAt:p.captured_at,receivedAt:p.received_at,stale:!fresh}:null,eta:currentEta?{...JSON.parse(eta.result),calculatedAt:eta.updated_at}:null,mapsConnected:Boolean(maps)};}
 function list(a){role(a,'customer','driver','admin');const ids=[...db.prepare('SELECT id FROM bookings').all().map(r=>['booking',r.id]),...db.prepare('SELECT id FROM ride2go_trips').all().map(r=>['ride2go',r.id])];return ids.flatMap(([k,id])=>{try{const t=read(a,k,id);return ['cancelled','completed','CANCELLED','COMPLETED','EXPIRED'].includes(t.status)?[]:[t];}catch(e){if([403,409].includes(e.status))return [];throw e;}});}
 function route(a,kind,id,b){role(a,'customer','admin');const t=access(a,kind,id);if(['cancelled','completed','CANCELLED','COMPLETED','EXPIRED'].includes(t.status))fail(409,'Trip is closed');if(t.inProgress&&a.role!=='admin')fail(409,'Operations must review destination changes after departure');const data={pickup:coordinate(b.pickup),destination:coordinate(b.destination),destinationLabel:text(b.destinationLabel,'Navigation destination',200),reason:text(b.reason,'Coordinate source or change reason',500)};if(b.shareWithDriver!==true)fail(400,'Consent to share this route with the assigned driver');return transaction(db,()=>{const old=db.prepare('SELECT version FROM trip_routes WHERE kind=? AND target_id=?').get(kind,id);if(b.version!==(old?.version||0))fail(409,'Route changed; refresh first');db.prepare(`INSERT INTO trip_routes VALUES(?,?,1,?,?) ON CONFLICT(kind,target_id) DO UPDATE SET version=version+1,data=excluded.data,updated_at=excluded.updated_at`).run(kind,id,JSON.stringify(data),now());db.prepare('DELETE FROM trip_eta WHERE kind=? AND target_id=?').run(kind,id);audit(a,'tracking.route_updated',id,{kind});return read(a,kind,id);});}
 function position(a,kind,id,b){role(a,'driver');const t=access(a,kind,id);if(!t.active||t.driverId!==a.id)fail(409,'Location sharing requires your active assigned trip');const p=coordinate(b);if(!Number.isFinite(b.accuracy)||b.accuracy<0||b.accuracy>200)fail(400,'GPS accuracy must be within 200 metres');if(!Number.isSafeInteger(b.sequence)||b.sequence<1)fail(400,'Monotonic location sequence required');const time=Date.parse(b.capturedAt);if(!Number.isFinite(time)||time>Date.now()+15000||time<Date.now()-120000)fail(400,'Location must be captured within the last two minutes');const old=db.prepare('SELECT * FROM driver_positions WHERE kind=? AND target_id=?').get(kind,id);if(old?.driver_id===a.id){if(b.sequence<=old.sequence||time<Date.parse(old.captured_at))fail(409,'Out-of-order location update');if(Date.parse(old.received_at)>Date.now()-5000)fail(429,'Share location at most once every five seconds');}db.prepare(`INSERT INTO driver_positions VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(kind,target_id) DO UPDATE SET driver_id=excluded.driver_id,sequence=excluded.sequence,latitude=excluded.latitude,longitude=excluded.longitude,accuracy=excluded.accuracy,captured_at=excluded.captured_at,received_at=excluded.received_at`).run(kind,id,a.id,b.sequence,p.latitude,p.longitude,b.accuracy,new Date(time).toISOString(),now());return {accepted:true};}
 function stopSharing(a,kind,id){role(a,'driver');const t=access(a,kind,id);if(t.driverId!==a.id)fail(403,'Assigned driver required');db.prepare('DELETE FROM driver_positions WHERE kind=? AND target_id=?').run(kind,id);db.prepare('DELETE FROM trip_eta WHERE kind=? AND target_id=?').run(kind,id);audit(a,'tracking.sharing_stopped',id,{kind});return {stopped:true};}
 async function eta(a,kind,id){const t=read(a,kind,id);if(!maps)fail(503,'Road routing provider is not configured');if(!t.active||!t.location||t.location.stale||!t.route)fail(409,'A route and fresh driver location are required');if(t.eta)return t;const key=kind+':'+id;if(busy.has(key))fail(429,'ETA calculation is already running');busy.add(key);const position=db.prepare('SELECT sequence FROM driver_positions WHERE kind=? AND target_id=?').get(kind,id);try{const result=await maps.route({origin:coordinate(t.location),destination:t.inProgress?t.route.destination:t.route.pickup});if(!Number.isFinite(result.durationSeconds)||result.durationSeconds<0||!Number.isFinite(result.distanceMetres)||result.distanceMetres<0)fail(502,'Routing provider returned invalid distance or duration');const current=read(a,kind,id);if(!current.active||current.driverId!==t.driverId||current.route?.version!==t.route.version||current.inProgress!==t.inProgress)fail(409,'Trip changed while routing');db.prepare(`INSERT INTO trip_eta VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(kind,target_id) DO UPDATE SET route_version=excluded.route_version,driver_id=excluded.driver_id,position_sequence=excluded.position_sequence,phase=excluded.phase,result=excluded.result,updated_at=excluded.updated_at`).run(kind,id,t.route.version,t.driverId,position.sequence,t.inProgress?'destination':'pickup',JSON.stringify(result),now());return read(a,kind,id);}finally{busy.delete(key);}}
 function cleanup(){for(const p of db.prepare('SELECT kind,target_id,received_at FROM driver_positions').all()){let active=false;try{active=trip(p.kind,p.target_id).active;}catch{}if(!active||Date.parse(p.received_at)<Date.now()-30*60000){db.prepare('DELETE FROM driver_positions WHERE kind=? AND target_id=?').run(p.kind,p.target_id);db.prepare('DELETE FROM trip_eta WHERE kind=? AND target_id=?').run(p.kind,p.target_id);}}}
 async function geocode(a,address){role(a,'customer','admin');if(!maps?.geocode)fail(503,'Address search provider is not configured');text(address,'Street address',300);let limit=geocodeLimits.get(a.id);if(!limit||limit.until<Date.now()){limit={count:0,until:Date.now()+60000};geocodeLimits.set(a.id,limit);}if(++limit.count>10)fail(429,'Too many address searches; retry in a minute');const results=await maps.geocode(address);return {results:results.map(p=>({...coordinate(p),address:text(p.address,'Resolved address',500)}))};}
 return {read,list,route,position,stopSharing,eta,cleanup,geocode};
}
module.exports={createTracking};
