const {randomUUID}=require('node:crypto');
function createMarketplaceAuthority({db,audit=()=>{}}){
 const now=()=>new Date().toISOString();
 function fail(status,message){throw Object.assign(new Error(message),{status});}
 function tx(fn){db.exec('BEGIN IMMEDIATE');try{const r=fn();db.exec('COMMIT');return r;}catch(e){db.exec('ROLLBACK');throw e;}}
 function role(a,...roles){if(!a)fail(401,'Sign in to continue');if(!roles.includes(a.role))fail(403,'This action is not permitted for this account');}
 function relationship({customerId,agentId,listingId,sourceKind,sourceId,actor}){
  return tx(()=>{let r=db.prepare('SELECT * FROM marketplace_relationships WHERE customer_id=? AND agent_id=? AND listing_id=?').get(customerId,agentId,listingId);if(r)return {...r,duplicate:true};
   const id=randomUUID(),t=now();db.prepare('INSERT INTO marketplace_relationships VALUES(?,?,?,?,?,?,\'ACTIVE\',?,?)').run(id,customerId,agentId,listingId,sourceKind,sourceId,t,t);audit(actor,'marketplace.relationship_created',id,{sourceKind,sourceId});return db.prepare('SELECT * FROM marketplace_relationships WHERE id=?').get(id);
  });
 }
 function earn(a,data){role(a,'admin');if(!['driver','agent'].includes(data.beneficiaryRole))fail(400,'Invalid beneficiary role');for(const k of ['grossAmount','platformAmount','beneficiaryAmount'])if(!Number.isSafeInteger(data[k])||data[k]<0)fail(400,'Amounts must be non-negative whole KES');if(data.grossAmount!==data.platformAmount+data.beneficiaryAmount)fail(400,'Earnings split must equal gross amount');
  const user=db.prepare('SELECT id,role FROM users WHERE id=?').get(data.beneficiaryId);if(!user||user.role!==data.beneficiaryRole)fail(409,'Beneficiary role does not match account');
  return tx(()=>{const prior=db.prepare('SELECT * FROM marketplace_earnings WHERE beneficiary_id=? AND source_kind=? AND source_id=?').get(data.beneficiaryId,data.sourceKind,data.sourceId);if(prior)return {...prior,duplicate:true};const id=randomUUID(),t=now();db.prepare('INSERT INTO marketplace_earnings(id,beneficiary_id,beneficiary_role,source_kind,source_id,gross_amount,platform_amount,beneficiary_amount,currency,status,evidence_ref,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,\'KES\',\'EARNED\',?,?,?)').run(id,data.beneficiaryId,data.beneficiaryRole,data.sourceKind,data.sourceId,data.grossAmount,data.platformAmount,data.beneficiaryAmount,String(data.evidenceRef||'').slice(0,512),t,t);audit(a,'marketplace.earning_recorded',id,{sourceKind:data.sourceKind,sourceId:data.sourceId});return db.prepare('SELECT * FROM marketplace_earnings WHERE id=?').get(id);});
 }
 function earnings(a){role(a,'driver','agent','admin');return db.prepare('SELECT * FROM marketplace_earnings '+(a.role==='admin'?'':'WHERE beneficiary_id=?')+' ORDER BY created_at DESC').all(...(a.role==='admin'?[]:[a.id]));}
 function payout(a,id,{reference,evidenceRef}){role(a,'admin');if(!reference||!evidenceRef)fail(400,'Actual payout reference and evidence are required');return tx(()=>{const e=db.prepare('SELECT * FROM marketplace_earnings WHERE id=?').get(id);if(!e)fail(404,'Earning not found');if(e.status==='PAID'){if(e.payout_reference===reference)return {...e,duplicate:true};fail(409,'Earning already paid');}if(!['EARNED','PAYOUT_PENDING'].includes(e.status))fail(409,'Earning cannot be paid from its current state');if(db.prepare('SELECT 1 FROM payment_references WHERE reference=?').get(reference))fail(409,'Payment reference already used');const t=now();db.prepare('INSERT INTO payment_references(reference,kind,entity_id,amount,currency,created_at) VALUES(?,?,?,?,?,?)').run(reference,'marketplace_payout',id,e.beneficiary_amount,e.currency,t);db.prepare("UPDATE marketplace_earnings SET status='PAID',payout_reference=?,updated_at=? WHERE id=?").run(reference,t,id);audit(a,'marketplace.payout_recorded',id,{reference,evidenceRef});return db.prepare('SELECT * FROM marketplace_earnings WHERE id=?').get(id);});}
 function createPlan(a,data){role(a,'admin');for(const k of ['price','durationDays','viewingCredits'])if(!Number.isSafeInteger(data[k])||data[k]<0)fail(400,'Plan values must be whole non-negative numbers');if(data.durationDays<1)fail(400,'Duration must be positive');const id=randomUUID(),t=now();db.prepare('INSERT INTO subscription_plans(id,name,price,currency,duration_days,viewing_credits,created_at) VALUES(?,?,?,\'KES\',?,?,?)').run(id,String(data.name||'').trim(),data.price,data.durationDays,data.viewingCredits,t);return db.prepare('SELECT * FROM subscription_plans WHERE id=?').get(id);}
 function plans(){return db.prepare('SELECT * FROM subscription_plans WHERE active=1 ORDER BY price').all();}
 function subscribe(a,data){role(a,'customer');const p=db.prepare('SELECT * FROM subscription_plans WHERE id=? AND active=1').get(data.planId);if(!p)fail(404,'Subscription plan not found');const prior=db.prepare("SELECT * FROM customer_subscriptions WHERE customer_id=? AND status='ACTIVE' AND ends_at>?").get(a.id,now());if(prior)fail(409,'Customer already has an active subscription');const id=randomUUID(),start=now(),end=new Date(Date.parse(start)+p.duration_days*86400000).toISOString();db.prepare("INSERT INTO customer_subscriptions VALUES(?,?,?,'PENDING',?,?,?,?,?,?)").run(id,a.id,p.id,start,end,p.viewing_credits,null,start,start);audit(a,'subscription.requested',id,{planId:p.id});return db.prepare('SELECT * FROM customer_subscriptions WHERE id=?').get(id);}
 function activate(a,id,{reference}){role(a,'admin');if(!reference)fail(400,'Payment reference required');return tx(()=>{const s=db.prepare('SELECT * FROM customer_subscriptions WHERE id=?').get(id);if(!s)fail(404,'Subscription not found');if(s.status==='ACTIVE'){if(s.payment_reference===reference)return {...s,duplicate:true};fail(409,'Subscription already active');}if(s.status!=='PENDING')fail(409,'Subscription cannot be activated');if(db.prepare('SELECT 1 FROM payment_references WHERE reference=?').get(reference))fail(409,'Payment reference already used');const p=db.prepare('SELECT * FROM subscription_plans WHERE id=?').get(s.plan_id);db.prepare('INSERT INTO payment_references(reference,kind,entity_id,amount,currency,created_at) VALUES(?,?,?,?,?,?)').run(reference,'subscription',id,p.price,p.currency,now());db.prepare("UPDATE customer_subscriptions SET status='ACTIVE',payment_reference=?,updated_at=? WHERE id=?").run(reference,now(),id);audit(a,'subscription.activated',id,{reference});return db.prepare('SELECT * FROM customer_subscriptions WHERE id=?').get(id);});}
 function subscriptions(a){role(a,'customer','admin');db.prepare("UPDATE customer_subscriptions SET status='EXPIRED',updated_at=? WHERE status='ACTIVE' AND ends_at<=?").run(now(),now());return db.prepare('SELECT * FROM customer_subscriptions '+(a.role==='admin'?'':'WHERE customer_id=?')+' ORDER BY created_at DESC').all(...(a.role==='admin'?[]:[a.id]));}
 return {relationship,earn,earnings,payout,createPlan,plans,subscribe,activate,subscriptions};
}
module.exports={createMarketplaceAuthority};
