function installGrowthSchema(db){db.exec(`
CREATE TABLE student_pools(id TEXT PRIMARY KEY,owner_id TEXT NOT NULL REFERENCES users(id),trip_id TEXT REFERENCES ride2go_trips(id),status TEXT NOT NULL DEFAULT 'OPEN',max_members INTEGER NOT NULL CHECK(max_members BETWEEN 2 AND 4),created_at TEXT NOT NULL,updated_at TEXT NOT NULL,CHECK(status IN ('OPEN','LOCKED','COMPLETED','CANCELLED')));
CREATE TABLE student_pool_members(pool_id TEXT NOT NULL REFERENCES student_pools(id),customer_id TEXT NOT NULL REFERENCES users(id),share_amount INTEGER CHECK(share_amount>=0),status TEXT NOT NULL DEFAULT 'INVITED',joined_at TEXT,PRIMARY KEY(pool_id,customer_id),CHECK(status IN ('INVITED','JOINED','LEFT')));
CREATE TABLE marketplace_reviews(id TEXT PRIMARY KEY,source_kind TEXT NOT NULL,source_id TEXT NOT NULL,reviewer_id TEXT NOT NULL REFERENCES users(id),subject_id TEXT NOT NULL REFERENCES users(id),subject_role TEXT NOT NULL,rating INTEGER NOT NULL CHECK(rating BETWEEN 1 AND 5),comment TEXT NOT NULL,created_at TEXT NOT NULL,UNIQUE(source_kind,source_id,reviewer_id,subject_id));
CREATE TABLE safety_incidents(id TEXT PRIMARY KEY,source_kind TEXT NOT NULL,source_id TEXT NOT NULL,reporter_id TEXT NOT NULL REFERENCES users(id),severity TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'OPEN',summary TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,CHECK(severity IN ('LOW','MEDIUM','HIGH','CRITICAL')),CHECK(status IN ('OPEN','ACKNOWLEDGED','RESOLVED')));
CREATE TABLE safety_incident_events(id TEXT PRIMARY KEY,incident_id TEXT NOT NULL REFERENCES safety_incidents(id),actor_id TEXT REFERENCES users(id),event TEXT NOT NULL,details TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE remote_ai_summaries(case_id TEXT PRIMARY KEY REFERENCES property_service_cases(id),source_hash TEXT NOT NULL,summary TEXT NOT NULL,observations TEXT NOT NULL,limitations TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE subscription_consumptions(id TEXT PRIMARY KEY,subscription_id TEXT NOT NULL REFERENCES customer_subscriptions(id),source_kind TEXT NOT NULL,source_id TEXT NOT NULL,units INTEGER NOT NULL CHECK(units>0),created_at TEXT NOT NULL,UNIQUE(subscription_id,source_kind,source_id));
CREATE INDEX student_pool_trip ON student_pools(trip_id,status);CREATE INDEX marketplace_review_subject ON marketplace_reviews(subject_id,subject_role);CREATE INDEX safety_incident_source ON safety_incidents(source_kind,source_id,status);
`);}
module.exports={installGrowthSchema};